export const CREATE_WORK_ORDER_REQUEST_COPY = {
  title: "New task",
  description: "Create a task for this workspace.",
  titleField: "Title",
  titlePlaceholder: "Title",
  placeholder: "Describe the task. You can attach images and videos.",
  attach: "Attach image or video",
  attachedImages: "Attached files",
  openImage: "Open attachment",
  closeImage: "Close attachment",
  deleteImage: "Delete attachment",
  create: "Create task",
  creating: "Creating...",
  expand: "Open full screen",
  collapse: "Exit full screen",
} as const;
