BEGIN;

ALTER TABLE factories
  ADD COLUMN IF NOT EXISTS planning_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS planning_clarity BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS planning_confidence BOOLEAN NOT NULL DEFAULT TRUE;

COMMIT;
