ALTER TABLE runners ADD COLUMN IF NOT EXISTS tags jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE runners ADD COLUMN IF NOT EXISTS os text NOT NULL DEFAULT '';
ALTER TABLE runners ADD COLUMN IF NOT EXISTS arch text NOT NULL DEFAULT '';
ALTER TABLE runners ADD COLUMN IF NOT EXISTS hostname text NOT NULL DEFAULT '';
ALTER TABLE runners ADD COLUMN IF NOT EXISTS ip text NOT NULL DEFAULT '';
