// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.15.8
// source: scripts.proto

package scripts

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListScriptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScriptsRequest) Reset() {
	*x = ListScriptsRequest{}
	mi := &file_scripts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScriptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScriptsRequest) ProtoMessage() {}

func (x *ListScriptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScriptsRequest.ProtoReflect.Descriptor instead.
func (*ListScriptsRequest) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{0}
}

type ListScriptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scripts       []*Script              `protobuf:"bytes,1,rep,name=scripts,proto3" json:"scripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScriptsResponse) Reset() {
	*x = ListScriptsResponse{}
	mi := &file_scripts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScriptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScriptsResponse) ProtoMessage() {}

func (x *ListScriptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScriptsResponse.ProtoReflect.Descriptor instead.
func (*ListScriptsResponse) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{1}
}

func (x *ListScriptsResponse) GetScripts() []*Script {
	if x != nil {
		return x.Scripts
	}
	return nil
}

type DescribeScriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeScriptRequest) Reset() {
	*x = DescribeScriptRequest{}
	mi := &file_scripts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeScriptRequest) ProtoMessage() {}

func (x *DescribeScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeScriptRequest.ProtoReflect.Descriptor instead.
func (*DescribeScriptRequest) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeScriptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DescribeScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        *Script                `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeScriptResponse) Reset() {
	*x = DescribeScriptResponse{}
	mi := &file_scripts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeScriptResponse) ProtoMessage() {}

func (x *DescribeScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeScriptResponse.ProtoReflect.Descriptor instead.
func (*DescribeScriptResponse) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeScriptResponse) GetScript() *Script {
	if x != nil {
		return x.Script
	}
	return nil
}

type CreateScriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        *Script                `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScriptRequest) Reset() {
	*x = CreateScriptRequest{}
	mi := &file_scripts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScriptRequest) ProtoMessage() {}

func (x *CreateScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScriptRequest.ProtoReflect.Descriptor instead.
func (*CreateScriptRequest) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{4}
}

func (x *CreateScriptRequest) GetScript() *Script {
	if x != nil {
		return x.Script
	}
	return nil
}

type CreateScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        *Script                `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScriptResponse) Reset() {
	*x = CreateScriptResponse{}
	mi := &file_scripts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScriptResponse) ProtoMessage() {}

func (x *CreateScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScriptResponse.ProtoReflect.Descriptor instead.
func (*CreateScriptResponse) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{5}
}

func (x *CreateScriptResponse) GetScript() *Script {
	if x != nil {
		return x.Script
	}
	return nil
}

type UpdateScriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Script        *Script                `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScriptRequest) Reset() {
	*x = UpdateScriptRequest{}
	mi := &file_scripts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScriptRequest) ProtoMessage() {}

func (x *UpdateScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScriptRequest.ProtoReflect.Descriptor instead.
func (*UpdateScriptRequest) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateScriptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateScriptRequest) GetScript() *Script {
	if x != nil {
		return x.Script
	}
	return nil
}

type UpdateScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        *Script                `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScriptResponse) Reset() {
	*x = UpdateScriptResponse{}
	mi := &file_scripts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScriptResponse) ProtoMessage() {}

func (x *UpdateScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScriptResponse.ProtoReflect.Descriptor instead.
func (*UpdateScriptResponse) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateScriptResponse) GetScript() *Script {
	if x != nil {
		return x.Script
	}
	return nil
}

type DeleteScriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScriptRequest) Reset() {
	*x = DeleteScriptRequest{}
	mi := &file_scripts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScriptRequest) ProtoMessage() {}

func (x *DeleteScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScriptRequest.ProtoReflect.Descriptor instead.
func (*DeleteScriptRequest) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteScriptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScriptResponse) Reset() {
	*x = DeleteScriptResponse{}
	mi := &file_scripts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScriptResponse) ProtoMessage() {}

func (x *DeleteScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScriptResponse.ProtoReflect.Descriptor instead.
func (*DeleteScriptResponse) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{9}
}

type GenerateScriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScriptId      string                 `protobuf:"bytes,1,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateScriptRequest) Reset() {
	*x = GenerateScriptRequest{}
	mi := &file_scripts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateScriptRequest) ProtoMessage() {}

func (x *GenerateScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateScriptRequest.ProtoReflect.Descriptor instead.
func (*GenerateScriptRequest) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateScriptRequest) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *GenerateScriptRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GenerateScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateScriptResponse) Reset() {
	*x = GenerateScriptResponse{}
	mi := &file_scripts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateScriptResponse) ProtoMessage() {}

func (x *GenerateScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateScriptResponse.ProtoReflect.Descriptor instead.
func (*GenerateScriptResponse) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateScriptResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *GenerateScriptResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Script struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Label          string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Source         string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	ManifestJson   string                 `protobuf:"bytes,7,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt      *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamp.Timestamp   `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Script) Reset() {
	*x = Script{}
	mi := &file_scripts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Script) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Script) ProtoMessage() {}

func (x *Script) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Script.ProtoReflect.Descriptor instead.
func (*Script) Descriptor() ([]byte, []int) {
	return file_scripts_proto_rawDescGZIP(), []int{12}
}

func (x *Script) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Script) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Script) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Script) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Script) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Script) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Script) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

func (x *Script) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Script) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Script) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Script) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_scripts_proto protoreflect.FileDescriptor

const file_scripts_proto_rawDesc = "" +
	"\n" +
	"\rscripts.proto\x12\x12Superplane.Scripts\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x14\n" +
	"\x12ListScriptsRequest\"K\n" +
	"\x13ListScriptsResponse\x124\n" +
	"\ascripts\x18\x01 \x03(\v2\x1a.Superplane.Scripts.ScriptR\ascripts\"'\n" +
	"\x15DescribeScriptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x16DescribeScriptResponse\x122\n" +
	"\x06script\x18\x01 \x01(\v2\x1a.Superplane.Scripts.ScriptR\x06script\"I\n" +
	"\x13CreateScriptRequest\x122\n" +
	"\x06script\x18\x01 \x01(\v2\x1a.Superplane.Scripts.ScriptR\x06script\"J\n" +
	"\x14CreateScriptResponse\x122\n" +
	"\x06script\x18\x01 \x01(\v2\x1a.Superplane.Scripts.ScriptR\x06script\"Y\n" +
	"\x13UpdateScriptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x06script\x18\x02 \x01(\v2\x1a.Superplane.Scripts.ScriptR\x06script\"J\n" +
	"\x14UpdateScriptResponse\x122\n" +
	"\x06script\x18\x01 \x01(\v2\x1a.Superplane.Scripts.ScriptR\x06script\"%\n" +
	"\x13DeleteScriptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteScriptResponse\"N\n" +
	"\x15GenerateScriptRequest\x12\x1b\n" +
	"\tscript_id\x18\x01 \x01(\tR\bscriptId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x16GenerateScriptResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"\xf7\x02\n" +
	"\x06Script\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12#\n" +
	"\rmanifest_json\x18\a \x01(\tR\fmanifestJson\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xa9\t\n" +
	"\aScripts\x12\xc3\x01\n" +
	"\vListScripts\x12&.Superplane.Scripts.ListScriptsRequest\x1a'.Superplane.Scripts.ListScriptsResponse\"c\x92AI\n" +
	"\x06Script\x12\fList scripts\x1a1Returns a list of all scripts in the organization\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/scripts\x12\xb3\x01\n" +
	"\x0eDescribeScript\x12).Superplane.Scripts.DescribeScriptRequest\x1a*.Superplane.Scripts.DescribeScriptResponse\"J\x92A+\n" +
	"\x06Script\x12\x0fDescribe script\x1a\x10Returns a script\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/scripts/{id}\x12\xb4\x01\n" +
	"\fCreateScript\x12'.Superplane.Scripts.CreateScriptRequest\x1a(.Superplane.Scripts.CreateScriptResponse\"Q\x92A4\n" +
	"\x06Script\x12\rCreate script\x1a\x1bCreates a new in-app script\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/scripts\x12\xb8\x01\n" +
	"\fUpdateScript\x12'.Superplane.Scripts.UpdateScriptRequest\x1a(.Superplane.Scripts.UpdateScriptResponse\"U\x92A3\n" +
	"\x06Script\x12\rUpdate script\x1a\x1aUpdates an existing script\x82\xd3\xe4\x93\x02\x19:\x01*2\x14/api/v1/scripts/{id}\x12\xb5\x01\n" +
	"\fDeleteScript\x12'.Superplane.Scripts.DeleteScriptRequest\x1a(.Superplane.Scripts.DeleteScriptResponse\"R\x92A3\n" +
	"\x06Script\x12\rDelete script\x1a\x1aDeletes an existing script\x82\xd3\xe4\x93\x02\x16*\x14/api/v1/scripts/{id}\x12\xf7\x01\n" +
	"\x0eGenerateScript\x12).Superplane.Scripts.GenerateScriptRequest\x1a*.Superplane.Scripts.GenerateScriptResponse\"\x8d\x01\x92A[\n" +
	"\x06Script\x12\x0fGenerate script\x1a@Uses AI to generate or update script code based on a user prompt\x82\xd3\xe4\x93\x02):\x01*\"$/api/v1/scripts/{script_id}/generateB\xcc\x01\x92A\x91\x01\x12g\n" +
	"\x16Superplane Scripts API\x12!API for Superplane in-app scripts\"%\n" +
	"\vAPI Support\x1a\x16support@superplane.com2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZ5github.com/superplanehq/superplane/pkg/protos/scriptsb\x06proto3"

var (
	file_scripts_proto_rawDescOnce sync.Once
	file_scripts_proto_rawDescData []byte
)

func file_scripts_proto_rawDescGZIP() []byte {
	file_scripts_proto_rawDescOnce.Do(func() {
		file_scripts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scripts_proto_rawDesc), len(file_scripts_proto_rawDesc)))
	})
	return file_scripts_proto_rawDescData
}

var file_scripts_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_scripts_proto_goTypes = []any{
	(*ListScriptsRequest)(nil),     // 0: Superplane.Scripts.ListScriptsRequest
	(*ListScriptsResponse)(nil),    // 1: Superplane.Scripts.ListScriptsResponse
	(*DescribeScriptRequest)(nil),  // 2: Superplane.Scripts.DescribeScriptRequest
	(*DescribeScriptResponse)(nil), // 3: Superplane.Scripts.DescribeScriptResponse
	(*CreateScriptRequest)(nil),    // 4: Superplane.Scripts.CreateScriptRequest
	(*CreateScriptResponse)(nil),   // 5: Superplane.Scripts.CreateScriptResponse
	(*UpdateScriptRequest)(nil),    // 6: Superplane.Scripts.UpdateScriptRequest
	(*UpdateScriptResponse)(nil),   // 7: Superplane.Scripts.UpdateScriptResponse
	(*DeleteScriptRequest)(nil),    // 8: Superplane.Scripts.DeleteScriptRequest
	(*DeleteScriptResponse)(nil),   // 9: Superplane.Scripts.DeleteScriptResponse
	(*GenerateScriptRequest)(nil),  // 10: Superplane.Scripts.GenerateScriptRequest
	(*GenerateScriptResponse)(nil), // 11: Superplane.Scripts.GenerateScriptResponse
	(*Script)(nil),                 // 12: Superplane.Scripts.Script
	(*timestamp.Timestamp)(nil),    // 13: google.protobuf.Timestamp
}
var file_scripts_proto_depIdxs = []int32{
	12, // 0: Superplane.Scripts.ListScriptsResponse.scripts:type_name -> Superplane.Scripts.Script
	12, // 1: Superplane.Scripts.DescribeScriptResponse.script:type_name -> Superplane.Scripts.Script
	12, // 2: Superplane.Scripts.CreateScriptRequest.script:type_name -> Superplane.Scripts.Script
	12, // 3: Superplane.Scripts.CreateScriptResponse.script:type_name -> Superplane.Scripts.Script
	12, // 4: Superplane.Scripts.UpdateScriptRequest.script:type_name -> Superplane.Scripts.Script
	12, // 5: Superplane.Scripts.UpdateScriptResponse.script:type_name -> Superplane.Scripts.Script
	13, // 6: Superplane.Scripts.Script.created_at:type_name -> google.protobuf.Timestamp
	13, // 7: Superplane.Scripts.Script.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: Superplane.Scripts.Scripts.ListScripts:input_type -> Superplane.Scripts.ListScriptsRequest
	2,  // 9: Superplane.Scripts.Scripts.DescribeScript:input_type -> Superplane.Scripts.DescribeScriptRequest
	4,  // 10: Superplane.Scripts.Scripts.CreateScript:input_type -> Superplane.Scripts.CreateScriptRequest
	6,  // 11: Superplane.Scripts.Scripts.UpdateScript:input_type -> Superplane.Scripts.UpdateScriptRequest
	8,  // 12: Superplane.Scripts.Scripts.DeleteScript:input_type -> Superplane.Scripts.DeleteScriptRequest
	10, // 13: Superplane.Scripts.Scripts.GenerateScript:input_type -> Superplane.Scripts.GenerateScriptRequest
	1,  // 14: Superplane.Scripts.Scripts.ListScripts:output_type -> Superplane.Scripts.ListScriptsResponse
	3,  // 15: Superplane.Scripts.Scripts.DescribeScript:output_type -> Superplane.Scripts.DescribeScriptResponse
	5,  // 16: Superplane.Scripts.Scripts.CreateScript:output_type -> Superplane.Scripts.CreateScriptResponse
	7,  // 17: Superplane.Scripts.Scripts.UpdateScript:output_type -> Superplane.Scripts.UpdateScriptResponse
	9,  // 18: Superplane.Scripts.Scripts.DeleteScript:output_type -> Superplane.Scripts.DeleteScriptResponse
	11, // 19: Superplane.Scripts.Scripts.GenerateScript:output_type -> Superplane.Scripts.GenerateScriptResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_scripts_proto_init() }
func file_scripts_proto_init() {
	if File_scripts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scripts_proto_rawDesc), len(file_scripts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scripts_proto_goTypes,
		DependencyIndexes: file_scripts_proto_depIdxs,
		MessageInfos:      file_scripts_proto_msgTypes,
	}.Build()
	File_scripts_proto = out.File
	file_scripts_proto_goTypes = nil
	file_scripts_proto_depIdxs = nil
}
