package daytona

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test__validateSandboxSecrets(t *testing.T) {
	t.Run("valid file secret", func(t *testing.T) {
		err := validateSandboxSecrets([]SandboxSecret{
			{
				Type: SandboxSecretTypeFile,
				Path: "/home/daytona/.ssh/id_rsa",
				Value: SecretKeyRef{
					Secret: "ssh-keys",
					Key:    "sandbox",
				},
			},
		})

		require.NoError(t, err)
	})

	t.Run("valid env-var secret", func(t *testing.T) {
		err := validateSandboxSecrets([]SandboxSecret{
			{
				Type: SandboxSecretTypeEnvVar,
				Name: "GITHUB_TOKEN",
				Value: SecretKeyRef{
					Secret: "credentials",
					Key:    "token",
				},
			},
		})

		require.NoError(t, err)
	})

	t.Run("missing secret ref -> error", func(t *testing.T) {
		err := validateSandboxSecrets([]SandboxSecret{
			{
				Type:  SandboxSecretTypeFile,
				Path:  "/tmp/file",
				Value: SecretKeyRef{},
			},
		})

		require.ErrorContains(t, err, "value.secret")
	})
}

func Test__buildSandboxSecretsEnvScript(t *testing.T) {
	script := buildSandboxSecretsEnvScript([]sandboxEnvBinding{
		{Name: "Z_TOKEN", Path: "/home/daytona/.superplane/secrets/values/Z_TOKEN"},
		{Name: "A_TOKEN", Path: "/home/daytona/.superplane/secrets/values/A_TOKEN"},
	})

	assert.Contains(t, script, "# Generated by SuperPlane")
	assert.Contains(t, script, "export A_TOKEN=\"$(cat '/home/daytona/.superplane/secrets/values/A_TOKEN')\"")
	assert.Contains(t, script, "export Z_TOKEN=\"$(cat '/home/daytona/.superplane/secrets/values/Z_TOKEN')\"")
}

func Test__wrapCommandWithSandboxSecretEnv(t *testing.T) {
	command := wrapCommandWithSandboxSecretEnv("echo hello")
	assert.Contains(t, command, "if [ -f '/home/daytona/.superplane/secrets/env.sh' ]")
	assert.Contains(t, command, "&& echo hello")
}
