services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    ports:
      - "443:443"
    depends_on:
      - app
  app:
    image: ghcr.io/superplanehq/superplane:${IMAGE_TAG}
    environment:
      POSTGRES_DB_SSL: "false"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "superplane"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "the-cake-is-a-lie"
      DB_POOL_SIZE: "5"
      APPLICATION_NAME: "superplane"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
      SWAGGER_BASE_PATH: "/app/api/swagger"
      RBAC_MODEL_PATH: "/app/rbac/rbac_model.conf"
      RBAC_ORG_POLICY_PATH: "/app/rbac/rbac_org_policy.csv"
      RBAC_CANVAS_POLICY_PATH: "/app/rbac/rbac_canvas_policy.csv"
      START_PUBLIC_API: "yes"
      START_INTERNAL_API: "yes"
      START_PENDING_EVENTS_WORKER: "yes"
      START_PENDING_STAGE_EVENTS_WORKER: "yes"
      START_TIME_WINDOW_WORKER: "yes"
      START_STAGE_EVENT_APPROVED_CONSUMER: "yes"
      START_EXECUTIONS_POLLER: "yes"
      START_PENDING_EXECUTIONS_WORKER: "yes"
      START_PENDING_FIELD_SETS_WORKER: "yes"
      START_PENDING_EVENT_SOURCES_WORKER: "yes"
      PUBLIC_API_BASE_PATH: /api/v1
      START_GRPC_GATEWAY: "yes"
      ENCRYPTION_KEY: 1234567890abcdefghijklmnopqrstuv
      JWT_SECRET: 1234567890abcdefghijklmnopqrstuv
      SESSION_SECRET: 1234567890abcdefghijklmnopqrstuv
      GITHUB_CLIENT_ID: 1234567890abcdefghijklmnopqrstuv
      GITHUB_CLIENT_SECRET: 1234567890abcdefghijklmnopqrstuv
      BASE_URL: ${BASE_URL}

    ports:
      - 80:8000
      - 50051:50051

    links:
      - db:db
      - rabbitmq:rabbitmq
    
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  db:
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "the-cake-is-a-lie"
    restart: "on-failure"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.8.17-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    restart: "on-failure"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  postgres-data:
    driver: local
