services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev

    tty: true

    command: go run cmd/main.go
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "superplane"
      DB_USERNAME: "postgres"
      APPLICATION_NAME: "superplane"
      DB_PASSWORD: "the-cake-is-a-lie"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
      SWAGGER_BASE_PATH: "/app/api/swagger"
      START_PUBLIC_API: "yes"
      START_INTERNAL_API: "yes"
      START_PENDING_EVENTS_WORKER: "yes"
      START_PENDING_STAGE_EVENTS_WORKER: "yes"
      START_TIME_WINDOW_WORKER: "yes"
      START_STAGE_EVENT_APPROVED_CONSUMER: "yes"
      START_EXECUTIONS_POLLER: "yes"
      START_PENDING_EXECUTIONS_WORKER: "yes"
      PUBLIC_API_BASE_PATH: /api/v1
      START_GRPC_GATEWAY: "yes"
      ENCRYPTION_KEY: 1234567890abcdefghijklmnopqrstuv
      JWT_SECRET: 1234567890abcdefghijklmnopqrstuv

    ports:
      - 4000:4000
      - 5173:5173
      - 4173:4173
      - 8000:8000
      - 50051:50051

    links:
      - db:db
      - rabbitmq:rabbitmq

    volumes:
      - go-pkg-cache:/go
      - .:/app
      - /tmp:/tmp

    ports:
      - 8000:8000
      - 50051:50051

  db:
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "the-cake-is-a-lie"
  rabbitmq:
    image: rabbitmq:3.8.17-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  repo-data:
    driver: local

  go-pkg-cache:
    driver: local

  postgres-data:
    driver: local
