services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev

    tty: true

    command: go run cmd/server/main.go
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "superplane"
      DB_USERNAME: "postgres"
      APPLICATION_NAME: "superplane"
      DB_PASSWORD: "the-cake-is-a-lie"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
      SWAGGER_BASE_PATH: "/app/api/swagger"
      START_PUBLIC_API: "yes"
      START_INTERNAL_API: "yes"
      START_PENDING_EVENTS_WORKER: "yes"
      START_PENDING_STAGE_EVENTS_WORKER: "yes"
      START_TIME_WINDOW_WORKER: "yes"
      START_STAGE_EVENT_APPROVED_CONSUMER: "yes"
      START_EXECUTIONS_POLLER: "yes"
      START_PENDING_EXECUTIONS_WORKER: "yes"
      PUBLIC_API_BASE_PATH: /api/v1
      ENCRYPTION_KEY: 1234567890abcdefghijklmnopqrstuv
      JWT_SECRET: 1234567890abcdefghijklmnopqrstuv
      NO_ENCRYPTION: "yes"

    ports:
      - 5173:5173
      - 4173:4173
      - 8000:8000
      - 50051:50051

    links:
      - db:db
      - rabbitmq:rabbitmq

    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    volumes:
      - go-pkg-cache:/go
      - .:/app
      - /tmp:/tmp

  db:
    image: postgres:17.5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "the-cake-is-a-lie"
    restart: "on-failure"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
  
  pgweb:
    image: sosedoff/pgweb
    environment:
      DATABASE_URL: "postgres://postgres:the-cake-is-a-lie@db:5432/superplane?sslmode=disable"
    ports:
      - 8081:8081
    links:
      - db:db
    depends_on:
      db:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.8.17-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    restart: "on-failure"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  repo-data:
    driver: local

  go-pkg-cache:
    driver: local

  postgres-data:
    driver: local
