#!/bin/sh

set -e
set -o pipefail

# Pin the exact postgresql-client-17 package version so that `pg_dump`
# produces byte-identical `-- Dumped by pg_dump version ...` header
# comments across builds. Without a pin, apt installs whatever the
# latest patch release happens to be on the day the image is built,
# which makes db/structure.sql (generated by `make db.migrate`) drift
# even when the schema has not changed.
#
# To bump this on purpose (e.g. to pick up a security fix), update the
# version below and regenerate db/structure.sql with `make db.migrate.all`.
PG_CLIENT_VERSION="17.11-1.pgdg22.04+2"

echo "Installing PostgreSQL Client ${PG_CLIENT_VERSION}"

apt-get update -y
apt-get install --no-install-recommends -y ca-certificates curl gnupg

. /etc/os-release
echo "deb http://apt.postgresql.org/pub/repos/apt ${VERSION_CODENAME}-pgdg main" > /etc/apt/sources.list.d/pgdg.list
curl --retry 5 --retry-delay 1 --retry-max-time 60 --retry-connrefused -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg

apt-get update -y
apt-get install --no-install-recommends -y "postgresql-client-17=${PG_CLIENT_VERSION}"
apt-get clean
rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*
