apiVersion: v1
kind: Canvas
metadata:
  name: my-application-canvas
  organizationId: 5684c6ad-51ee-49a8-9d0a-1adb4dc3b75c
  # Canvas is a top-level construct that groups other resources
  # No additional specific fields required besides name
