apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  canvasId: 756541b3-55c9-42b3-97eb-0df272dce061 # Reference to the canvas this secret belongs to
spec:
  provider: PROVIDER_LOCAL # Currently only local provider is supported
  local:
    data:
      api-key: "gdetlTEbvLXnWlQ07KrH"
    # You can add any key-value pairs here
