package claude

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/google/uuid"
	"github.com/mitchellh/mapstructure"
	"github.com/superplanehq/superplane/pkg/configuration"
	"github.com/superplanehq/superplane/pkg/core"
)

const (
	CodeAgentPayloadType   = "claude.codeAgent.finished"
	CodeAgentDefaultModel  = "claude-sonnet-4-6"
	CodeAgentDefaultBranch = "main"
	CodeAgentMaxTokens     = 8192
)

type CodeAgent struct{}

type CodeAgentSpec struct {
	Task          string `json:"task" mapstructure:"task"`
	Model         string `json:"model" mapstructure:"model"`
	Repository    string `json:"repository" mapstructure:"repository"`
	IssueKey      string `json:"issueKey" mapstructure:"issueKey"`
	BaseBranch    string `json:"baseBranch" mapstructure:"baseBranch"`
	GitHubToken   string `json:"githubToken" mapstructure:"githubToken"`
	ReviewComment string `json:"reviewComment" mapstructure:"reviewComment"`
}

type CodeAgentOutputPayload struct {
	Status   string `json:"status"`
	PrURL    string `json:"prUrl,omitempty"`
	PrNumber int    `json:"prNumber,omitempty"`
	Branch   string `json:"branch"`
	Plan     string `json:"plan,omitempty"`
	ErrorMsg string `json:"error,omitempty"`
}

// claudeCodeResponse is the structured JSON we ask Claude to return.
type claudeCodeResponse struct {
	Plan  string            `json:"plan"`
	Files map[string]string `json:"files"`
}

func (c *CodeAgent) Name() string { return "claude.codeAgent" }

func (c *CodeAgent) Label() string { return "Code Agent" }

func (c *CodeAgent) Description() string {
	return "Uses Claude to plan and implement a task, then opens a GitHub PR on a branch named after the issue"
}

func (c *CodeAgent) Documentation() string {
	return `The Code Agent component uses Claude to implement a task and ship it as a GitHub PR.

## How it works
1. Sends the task description to Claude with instructions to produce an implementation plan and code files
2. Creates a new GitHub branch named after the issue key (e.g. KAN-1)
3. Commits the generated files to that branch
4. Opens a pull request and returns its URL

## Configuration
- **Task**: What to implement — supports expressions from upstream nodes
- **Model**: Claude model to use (defaults to claude-sonnet-4-6)
- **Repository**: GitHub repository in owner/repo format (e.g. acme/my-app)
- **Issue Key**: Used as the branch name (e.g. KAN-1)
- **Base Branch**: Branch to fork from (defaults to main)
- **GitHub Token**: Personal access token with repo scope

## Output
- **prUrl**: URL of the opened pull request
- **branch**: Branch name used
- **plan**: Implementation plan generated by Claude
- **status**: succeeded or failed`
}

func (c *CodeAgent) Icon() string  { return "cpu" }
func (c *CodeAgent) Color() string { return "violet" }

func (c *CodeAgent) ExampleOutput() map[string]any {
	return map[string]any{
		"type": CodeAgentPayloadType,
		"data": map[string]any{
			"status": "succeeded",
			"prUrl":  "https://github.com/acme/my-app/pull/7",
			"branch": "KAN-1",
			"plan":   "1. Create landing page component\n2. Add routing\n3. Write tests",
		},
	}
}

func (c *CodeAgent) OutputChannels(config any) []core.OutputChannel {
	return []core.OutputChannel{core.DefaultOutputChannel}
}

func (c *CodeAgent) Configuration() []configuration.Field {
	return []configuration.Field{
		{
			Name:        "task",
			Label:       "Task",
			Type:        configuration.FieldTypeExpression,
			Required:    true,
			Description: "What should be implemented? Supports expressions from upstream nodes.",
			Placeholder: "Add onboarding flow skeleton to the mobile app",
		},
		{
			Name:        "model",
			Label:       "Model",
			Type:        configuration.FieldTypeIntegrationResource,
			Required:    false,
			Default:     CodeAgentDefaultModel,
			TypeOptions: &configuration.TypeOptions{
				Resource: &configuration.ResourceTypeOptions{Type: "model"},
			},
		},
		{
			Name:        "repository",
			Label:       "Repository",
			Type:        configuration.FieldTypeExpression,
			Required:    true,
			Description: "GitHub repository in owner/repo format",
			Placeholder: "acme/my-app",
		},
		{
			Name:        "issueKey",
			Label:       "Issue Key",
			Type:        configuration.FieldTypeExpression,
			Required:    true,
			Description: "Used as the branch name (e.g. KAN-1)",
			Placeholder: "KAN-1",
		},
		{
			Name:        "baseBranch",
			Label:       "Base Branch",
			Type:        configuration.FieldTypeString,
			Required:    false,
			Default:     CodeAgentDefaultBranch,
			Description: "Branch to fork from",
		},
		{
			Name:        "githubToken",
			Label:       "GitHub Token",
			Type:        configuration.FieldTypeExpression,
			Required:    true,
			Description: "GitHub personal access token with repo scope",
		},
	}
}

func (c *CodeAgent) Setup(ctx core.SetupContext) error {
	spec := CodeAgentSpec{}
	if err := mapstructure.Decode(ctx.Configuration, &spec); err != nil {
		return fmt.Errorf("failed to decode configuration: %v", err)
	}

	if spec.Task == "" {
		return fmt.Errorf("task is required")
	}
	if spec.Repository == "" {
		return fmt.Errorf("repository is required")
	}
	if spec.IssueKey == "" {
		return fmt.Errorf("issueKey is required")
	}
	if spec.GitHubToken == "" {
		return fmt.Errorf("githubToken is required")
	}

	return nil
}

func (c *CodeAgent) Execute(ctx core.ExecutionContext) error {
	spec := CodeAgentSpec{}
	if err := mapstructure.Decode(ctx.Configuration, &spec); err != nil {
		return fmt.Errorf("failed to decode configuration: %v", err)
	}

	if spec.Model == "" {
		spec.Model = CodeAgentDefaultModel
	}
	if spec.BaseBranch == "" {
		spec.BaseBranch = CodeAgentDefaultBranch
	}

	ctx.Logger.Infof("[CodeAgent] Starting — task=%q repo=%q branch=%q", spec.Task, spec.Repository, spec.IssueKey)

	// Parse owner/repo
	parts := strings.SplitN(spec.Repository, "/", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return fmt.Errorf("repository must be in owner/repo format")
	}
	owner, repo := parts[0], parts[1]

	// 1. Ask Claude to plan and generate code
	claudeClient, err := NewClient(ctx.HTTP, ctx.Integration)
	if err != nil {
		return fmt.Errorf("failed to create Claude client: %v", err)
	}

	prompt := buildCodeAgentPrompt(spec.Task, spec.Repository, spec.IssueKey)
	ctx.Logger.Infof("[CodeAgent] Calling Claude API model=%q maxTokens=%d", spec.Model, CodeAgentMaxTokens)
	response, err := claudeClient.CreateMessage(CreateMessageRequest{
		Model:     spec.Model,
		MaxTokens: CodeAgentMaxTokens,
		System:    codeAgentSystemPrompt(),
		Messages:  []Message{{Role: "user", Content: prompt}},
	})
	if err != nil {
		return emitFailure(ctx, spec.IssueKey, fmt.Sprintf("Claude API error: %v", err))
	}

	text := extractMessageText(response)
	parsed, err := parseClaudeCodeResponse(text)
	if err != nil {
		ctx.Logger.Warnf("[CodeAgent] JSON parse failed (%v) — raw response: %.500s", err, text)
		parsed = &claudeCodeResponse{
			Plan: text,
			Files: map[string]string{
				"IMPLEMENTATION_PLAN.md": text,
			},
		}
	} else {
		ctx.Logger.Infof("[CodeAgent] Parsed %d files from Claude response", len(parsed.Files))
	}

	ctx.Logger.Infof("[CodeAgent] Claude responded — creating GitHub branch %q", spec.IssueKey)

	// 2. Create branch on GitHub
	ghClient := NewGitHubClient(spec.GitHubToken, ctx.HTTP)

	baseSHA, err := ghClient.GetBranchSHA(owner, repo, spec.BaseBranch)
	if err != nil {
		return emitFailure(ctx, spec.IssueKey, fmt.Sprintf("failed to get base branch SHA: %v", err))
	}

	if err := ghClient.CreateBranch(owner, repo, spec.IssueKey, baseSHA); err != nil {
		return emitFailure(ctx, spec.IssueKey, fmt.Sprintf("failed to create branch: %v", err))
	}

	// 3. Commit generated files
	for path, content := range parsed.Files {
		commitMsg := fmt.Sprintf("%s: %s", spec.IssueKey, path)
		if err := ghClient.CommitFile(owner, repo, spec.IssueKey, path, commitMsg, content); err != nil {
			return emitFailure(ctx, spec.IssueKey, fmt.Sprintf("failed to commit %s: %v", path, err))
		}
	}

	// 4. Open PR
	prTitle := fmt.Sprintf("feat(%s): %s", spec.IssueKey, truncate(spec.Task, 60))
	prBody := buildPRBody(spec.IssueKey, spec.Task, parsed.Plan)
	ctx.Logger.Infof("[CodeAgent] Files committed — opening PR")
	pr, err := ghClient.CreatePR(owner, repo, prTitle, prBody, spec.IssueKey, spec.BaseBranch)
	if err != nil {
		return emitFailure(ctx, spec.IssueKey, fmt.Sprintf("failed to create PR: %v", err))
	}

	ctx.Logger.Infof("[CodeAgent] PR created: %s (#%d)", pr.URL, pr.Number)

	if spec.ReviewComment != "" {
		if err := ghClient.CreatePRComment(owner, repo, pr.Number, spec.ReviewComment); err != nil {
			ctx.Logger.Warnf("[CodeAgent] Failed to post review comment: %v", err)
		} else {
			ctx.Logger.Infof("[CodeAgent] Review comment posted on PR #%d", pr.Number)
		}
	}

	return ctx.ExecutionState.Emit(
		core.DefaultOutputChannel.Name,
		CodeAgentPayloadType,
		[]any{CodeAgentOutputPayload{
			Status:   "succeeded",
			PrURL:    pr.URL,
			PrNumber: pr.Number,
			Branch:   spec.IssueKey,
			Plan:     parsed.Plan,
		}},
	)
}

func emitFailure(ctx core.ExecutionContext, branch, errMsg string) error {
	return ctx.ExecutionState.Emit(
		core.DefaultOutputChannel.Name,
		CodeAgentPayloadType,
		[]any{CodeAgentOutputPayload{
			Status:   "failed",
			Branch:   branch,
			ErrorMsg: errMsg,
		}},
	)
}

func codeAgentSystemPrompt() string {
	return `You are an expert software engineer. You MUST respond with ONLY a valid JSON object — no prose, no markdown, no explanation before or after.

The JSON object must have exactly these two keys:
- "plan": a string with a short implementation plan (use \n for newlines)
- "files": an object where each key is a file path and each value is the complete file content as a string

You MUST include real, working implementation code in "files" — not placeholders or comments.
Escape all double quotes inside file contents as \".
Escape all newlines inside file contents as \n.

Example (follow this format exactly):
{"plan":"1. Create component\n2. Wire routing","files":{"src/App.tsx":"import React from 'react';\nexport default function App() { return <div>Hello</div>; }"}}`
}

func buildCodeAgentPrompt(task, repository, issueKey string) string {
	return fmt.Sprintf(`Task: %s

Repository: %s
Issue: %s

Implement this task. Return a JSON object with your implementation plan and the files to create or modify.
IMPORTANT: Generate at most 2 files. Keep each file under 100 lines. Be concise but complete.`, task, repository, issueKey)
}

func parseClaudeCodeResponse(text string) (*claudeCodeResponse, error) {
	// Strip markdown code fences if present
	text = strings.TrimSpace(text)
	if strings.HasPrefix(text, "```") {
		lines := strings.Split(text, "\n")
		if len(lines) > 2 {
			text = strings.Join(lines[1:len(lines)-1], "\n")
		}
	}

	var result claudeCodeResponse
	if err := json.Unmarshal([]byte(text), &result); err != nil {
		return nil, err
	}

	return &result, nil
}

func buildPRBody(issueKey, task, plan string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("## %s\n\n", issueKey))
	sb.WriteString(fmt.Sprintf("**Task:** %s\n\n", task))
	if plan != "" {
		sb.WriteString("## Implementation Plan\n\n")
		sb.WriteString(plan)
		sb.WriteString("\n\n")
	}
	sb.WriteString("---\n*Generated by Claude Code Agent via SuperPlane*")
	return sb.String()
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}

func (c *CodeAgent) Cancel(ctx core.ExecutionContext) error      { return nil }
func (c *CodeAgent) Cleanup(ctx core.SetupContext) error          { return nil }
func (c *CodeAgent) Actions() []core.Action                       { return []core.Action{} }
func (c *CodeAgent) HandleAction(ctx core.ActionContext) error    { return nil }

func (c *CodeAgent) ProcessQueueItem(ctx core.ProcessQueueContext) (*uuid.UUID, error) {
	return ctx.DefaultProcessing()
}

func (c *CodeAgent) HandleWebhook(ctx core.WebhookRequestContext) (int, *core.WebhookResponseBody, error) {
	return http.StatusOK, nil, nil
}
