package claude

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/google/uuid"
	"github.com/mitchellh/mapstructure"
	"github.com/superplanehq/superplane/pkg/configuration"
	"github.com/superplanehq/superplane/pkg/core"
)

const IncidentReportPayloadType = "claude.incidentReport"

type IncidentReport struct{}

type IncidentReportSpec struct {
	Model         string `json:"model"`
	ContainerName string `json:"containerName"`
	DockerLogs    string `json:"dockerLogs"`
}

type IncidentReportPayload struct {
	ContainerName  string `json:"containerName"`
	DiscordContent string `json:"discordContent"`
}

func (c *IncidentReport) Name() string {
	return "claude.incidentReport"
}

func (c *IncidentReport) Label() string {
	return "Incident Report"
}

func (c *IncidentReport) Description() string {
	return "Analyzes Docker container logs with Claude and produces a formatted Discord incident report"
}

func (c *IncidentReport) Documentation() string {
	return "Analyzes Docker logs using Claude and formats the output as a Discord SRE alert message."
}

func (c *IncidentReport) Icon() string {
	return "alert-triangle"
}

func (c *IncidentReport) Color() string {
	return "red"
}

func (c *IncidentReport) ExampleOutput() map[string]any {
	return map[string]any{
		"containerName":  "api-server",
		"discordContent": "🚨 **SYSTEM ALERT: API-SERVER** 🚨\n\nAnalysis...",
	}
}

func (c *IncidentReport) OutputChannels(configuration any) []core.OutputChannel {
	return []core.OutputChannel{core.DefaultOutputChannel}
}

func (c *IncidentReport) Configuration() []configuration.Field {
	return []configuration.Field{
		{
			Name:        "model",
			Label:       "Model",
			Type:        configuration.FieldTypeIntegrationResource,
			Required:    true,
			Default:     "claude-opus-4-6",
			Placeholder: "Select a Claude model",
			TypeOptions: &configuration.TypeOptions{
				Resource: &configuration.ResourceTypeOptions{
					Type: "model",
				},
			},
		},
		{
			Name:        "containerName",
			Label:       "Container Name",
			Type:        configuration.FieldTypeString,
			Required:    true,
			Placeholder: "e.g. api-server",
			Description: "The name of the affected container",
		},
		{
			Name:        "dockerLogs",
			Label:       "Docker Logs",
			Type:        configuration.FieldTypeText,
			Required:    true,
			Placeholder: "Paste raw Docker/container logs here",
			Description: "The raw error logs from the crashed container",
		},
	}
}

func (c *IncidentReport) Setup(ctx core.SetupContext) error {
	spec := IncidentReportSpec{}
	if err := mapstructure.Decode(ctx.Configuration, &spec); err != nil {
		return fmt.Errorf("failed to decode configuration: %v", err)
	}
	if spec.Model == "" {
		return fmt.Errorf("model is required")
	}
	if spec.ContainerName == "" {
		return fmt.Errorf("containerName is required")
	}
	return nil
}

func (c *IncidentReport) Execute(ctx core.ExecutionContext) error {
	spec := IncidentReportSpec{}
	if err := mapstructure.Decode(ctx.Configuration, &spec); err != nil {
		return fmt.Errorf("failed to decode configuration: %v", err)
	}

	if spec.Model == "" {
		return fmt.Errorf("model is required")
	}
	if spec.ContainerName == "" {
		return fmt.Errorf("containerName is required")
	}

	logs := strings.TrimSpace(spec.DockerLogs)
	if logs == "" {
		logs = "No logs provided. Container exited silently."
	}

	client, err := NewClient(ctx.HTTP, ctx.Integration)
	if err != nil {
		return err
	}

	prompt := fmt.Sprintf(
		"You are an SRE bot. Analyze the following Docker container logs for container '%s' and produce a concise incident summary suitable for a Discord alert. Include: what failed, likely cause, and suggested next steps.\n\nLogs:\n%s",
		spec.ContainerName,
		logs,
	)

	resp, err := client.CreateMessage(CreateMessageRequest{
		Model:     spec.Model,
		MaxTokens: 4096,
		Messages:  []Message{{Role: "user", Content: prompt}},
	})
	if err != nil {
		return fmt.Errorf("Claude API error: %w", err)
	}

	analysis := extractMessageText(resp)
	discordContent := fmt.Sprintf(
		"🚨 **SYSTEM ALERT: %s** 🚨\n\n%s\n\n---\n🤖 *Analysis generated by SuperPlane SRE Agent*",
		strings.ToUpper(spec.ContainerName),
		analysis,
	)

	payload := IncidentReportPayload{
		ContainerName:  spec.ContainerName,
		DiscordContent: discordContent,
	}

	return ctx.ExecutionState.Emit(
		core.DefaultOutputChannel.Name,
		IncidentReportPayloadType,
		[]any{payload},
	)
}

func (c *IncidentReport) Cancel(ctx core.ExecutionContext) error {
	return nil
}

func (c *IncidentReport) Actions() []core.Action {
	return []core.Action{}
}

func (c *IncidentReport) HandleAction(ctx core.ActionContext) error {
	return nil
}

func (c *IncidentReport) HandleWebhook(ctx core.WebhookRequestContext) (int, *core.WebhookResponseBody, error) {
	return http.StatusOK, nil, nil
}

func (c *IncidentReport) ProcessQueueItem(ctx core.ProcessQueueContext) (*uuid.UUID, error) {
	return ctx.DefaultProcessing()
}

func (c *IncidentReport) Cleanup(ctx core.SetupContext) error {
	return nil
}
