import {
  GITHUB_INSTALL_REQUEST_NEXT,
  GITHUB_INSTALL_REQUEST_TITLE,
  githubInstallRequestBody,
} from "@/lib/githubInstallRequestCopy";

export const FIRST_RUN_COPY = {
  chrome: {
    logOut: "Log out",
    switchOrganization: "Switch organization",
    switchWorkspace: "Switch workspace",
    loggedInAs: "Logged in as",
    stepLabel: (step: number, total: number) => `Step ${step} of ${total}`,
    back: "Back",
  },
  welcome: {
    greeting: (firstName: string) => `Hi ${firstName}.`,
    headline: "One-shot the routine work in your backlog",
    intro:
      "SuperPlane finds the tickets agents can finish with high confidence and turns them into review-ready pull requests.",
    getStarted: "Get started",
  },
  connect: {
    headline: "Let's start by connecting your GitHub",
    body: "SuperPlane works in your code and tickets. Both live on GitHub.",
    signedInAs: (login: string) => `You are signed in to GitHub as ${login}.`,
    connectGitHub: "Connect GitHub",
    selectAccount: "Choose the organization SuperPlane should work in",
    selectAccountBody: "This decides which repositories and tickets SuperPlane can read.",
    useAccount: (account: string) => `Use ${account}`,
    missingAccount: "Do not see your GitHub account or organization?",
    installThere: "Install SuperPlane on more GitHub organizations.",
    connectError: "SuperPlane could not connect to GitHub. Check your access and try again.",
    installRequested: GITHUB_INSTALL_REQUEST_TITLE,
    installRequestedBody: githubInstallRequestBody,
    installRequestedNext: GITHUB_INSTALL_REQUEST_NEXT,
    openingGitHub: "Opening GitHub…",
    loadingAccounts: "Loading GitHub accounts…",
    connectingAccount: (account: string) => `Connecting ${account}…`,
  },
  choose: {
    headline: "Choose the repository where SuperPlane will open pull requests",
    repositoryLabel: "Repository",
    repositoryHelper: "Tickets are scored against this codebase, and finished work comes back here for review.",
    searchPlaceholder: "Search repositories",
    missingRepository: "Do not see your repository?",
    editConnection: "Grant access to more repositories.",
    accessHint: "You need admin access to the GitHub App or organization to change the repositories.",
    continue: "Choose a repository to continue",
    continueReady: "Continue",
    saving: "Saving repository…",
    loading: "Loading repositories…",
    moreLater: "You can add more repositories later.",
    missingTitle: "Why is my repository not shown?",
    missingReasons: [
      "The repository must be granted to the SuperPlane GitHub App.",
      "You need admin rights on the GitHub organization to add a repository.",
      "Editing the connection opens GitHub. A 404 there means you do not have access.",
    ],
  },
  tickets: {
    headline: "Choose the backlog SuperPlane should scan for routine work",
    intro: "SuperPlane reads these tickets and scores each one by how likely an agent can complete it.",
    githubIssues: "GitHub Issues",
    jira: "Jira",
    linear: "Linear",
    githubIssuesHelper: "Issues on this repository. No extra setup.",
    jiraHelper: "Scan your Jira backlog.",
    linearHelper: "Scan your Linear backlog.",
    analyze: "Scan my backlog",
    continue: "Connect agent",
    saving: "Saving ticket source…",
  },
  agent: {
    headline: "Connect agent",
    loading: "Checking agent availability…",
  },
  // Shared by every screen that provisions the workspace. Hosted credentials
  // move that action from the agent screen to the ticket screen.
  finish: {
    action: "Finish setup",
    saving: "Finishing setup…",
  },
  analysis: {
    headline: "Finding tickets SuperPlane can one-shot",
    body: "Each open ticket gets a confidence score. High-confidence work is ready to run. Ambiguous work stays with your team.",
    stageImporting: "Importing your backlog…",
    stageImported: (count: number) => `Backlog imported — ${count} tickets`,
    stageScoring: (scored: number, total: number) => `Scoring tickets… ${scored} of ${total}`,
    stageBoard: "Building your board",
    goToBoard: "Go to your board",
    note: "Scoring continues on the board. No work starts until you approve a ticket.",
    failure: "SuperPlane could not read the scoring progress. Your board still works.",
  },
  sphere: {
    phases: ["01 Plan", "02 Build", "03 Check", "04 Review"],
    discover: "Discover",
    verify: "Verify",
    awaitingCode: "Awaiting code",
    reviewReadyPr: "Review-ready PR",
    ticketsFound: (count: number) => `${count} tickets found`,
    captionSetup: "Awaiting setup",
    captionConnect: "Awaiting GitHub connection",
    captionOrganization: "Awaiting organization",
    captionRepository: (repository: string) => `Repository: ${repository}`,
    captionAwaitingRepository: "Awaiting repository",
    captionTickets: "Awaiting ticket source",
    captionScoring: (repository: string) => `Scoring: ${repository}`,
  },
  results: {
    headline: "Tickets SuperPlane can implement",
    subhead: "Each score shows how confident SuperPlane is that an agent can complete the ticket correctly.",
    approve: "Approve",
    approved: "Approved",
    helper: "Work starts only on tickets you approve.",
    empty: "No tickets scored above 65%. Connect more of your backlog or create a task yourself.",
    rescan: "Rescan backlog",
  },
  board: {
    backlogHintTitle: "Tickets land here first.",
    backlogHintBody:
      "New issues become tasks here. SuperPlane scores them for how well an agent can complete the work.",
  },
} as const;
