/*
Superplane Organizations API

Testing SecretAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi_client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/openapi_client"
)

func Test_openapi_client_SecretAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SecretAPIService SecretsCreateSecret", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SecretAPI.SecretsCreateSecret(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretAPIService SecretsDeleteSecret", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var idOrName string

		resp, httpRes, err := apiClient.SecretAPI.SecretsDeleteSecret(context.Background(), idOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretAPIService SecretsDescribeSecret", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var idOrName string

		resp, httpRes, err := apiClient.SecretAPI.SecretsDescribeSecret(context.Background(), idOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretAPIService SecretsListSecrets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SecretAPI.SecretsListSecrets(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretAPIService SecretsUpdateSecret", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var idOrName string

		resp, httpRes, err := apiClient.SecretAPI.SecretsUpdateSecret(context.Background(), idOrName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
