{{- if eq .Values.posthog.secretName "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.posthog.name" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ if .Values.posthog.enabled }}
  {{ $key := .Values.posthog.key | required ".Values.posthog.key is required." -}}
  POSTHOG_KEY: {{ $key }}
{{- end }}
{{- end }}
