# coding: utf-8

"""
    Superplane Organizations API

    API for managing organizations in the Superplane service

    The version of the OpenAPI document: 1.0
    Contact: support@superplane.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from superplaneapi.models.configuration_required_condition import ConfigurationRequiredCondition
from superplaneapi.models.configuration_visibility_condition import ConfigurationVisibilityCondition
from typing import Optional, Set
from typing_extensions import Self

class ConfigurationField(BaseModel):
    """
    ConfigurationField
    """ # noqa: E501
    name: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    required: Optional[StrictBool] = None
    default_value: Optional[StrictStr] = Field(default=None, alias="defaultValue")
    label: Optional[StrictStr] = None
    visibility_conditions: Optional[List[ConfigurationVisibilityCondition]] = Field(default=None, alias="visibilityConditions")
    type_options: Optional[ConfigurationTypeOptions] = Field(default=None, alias="typeOptions")
    required_conditions: Optional[List[ConfigurationRequiredCondition]] = Field(default=None, alias="requiredConditions")
    placeholder: Optional[StrictStr] = None
    sensitive: Optional[StrictBool] = None
    togglable: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["name", "type", "description", "required", "defaultValue", "label", "visibilityConditions", "typeOptions", "requiredConditions", "placeholder", "sensitive", "togglable"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigurationField from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in visibility_conditions (list)
        _items = []
        if self.visibility_conditions:
            for _item_visibility_conditions in self.visibility_conditions:
                if _item_visibility_conditions:
                    _items.append(_item_visibility_conditions.to_dict())
            _dict['visibilityConditions'] = _items
        # override the default output from pydantic by calling `to_dict()` of type_options
        if self.type_options:
            _dict['typeOptions'] = self.type_options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in required_conditions (list)
        _items = []
        if self.required_conditions:
            for _item_required_conditions in self.required_conditions:
                if _item_required_conditions:
                    _items.append(_item_required_conditions.to_dict())
            _dict['requiredConditions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigurationField from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "type": obj.get("type"),
            "description": obj.get("description"),
            "required": obj.get("required"),
            "defaultValue": obj.get("defaultValue"),
            "label": obj.get("label"),
            "visibilityConditions": [ConfigurationVisibilityCondition.from_dict(_item) for _item in obj["visibilityConditions"]] if obj.get("visibilityConditions") is not None else None,
            "typeOptions": ConfigurationTypeOptions.from_dict(obj["typeOptions"]) if obj.get("typeOptions") is not None else None,
            "requiredConditions": [ConfigurationRequiredCondition.from_dict(_item) for _item in obj["requiredConditions"]] if obj.get("requiredConditions") is not None else None,
            "placeholder": obj.get("placeholder"),
            "sensitive": obj.get("sensitive"),
            "togglable": obj.get("togglable")
        })
        return _obj

from superplaneapi.models.configuration_type_options import ConfigurationTypeOptions
# TODO: Rewrite to not use raise_errors
ConfigurationField.model_rebuild(raise_errors=False)

