# coding: utf-8

"""
    Superplane Organizations API

    API for managing organizations in the Superplane service

    The version of the OpenAPI document: 1.0
    Contact: support@superplane.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class OrganizationsAgentOpenAIKey(BaseModel):
    """
    OrganizationsAgentOpenAIKey
    """ # noqa: E501
    configured: Optional[StrictBool] = None
    last4: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    validation_error: Optional[StrictStr] = Field(default=None, alias="validationError")
    validated_at: Optional[datetime] = Field(default=None, alias="validatedAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    updated_by: Optional[StrictStr] = Field(default=None, alias="updatedBy")
    __properties: ClassVar[List[str]] = ["configured", "last4", "status", "validationError", "validatedAt", "updatedAt", "updatedBy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrganizationsAgentOpenAIKey from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrganizationsAgentOpenAIKey from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "configured": obj.get("configured"),
            "last4": obj.get("last4"),
            "status": obj.get("status"),
            "validationError": obj.get("validationError"),
            "validatedAt": obj.get("validatedAt"),
            "updatedAt": obj.get("updatedAt"),
            "updatedBy": obj.get("updatedBy")
        })
        return _obj


