# coding: utf-8

"""
    Superplane Organizations API

    API for managing organizations in the Superplane service

    The version of the OpenAPI document: 1.0
    Contact: support@superplane.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from superplaneapi.models.organizations_organization_limits import OrganizationsOrganizationLimits
from superplaneapi.models.organizations_organization_usage import OrganizationsOrganizationUsage
from typing import Optional, Set
from typing_extensions import Self

class OrganizationsDescribeUsageResponse(BaseModel):
    """
    OrganizationsDescribeUsageResponse
    """ # noqa: E501
    enabled: Optional[StrictBool] = None
    status_message: Optional[StrictStr] = Field(default=None, alias="statusMessage")
    limits: Optional[OrganizationsOrganizationLimits] = None
    usage: Optional[OrganizationsOrganizationUsage] = None
    __properties: ClassVar[List[str]] = ["enabled", "statusMessage", "limits", "usage"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrganizationsDescribeUsageResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of limits
        if self.limits:
            _dict['limits'] = self.limits.to_dict()
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrganizationsDescribeUsageResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enabled": obj.get("enabled"),
            "statusMessage": obj.get("statusMessage"),
            "limits": OrganizationsOrganizationLimits.from_dict(obj["limits"]) if obj.get("limits") is not None else None,
            "usage": OrganizationsOrganizationUsage.from_dict(obj["usage"]) if obj.get("usage") is not None else None
        })
        return _obj


