/** User-facing copy for workspace Agent resources. STE. */

export const AGENT_RESOURCES_COPY = {
  title: "Agent resources",
  helper:
    "Agents on every run in this workspace can use these resources. One signed-in account is shared by every agent.",
  refinementNote:
    "These connections can change systems outside SuperPlane during refinement. The repository stays read-only.",
  connectionsTab: "Connections",
  skillsTab: "Skills",
  addConnection: "Add connection",
  editConnection: "Edit connection",
  addSkill: "Add skill",
  skillsUnavailable: "Skills are not available yet.",
  emptyConnectionsTitle: "No MCP connections yet.",
  emptyConnectionsBody: "Add a connection so agents can use it on every run.",
  emptySkillsTitle: "Skills are not available yet.",
  emptySkillsBody: "SuperPlane will load skill packages from GitHub on this tab.",
  authHeader: "Header",
  authSignIn: "Sign-in",
  statusConnected: "Connected",
  statusNotConnected: "Not connected",
  statusReconnect: "Reconnect",
  statusReady: "Ready",
  statusFetchFailed: "Failed to fetch",
  connect: "Connect",
  reconnect: "Reconnect",
  disconnect: "Disconnect",
  edit: "Edit",
  delete: "Delete",
  saveConnection: "Save connection",
  cancel: "Cancel",
  nameLabel: "Name",
  nameHelper: "Use lowercase letters, numbers, and dashes. The name superplane is reserved.",
  urlLabel: "URL",
  urlHelper: "Use an https URL. Private hosts are not allowed.",
  authLabel: "Authentication",
  headersLabel: "Headers",
  headerNameLabel: "Header name",
  headerSecretLabel: "Secret",
  addHeader: "Add header",
  removeHeader: "Remove header",
  loading: "Loading agent resources...",
  loadError: "SuperPlane could not load agent resources. Try again.",
  nameRequired: "Name is required.",
  nameInvalid: "Use a lowercase name that starts with a letter. Use letters, numbers, and dashes.",
  nameReserved: "The name superplane is reserved.",
  urlRequired: "URL is required.",
  urlInvalid: "Enter an https URL.",
  headersHelper: "Add a header only when the server needs a credential.",
  headerIncomplete: "Each header needs a name and a secret.",
  created: "Connection added.",
  updated: "Connection updated.",
  deleted: "Connection deleted.",
  disconnected: "Connection disconnected.",
  createFailed: "SuperPlane could not add the connection.",
  updateFailed: "SuperPlane could not update the connection.",
  deleteFailed: "SuperPlane could not delete the connection.",
  connectFailed: "SuperPlane could not start sign-in.",
  disconnectFailed: "SuperPlane could not disconnect the connection.",
  noUpdatePermission: "You do not have permission to update agent resources.",
} as const;
