/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
	"fmt"
)

// AuthorizationSubjectIdentifierType the model 'AuthorizationSubjectIdentifierType'
type AuthorizationSubjectIdentifierType string

// List of AuthorizationSubjectIdentifierType
const (
	AUTHORIZATIONSUBJECTIDENTIFIERTYPE_USER_ID AuthorizationSubjectIdentifierType = "USER_ID"
	AUTHORIZATIONSUBJECTIDENTIFIERTYPE_USER_EMAIL AuthorizationSubjectIdentifierType = "USER_EMAIL"
	AUTHORIZATIONSUBJECTIDENTIFIERTYPE_INVITATION_ID AuthorizationSubjectIdentifierType = "INVITATION_ID"
)

// All allowed values of AuthorizationSubjectIdentifierType enum
var AllowedAuthorizationSubjectIdentifierTypeEnumValues = []AuthorizationSubjectIdentifierType{
	"USER_ID",
	"USER_EMAIL",
	"INVITATION_ID",
}

func (v *AuthorizationSubjectIdentifierType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AuthorizationSubjectIdentifierType(value)
	for _, existing := range AllowedAuthorizationSubjectIdentifierTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AuthorizationSubjectIdentifierType", value)
}

// NewAuthorizationSubjectIdentifierTypeFromValue returns a pointer to a valid AuthorizationSubjectIdentifierType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAuthorizationSubjectIdentifierTypeFromValue(v string) (*AuthorizationSubjectIdentifierType, error) {
	ev := AuthorizationSubjectIdentifierType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AuthorizationSubjectIdentifierType: valid values are %v", v, AllowedAuthorizationSubjectIdentifierTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AuthorizationSubjectIdentifierType) IsValid() bool {
	for _, existing := range AllowedAuthorizationSubjectIdentifierTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AuthorizationSubjectIdentifierType value
func (v AuthorizationSubjectIdentifierType) Ptr() *AuthorizationSubjectIdentifierType {
	return &v
}

type NullableAuthorizationSubjectIdentifierType struct {
	value *AuthorizationSubjectIdentifierType
	isSet bool
}

func (v NullableAuthorizationSubjectIdentifierType) Get() *AuthorizationSubjectIdentifierType {
	return v.value
}

func (v *NullableAuthorizationSubjectIdentifierType) Set(val *AuthorizationSubjectIdentifierType) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizationSubjectIdentifierType) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizationSubjectIdentifierType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizationSubjectIdentifierType(val *AuthorizationSubjectIdentifierType) *NullableAuthorizationSubjectIdentifierType {
	return &NullableAuthorizationSubjectIdentifierType{value: val, isSet: true}
}

func (v NullableAuthorizationSubjectIdentifierType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizationSubjectIdentifierType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

