/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the VersionManifestIntegration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VersionManifestIntegration{}

// VersionManifestIntegration struct for VersionManifestIntegration
type VersionManifestIntegration struct {
	Name          *string                     `json:"name,omitempty"`
	Label         *string                     `json:"label,omitempty"`
	Description   *string                     `json:"description,omitempty"`
	Instructions  *string                     `json:"instructions,omitempty"`
	Configuration []ConfigurationField        `json:"configuration,omitempty"`
	ResourceTypes []string                    `json:"resourceTypes,omitempty"`
	Actions       []ComponentsComponentAction `json:"actions,omitempty"`
}

// NewVersionManifestIntegration instantiates a new VersionManifestIntegration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVersionManifestIntegration() *VersionManifestIntegration {
	this := VersionManifestIntegration{}
	return &this
}

// NewVersionManifestIntegrationWithDefaults instantiates a new VersionManifestIntegration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVersionManifestIntegrationWithDefaults() *VersionManifestIntegration {
	this := VersionManifestIntegration{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *VersionManifestIntegration) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VersionManifestIntegration) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *VersionManifestIntegration) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *VersionManifestIntegration) SetName(v string) {
	o.Name = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *VersionManifestIntegration) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VersionManifestIntegration) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *VersionManifestIntegration) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *VersionManifestIntegration) SetLabel(v string) {
	o.Label = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *VersionManifestIntegration) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VersionManifestIntegration) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *VersionManifestIntegration) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *VersionManifestIntegration) SetDescription(v string) {
	o.Description = &v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *VersionManifestIntegration) GetInstructions() string {
	if o == nil || IsNil(o.Instructions) {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VersionManifestIntegration) GetInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.Instructions) {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *VersionManifestIntegration) HasInstructions() bool {
	if o != nil && !IsNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *VersionManifestIntegration) SetInstructions(v string) {
	o.Instructions = &v
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *VersionManifestIntegration) GetConfiguration() []ConfigurationField {
	if o == nil || IsNil(o.Configuration) {
		var ret []ConfigurationField
		return ret
	}
	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VersionManifestIntegration) GetConfigurationOk() ([]ConfigurationField, bool) {
	if o == nil || IsNil(o.Configuration) {
		return nil, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *VersionManifestIntegration) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given []ConfigurationField and assigns it to the Configuration field.
func (o *VersionManifestIntegration) SetConfiguration(v []ConfigurationField) {
	o.Configuration = v
}

// GetResourceTypes returns the ResourceTypes field value if set, zero value otherwise.
func (o *VersionManifestIntegration) GetResourceTypes() []string {
	if o == nil || IsNil(o.ResourceTypes) {
		var ret []string
		return ret
	}
	return o.ResourceTypes
}

// GetResourceTypesOk returns a tuple with the ResourceTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VersionManifestIntegration) GetResourceTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.ResourceTypes) {
		return nil, false
	}
	return o.ResourceTypes, true
}

// HasResourceTypes returns a boolean if a field has been set.
func (o *VersionManifestIntegration) HasResourceTypes() bool {
	if o != nil && !IsNil(o.ResourceTypes) {
		return true
	}

	return false
}

// SetResourceTypes gets a reference to the given []string and assigns it to the ResourceTypes field.
func (o *VersionManifestIntegration) SetResourceTypes(v []string) {
	o.ResourceTypes = v
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *VersionManifestIntegration) GetActions() []ComponentsComponentAction {
	if o == nil || IsNil(o.Actions) {
		var ret []ComponentsComponentAction
		return ret
	}
	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VersionManifestIntegration) GetActionsOk() ([]ComponentsComponentAction, bool) {
	if o == nil || IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *VersionManifestIntegration) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given []ComponentsComponentAction and assigns it to the Actions field.
func (o *VersionManifestIntegration) SetActions(v []ComponentsComponentAction) {
	o.Actions = v
}

func (o VersionManifestIntegration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VersionManifestIntegration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	if !IsNil(o.ResourceTypes) {
		toSerialize["resourceTypes"] = o.ResourceTypes
	}
	if !IsNil(o.Actions) {
		toSerialize["actions"] = o.Actions
	}
	return toSerialize, nil
}

type NullableVersionManifestIntegration struct {
	value *VersionManifestIntegration
	isSet bool
}

func (v NullableVersionManifestIntegration) Get() *VersionManifestIntegration {
	return v.value
}

func (v *NullableVersionManifestIntegration) Set(val *VersionManifestIntegration) {
	v.value = val
	v.isSet = true
}

func (v NullableVersionManifestIntegration) IsSet() bool {
	return v.isSet
}

func (v *NullableVersionManifestIntegration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVersionManifestIntegration(val *VersionManifestIntegration) *NullableVersionManifestIntegration {
	return &NullableVersionManifestIntegration{value: val, isSet: true}
}

func (v NullableVersionManifestIntegration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVersionManifestIntegration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
