/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the ConfigurationTogglableStringTypeOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurationTogglableStringTypeOptions{}

// ConfigurationTogglableStringTypeOptions struct for ConfigurationTogglableStringTypeOptions
type ConfigurationTogglableStringTypeOptions struct {
	Placeholder *string `json:"placeholder,omitempty"`
}

// NewConfigurationTogglableStringTypeOptions instantiates a new ConfigurationTogglableStringTypeOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationTogglableStringTypeOptions() *ConfigurationTogglableStringTypeOptions {
	this := ConfigurationTogglableStringTypeOptions{}
	return &this
}

// NewConfigurationTogglableStringTypeOptionsWithDefaults instantiates a new ConfigurationTogglableStringTypeOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationTogglableStringTypeOptionsWithDefaults() *ConfigurationTogglableStringTypeOptions {
	this := ConfigurationTogglableStringTypeOptions{}
	return &this
}

// GetPlaceholder returns the Placeholder field value if set, zero value otherwise.
func (o *ConfigurationTogglableStringTypeOptions) GetPlaceholder() string {
	if o == nil || IsNil(o.Placeholder) {
		var ret string
		return ret
	}
	return *o.Placeholder
}

// GetPlaceholderOk returns a tuple with the Placeholder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationTogglableStringTypeOptions) GetPlaceholderOk() (*string, bool) {
	if o == nil || IsNil(o.Placeholder) {
		return nil, false
	}
	return o.Placeholder, true
}

// HasPlaceholder returns a boolean if a field has been set.
func (o *ConfigurationTogglableStringTypeOptions) HasPlaceholder() bool {
	if o != nil && !IsNil(o.Placeholder) {
		return true
	}

	return false
}

// SetPlaceholder gets a reference to the given string and assigns it to the Placeholder field.
func (o *ConfigurationTogglableStringTypeOptions) SetPlaceholder(v string) {
	o.Placeholder = &v
}

func (o ConfigurationTogglableStringTypeOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurationTogglableStringTypeOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Placeholder) {
		toSerialize["placeholder"] = o.Placeholder
	}
	return toSerialize, nil
}

type NullableConfigurationTogglableStringTypeOptions struct {
	value *ConfigurationTogglableStringTypeOptions
	isSet bool
}

func (v NullableConfigurationTogglableStringTypeOptions) Get() *ConfigurationTogglableStringTypeOptions {
	return v.value
}

func (v *NullableConfigurationTogglableStringTypeOptions) Set(val *ConfigurationTogglableStringTypeOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationTogglableStringTypeOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationTogglableStringTypeOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationTogglableStringTypeOptions(val *ConfigurationTogglableStringTypeOptions) *NullableConfigurationTogglableStringTypeOptions {
	return &NullableConfigurationTogglableStringTypeOptions{value: val, isSet: true}
}

func (v NullableConfigurationTogglableStringTypeOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationTogglableStringTypeOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
