/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the AgentsCreateAgentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentsCreateAgentResponse{}

// AgentsCreateAgentResponse struct for AgentsCreateAgentResponse
type AgentsCreateAgentResponse struct {
	Token *string `json:"token,omitempty"`
	Url   *string `json:"url,omitempty"`
}

// NewAgentsCreateAgentResponse instantiates a new AgentsCreateAgentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentsCreateAgentResponse() *AgentsCreateAgentResponse {
	this := AgentsCreateAgentResponse{}
	return &this
}

// NewAgentsCreateAgentResponseWithDefaults instantiates a new AgentsCreateAgentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentsCreateAgentResponseWithDefaults() *AgentsCreateAgentResponse {
	this := AgentsCreateAgentResponse{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *AgentsCreateAgentResponse) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsCreateAgentResponse) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *AgentsCreateAgentResponse) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *AgentsCreateAgentResponse) SetToken(v string) {
	o.Token = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *AgentsCreateAgentResponse) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsCreateAgentResponse) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *AgentsCreateAgentResponse) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *AgentsCreateAgentResponse) SetUrl(v string) {
	o.Url = &v
}

func (o AgentsCreateAgentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentsCreateAgentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableAgentsCreateAgentResponse struct {
	value *AgentsCreateAgentResponse
	isSet bool
}

func (v NullableAgentsCreateAgentResponse) Get() *AgentsCreateAgentResponse {
	return v.value
}

func (v *NullableAgentsCreateAgentResponse) Set(val *AgentsCreateAgentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentsCreateAgentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentsCreateAgentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentsCreateAgentResponse(val *AgentsCreateAgentResponse) *NullableAgentsCreateAgentResponse {
	return &NullableAgentsCreateAgentResponse{value: val, isSet: true}
}

func (v NullableAgentsCreateAgentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentsCreateAgentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
