/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the CanvasesCreateCanvasChangeRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CanvasesCreateCanvasChangeRequestBody{}

// CanvasesCreateCanvasChangeRequestBody struct for CanvasesCreateCanvasChangeRequestBody
type CanvasesCreateCanvasChangeRequestBody struct {
	VersionId *string `json:"versionId,omitempty"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewCanvasesCreateCanvasChangeRequestBody instantiates a new CanvasesCreateCanvasChangeRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCanvasesCreateCanvasChangeRequestBody() *CanvasesCreateCanvasChangeRequestBody {
	this := CanvasesCreateCanvasChangeRequestBody{}
	return &this
}

// NewCanvasesCreateCanvasChangeRequestBodyWithDefaults instantiates a new CanvasesCreateCanvasChangeRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCanvasesCreateCanvasChangeRequestBodyWithDefaults() *CanvasesCreateCanvasChangeRequestBody {
	this := CanvasesCreateCanvasChangeRequestBody{}
	return &this
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *CanvasesCreateCanvasChangeRequestBody) GetVersionId() string {
	if o == nil || IsNil(o.VersionId) {
		var ret string
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCreateCanvasChangeRequestBody) GetVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *CanvasesCreateCanvasChangeRequestBody) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given string and assigns it to the VersionId field.
func (o *CanvasesCreateCanvasChangeRequestBody) SetVersionId(v string) {
	o.VersionId = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CanvasesCreateCanvasChangeRequestBody) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCreateCanvasChangeRequestBody) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CanvasesCreateCanvasChangeRequestBody) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CanvasesCreateCanvasChangeRequestBody) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CanvasesCreateCanvasChangeRequestBody) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCreateCanvasChangeRequestBody) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CanvasesCreateCanvasChangeRequestBody) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CanvasesCreateCanvasChangeRequestBody) SetDescription(v string) {
	o.Description = &v
}

func (o CanvasesCreateCanvasChangeRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CanvasesCreateCanvasChangeRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VersionId) {
		toSerialize["versionId"] = o.VersionId
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableCanvasesCreateCanvasChangeRequestBody struct {
	value *CanvasesCreateCanvasChangeRequestBody
	isSet bool
}

func (v NullableCanvasesCreateCanvasChangeRequestBody) Get() *CanvasesCreateCanvasChangeRequestBody {
	return v.value
}

func (v *NullableCanvasesCreateCanvasChangeRequestBody) Set(val *CanvasesCreateCanvasChangeRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCanvasesCreateCanvasChangeRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCanvasesCreateCanvasChangeRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCanvasesCreateCanvasChangeRequestBody(val *CanvasesCreateCanvasChangeRequestBody) *NullableCanvasesCreateCanvasChangeRequestBody {
	return &NullableCanvasesCreateCanvasChangeRequestBody{value: val, isSet: true}
}

func (v NullableCanvasesCreateCanvasChangeRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCanvasesCreateCanvasChangeRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


