/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the OrganizationsUpdateInviteLinkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsUpdateInviteLinkResponse{}

// OrganizationsUpdateInviteLinkResponse struct for OrganizationsUpdateInviteLinkResponse
type OrganizationsUpdateInviteLinkResponse struct {
	InviteLink *OrganizationsInviteLink `json:"inviteLink,omitempty"`
}

// NewOrganizationsUpdateInviteLinkResponse instantiates a new OrganizationsUpdateInviteLinkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsUpdateInviteLinkResponse() *OrganizationsUpdateInviteLinkResponse {
	this := OrganizationsUpdateInviteLinkResponse{}
	return &this
}

// NewOrganizationsUpdateInviteLinkResponseWithDefaults instantiates a new OrganizationsUpdateInviteLinkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsUpdateInviteLinkResponseWithDefaults() *OrganizationsUpdateInviteLinkResponse {
	this := OrganizationsUpdateInviteLinkResponse{}
	return &this
}

// GetInviteLink returns the InviteLink field value if set, zero value otherwise.
func (o *OrganizationsUpdateInviteLinkResponse) GetInviteLink() OrganizationsInviteLink {
	if o == nil || IsNil(o.InviteLink) {
		var ret OrganizationsInviteLink
		return ret
	}
	return *o.InviteLink
}

// GetInviteLinkOk returns a tuple with the InviteLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsUpdateInviteLinkResponse) GetInviteLinkOk() (*OrganizationsInviteLink, bool) {
	if o == nil || IsNil(o.InviteLink) {
		return nil, false
	}
	return o.InviteLink, true
}

// HasInviteLink returns a boolean if a field has been set.
func (o *OrganizationsUpdateInviteLinkResponse) HasInviteLink() bool {
	if o != nil && !IsNil(o.InviteLink) {
		return true
	}

	return false
}

// SetInviteLink gets a reference to the given OrganizationsInviteLink and assigns it to the InviteLink field.
func (o *OrganizationsUpdateInviteLinkResponse) SetInviteLink(v OrganizationsInviteLink) {
	o.InviteLink = &v
}

func (o OrganizationsUpdateInviteLinkResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsUpdateInviteLinkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InviteLink) {
		toSerialize["inviteLink"] = o.InviteLink
	}
	return toSerialize, nil
}

type NullableOrganizationsUpdateInviteLinkResponse struct {
	value *OrganizationsUpdateInviteLinkResponse
	isSet bool
}

func (v NullableOrganizationsUpdateInviteLinkResponse) Get() *OrganizationsUpdateInviteLinkResponse {
	return v.value
}

func (v *NullableOrganizationsUpdateInviteLinkResponse) Set(val *OrganizationsUpdateInviteLinkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsUpdateInviteLinkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsUpdateInviteLinkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsUpdateInviteLinkResponse(val *OrganizationsUpdateInviteLinkResponse) *NullableOrganizationsUpdateInviteLinkResponse {
	return &NullableOrganizationsUpdateInviteLinkResponse{value: val, isSet: true}
}

func (v NullableOrganizationsUpdateInviteLinkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsUpdateInviteLinkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
