/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the CanvasesCanvasVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CanvasesCanvasVersion{}

// CanvasesCanvasVersion struct for CanvasesCanvasVersion
type CanvasesCanvasVersion struct {
	Metadata *CanvasesCanvasVersionMetadata `json:"metadata,omitempty"`
	Spec     *CanvasesCanvasSpec            `json:"spec,omitempty"`
}

// NewCanvasesCanvasVersion instantiates a new CanvasesCanvasVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCanvasesCanvasVersion() *CanvasesCanvasVersion {
	this := CanvasesCanvasVersion{}
	return &this
}

// NewCanvasesCanvasVersionWithDefaults instantiates a new CanvasesCanvasVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCanvasesCanvasVersionWithDefaults() *CanvasesCanvasVersion {
	this := CanvasesCanvasVersion{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CanvasesCanvasVersion) GetMetadata() CanvasesCanvasVersionMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret CanvasesCanvasVersionMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCanvasVersion) GetMetadataOk() (*CanvasesCanvasVersionMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CanvasesCanvasVersion) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given CanvasesCanvasVersionMetadata and assigns it to the Metadata field.
func (o *CanvasesCanvasVersion) SetMetadata(v CanvasesCanvasVersionMetadata) {
	o.Metadata = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *CanvasesCanvasVersion) GetSpec() CanvasesCanvasSpec {
	if o == nil || IsNil(o.Spec) {
		var ret CanvasesCanvasSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCanvasVersion) GetSpecOk() (*CanvasesCanvasSpec, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *CanvasesCanvasVersion) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given CanvasesCanvasSpec and assigns it to the Spec field.
func (o *CanvasesCanvasVersion) SetSpec(v CanvasesCanvasSpec) {
	o.Spec = &v
}

func (o CanvasesCanvasVersion) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CanvasesCanvasVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return toSerialize, nil
}

type NullableCanvasesCanvasVersion struct {
	value *CanvasesCanvasVersion
	isSet bool
}

func (v NullableCanvasesCanvasVersion) Get() *CanvasesCanvasVersion {
	return v.value
}

func (v *NullableCanvasesCanvasVersion) Set(val *CanvasesCanvasVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableCanvasesCanvasVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableCanvasesCanvasVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCanvasesCanvasVersion(val *CanvasesCanvasVersion) *NullableCanvasesCanvasVersion {
	return &NullableCanvasesCanvasVersion{value: val, isSet: true}
}

func (v NullableCanvasesCanvasVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCanvasesCanvasVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
