/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the SuperplaneUpdateBlueprintResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuperplaneUpdateBlueprintResponse{}

// SuperplaneUpdateBlueprintResponse struct for SuperplaneUpdateBlueprintResponse
type SuperplaneUpdateBlueprintResponse struct {
	Blueprint *SuperplaneBlueprint `json:"blueprint,omitempty"`
}

// NewSuperplaneUpdateBlueprintResponse instantiates a new SuperplaneUpdateBlueprintResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuperplaneUpdateBlueprintResponse() *SuperplaneUpdateBlueprintResponse {
	this := SuperplaneUpdateBlueprintResponse{}
	return &this
}

// NewSuperplaneUpdateBlueprintResponseWithDefaults instantiates a new SuperplaneUpdateBlueprintResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuperplaneUpdateBlueprintResponseWithDefaults() *SuperplaneUpdateBlueprintResponse {
	this := SuperplaneUpdateBlueprintResponse{}
	return &this
}

// GetBlueprint returns the Blueprint field value if set, zero value otherwise.
func (o *SuperplaneUpdateBlueprintResponse) GetBlueprint() SuperplaneBlueprint {
	if o == nil || IsNil(o.Blueprint) {
		var ret SuperplaneBlueprint
		return ret
	}
	return *o.Blueprint
}

// GetBlueprintOk returns a tuple with the Blueprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneUpdateBlueprintResponse) GetBlueprintOk() (*SuperplaneBlueprint, bool) {
	if o == nil || IsNil(o.Blueprint) {
		return nil, false
	}
	return o.Blueprint, true
}

// HasBlueprint returns a boolean if a field has been set.
func (o *SuperplaneUpdateBlueprintResponse) HasBlueprint() bool {
	if o != nil && !IsNil(o.Blueprint) {
		return true
	}

	return false
}

// SetBlueprint gets a reference to the given SuperplaneBlueprint and assigns it to the Blueprint field.
func (o *SuperplaneUpdateBlueprintResponse) SetBlueprint(v SuperplaneBlueprint) {
	o.Blueprint = &v
}

func (o SuperplaneUpdateBlueprintResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuperplaneUpdateBlueprintResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Blueprint) {
		toSerialize["blueprint"] = o.Blueprint
	}
	return toSerialize, nil
}

type NullableSuperplaneUpdateBlueprintResponse struct {
	value *SuperplaneUpdateBlueprintResponse
	isSet bool
}

func (v NullableSuperplaneUpdateBlueprintResponse) Get() *SuperplaneUpdateBlueprintResponse {
	return v.value
}

func (v *NullableSuperplaneUpdateBlueprintResponse) Set(val *SuperplaneUpdateBlueprintResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSuperplaneUpdateBlueprintResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSuperplaneUpdateBlueprintResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuperplaneUpdateBlueprintResponse(val *SuperplaneUpdateBlueprintResponse) *NullableSuperplaneUpdateBlueprintResponse {
	return &NullableSuperplaneUpdateBlueprintResponse{value: val, isSet: true}
}

func (v NullableSuperplaneUpdateBlueprintResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuperplaneUpdateBlueprintResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


