/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the ConfigurationStringTypeOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigurationStringTypeOptions{}

// ConfigurationStringTypeOptions struct for ConfigurationStringTypeOptions
type ConfigurationStringTypeOptions struct {
	MinLength *int32 `json:"minLength,omitempty"`
	MaxLength *int32 `json:"maxLength,omitempty"`
}

// NewConfigurationStringTypeOptions instantiates a new ConfigurationStringTypeOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationStringTypeOptions() *ConfigurationStringTypeOptions {
	this := ConfigurationStringTypeOptions{}
	return &this
}

// NewConfigurationStringTypeOptionsWithDefaults instantiates a new ConfigurationStringTypeOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationStringTypeOptionsWithDefaults() *ConfigurationStringTypeOptions {
	this := ConfigurationStringTypeOptions{}
	return &this
}

// GetMinLength returns the MinLength field value if set, zero value otherwise.
func (o *ConfigurationStringTypeOptions) GetMinLength() int32 {
	if o == nil || IsNil(o.MinLength) {
		var ret int32
		return ret
	}
	return *o.MinLength
}

// GetMinLengthOk returns a tuple with the MinLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationStringTypeOptions) GetMinLengthOk() (*int32, bool) {
	if o == nil || IsNil(o.MinLength) {
		return nil, false
	}
	return o.MinLength, true
}

// HasMinLength returns a boolean if a field has been set.
func (o *ConfigurationStringTypeOptions) HasMinLength() bool {
	if o != nil && !IsNil(o.MinLength) {
		return true
	}

	return false
}

// SetMinLength gets a reference to the given int32 and assigns it to the MinLength field.
func (o *ConfigurationStringTypeOptions) SetMinLength(v int32) {
	o.MinLength = &v
}

// GetMaxLength returns the MaxLength field value if set, zero value otherwise.
func (o *ConfigurationStringTypeOptions) GetMaxLength() int32 {
	if o == nil || IsNil(o.MaxLength) {
		var ret int32
		return ret
	}
	return *o.MaxLength
}

// GetMaxLengthOk returns a tuple with the MaxLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigurationStringTypeOptions) GetMaxLengthOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxLength) {
		return nil, false
	}
	return o.MaxLength, true
}

// HasMaxLength returns a boolean if a field has been set.
func (o *ConfigurationStringTypeOptions) HasMaxLength() bool {
	if o != nil && !IsNil(o.MaxLength) {
		return true
	}

	return false
}

// SetMaxLength gets a reference to the given int32 and assigns it to the MaxLength field.
func (o *ConfigurationStringTypeOptions) SetMaxLength(v int32) {
	o.MaxLength = &v
}

func (o ConfigurationStringTypeOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigurationStringTypeOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MinLength) {
		toSerialize["minLength"] = o.MinLength
	}
	if !IsNil(o.MaxLength) {
		toSerialize["maxLength"] = o.MaxLength
	}
	return toSerialize, nil
}

type NullableConfigurationStringTypeOptions struct {
	value *ConfigurationStringTypeOptions
	isSet bool
}

func (v NullableConfigurationStringTypeOptions) Get() *ConfigurationStringTypeOptions {
	return v.value
}

func (v *NullableConfigurationStringTypeOptions) Set(val *ConfigurationStringTypeOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationStringTypeOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationStringTypeOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationStringTypeOptions(val *ConfigurationStringTypeOptions) *NullableConfigurationStringTypeOptions {
	return &NullableConfigurationStringTypeOptions{value: val, isSet: true}
}

func (v NullableConfigurationStringTypeOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationStringTypeOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
