/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the AccountOrganization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountOrganization{}

// AccountOrganization struct for AccountOrganization
type AccountOrganization struct {
	// Organization ID
	Id *string `json:"id,omitempty"`
	// Organization name
	Name *string `json:"name,omitempty"`
	// Organization description
	Description *string `json:"description,omitempty"`
	// Number of canvases in the organization
	CanvasCount *int64 `json:"canvasCount,omitempty"`
	// Number of members in the organization
	MemberCount *int64 `json:"memberCount,omitempty"`
}

// NewAccountOrganization instantiates a new AccountOrganization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountOrganization() *AccountOrganization {
	this := AccountOrganization{}
	return &this
}

// NewAccountOrganizationWithDefaults instantiates a new AccountOrganization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountOrganizationWithDefaults() *AccountOrganization {
	this := AccountOrganization{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AccountOrganization) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountOrganization) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AccountOrganization) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AccountOrganization) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AccountOrganization) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountOrganization) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AccountOrganization) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AccountOrganization) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AccountOrganization) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountOrganization) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AccountOrganization) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AccountOrganization) SetDescription(v string) {
	o.Description = &v
}

// GetCanvasCount returns the CanvasCount field value if set, zero value otherwise.
func (o *AccountOrganization) GetCanvasCount() int64 {
	if o == nil || IsNil(o.CanvasCount) {
		var ret int64
		return ret
	}
	return *o.CanvasCount
}

// GetCanvasCountOk returns a tuple with the CanvasCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountOrganization) GetCanvasCountOk() (*int64, bool) {
	if o == nil || IsNil(o.CanvasCount) {
		return nil, false
	}
	return o.CanvasCount, true
}

// HasCanvasCount returns a boolean if a field has been set.
func (o *AccountOrganization) HasCanvasCount() bool {
	if o != nil && !IsNil(o.CanvasCount) {
		return true
	}

	return false
}

// SetCanvasCount gets a reference to the given int64 and assigns it to the CanvasCount field.
func (o *AccountOrganization) SetCanvasCount(v int64) {
	o.CanvasCount = &v
}

// GetMemberCount returns the MemberCount field value if set, zero value otherwise.
func (o *AccountOrganization) GetMemberCount() int64 {
	if o == nil || IsNil(o.MemberCount) {
		var ret int64
		return ret
	}
	return *o.MemberCount
}

// GetMemberCountOk returns a tuple with the MemberCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountOrganization) GetMemberCountOk() (*int64, bool) {
	if o == nil || IsNil(o.MemberCount) {
		return nil, false
	}
	return o.MemberCount, true
}

// HasMemberCount returns a boolean if a field has been set.
func (o *AccountOrganization) HasMemberCount() bool {
	if o != nil && !IsNil(o.MemberCount) {
		return true
	}

	return false
}

// SetMemberCount gets a reference to the given int64 and assigns it to the MemberCount field.
func (o *AccountOrganization) SetMemberCount(v int64) {
	o.MemberCount = &v
}

func (o AccountOrganization) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountOrganization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.CanvasCount) {
		toSerialize["canvasCount"] = o.CanvasCount
	}
	if !IsNil(o.MemberCount) {
		toSerialize["memberCount"] = o.MemberCount
	}
	return toSerialize, nil
}

type NullableAccountOrganization struct {
	value *AccountOrganization
	isSet bool
}

func (v NullableAccountOrganization) Get() *AccountOrganization {
	return v.value
}

func (v *NullableAccountOrganization) Set(val *AccountOrganization) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountOrganization) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountOrganization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountOrganization(val *AccountOrganization) *NullableAccountOrganization {
	return &NullableAccountOrganization{value: val, isSet: true}
}

func (v NullableAccountOrganization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountOrganization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


