/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the CanvasesCanvasUpdateOperationNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CanvasesCanvasUpdateOperationNode{}

// CanvasesCanvasUpdateOperationNode struct for CanvasesCanvasUpdateOperationNode
type CanvasesCanvasUpdateOperationNode struct {
	Id            *string                `json:"id,omitempty"`
	Name          *string                `json:"name,omitempty"`
	Block         *string                `json:"block,omitempty"`
	Configuration map[string]interface{} `json:"configuration,omitempty"`
	Channel       *string                `json:"channel,omitempty"`
}

// NewCanvasesCanvasUpdateOperationNode instantiates a new CanvasesCanvasUpdateOperationNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCanvasesCanvasUpdateOperationNode() *CanvasesCanvasUpdateOperationNode {
	this := CanvasesCanvasUpdateOperationNode{}
	return &this
}

// NewCanvasesCanvasUpdateOperationNodeWithDefaults instantiates a new CanvasesCanvasUpdateOperationNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCanvasesCanvasUpdateOperationNodeWithDefaults() *CanvasesCanvasUpdateOperationNode {
	this := CanvasesCanvasUpdateOperationNode{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CanvasesCanvasUpdateOperationNode) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCanvasUpdateOperationNode) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CanvasesCanvasUpdateOperationNode) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CanvasesCanvasUpdateOperationNode) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CanvasesCanvasUpdateOperationNode) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCanvasUpdateOperationNode) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CanvasesCanvasUpdateOperationNode) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CanvasesCanvasUpdateOperationNode) SetName(v string) {
	o.Name = &v
}

// GetBlock returns the Block field value if set, zero value otherwise.
func (o *CanvasesCanvasUpdateOperationNode) GetBlock() string {
	if o == nil || IsNil(o.Block) {
		var ret string
		return ret
	}
	return *o.Block
}

// GetBlockOk returns a tuple with the Block field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCanvasUpdateOperationNode) GetBlockOk() (*string, bool) {
	if o == nil || IsNil(o.Block) {
		return nil, false
	}
	return o.Block, true
}

// HasBlock returns a boolean if a field has been set.
func (o *CanvasesCanvasUpdateOperationNode) HasBlock() bool {
	if o != nil && !IsNil(o.Block) {
		return true
	}

	return false
}

// SetBlock gets a reference to the given string and assigns it to the Block field.
func (o *CanvasesCanvasUpdateOperationNode) SetBlock(v string) {
	o.Block = &v
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *CanvasesCanvasUpdateOperationNode) GetConfiguration() map[string]interface{} {
	if o == nil || IsNil(o.Configuration) {
		var ret map[string]interface{}
		return ret
	}
	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCanvasUpdateOperationNode) GetConfigurationOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Configuration) {
		return map[string]interface{}{}, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *CanvasesCanvasUpdateOperationNode) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given map[string]interface{} and assigns it to the Configuration field.
func (o *CanvasesCanvasUpdateOperationNode) SetConfiguration(v map[string]interface{}) {
	o.Configuration = v
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *CanvasesCanvasUpdateOperationNode) GetChannel() string {
	if o == nil || IsNil(o.Channel) {
		var ret string
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCanvasUpdateOperationNode) GetChannelOk() (*string, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *CanvasesCanvasUpdateOperationNode) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given string and assigns it to the Channel field.
func (o *CanvasesCanvasUpdateOperationNode) SetChannel(v string) {
	o.Channel = &v
}

func (o CanvasesCanvasUpdateOperationNode) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CanvasesCanvasUpdateOperationNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Block) {
		toSerialize["block"] = o.Block
	}
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	return toSerialize, nil
}

type NullableCanvasesCanvasUpdateOperationNode struct {
	value *CanvasesCanvasUpdateOperationNode
	isSet bool
}

func (v NullableCanvasesCanvasUpdateOperationNode) Get() *CanvasesCanvasUpdateOperationNode {
	return v.value
}

func (v *NullableCanvasesCanvasUpdateOperationNode) Set(val *CanvasesCanvasUpdateOperationNode) {
	v.value = val
	v.isSet = true
}

func (v NullableCanvasesCanvasUpdateOperationNode) IsSet() bool {
	return v.isSet
}

func (v *NullableCanvasesCanvasUpdateOperationNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCanvasesCanvasUpdateOperationNode(val *CanvasesCanvasUpdateOperationNode) *NullableCanvasesCanvasUpdateOperationNode {
	return &NullableCanvasesCanvasUpdateOperationNode{value: val, isSet: true}
}

func (v NullableCanvasesCanvasUpdateOperationNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCanvasesCanvasUpdateOperationNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
