/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the OrganizationsUpdateAgentSettingsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsUpdateAgentSettingsResponse{}

// OrganizationsUpdateAgentSettingsResponse struct for OrganizationsUpdateAgentSettingsResponse
type OrganizationsUpdateAgentSettingsResponse struct {
	AgentSettings *OrganizationsAgentSettings `json:"agentSettings,omitempty"`
}

// NewOrganizationsUpdateAgentSettingsResponse instantiates a new OrganizationsUpdateAgentSettingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsUpdateAgentSettingsResponse() *OrganizationsUpdateAgentSettingsResponse {
	this := OrganizationsUpdateAgentSettingsResponse{}
	return &this
}

// NewOrganizationsUpdateAgentSettingsResponseWithDefaults instantiates a new OrganizationsUpdateAgentSettingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsUpdateAgentSettingsResponseWithDefaults() *OrganizationsUpdateAgentSettingsResponse {
	this := OrganizationsUpdateAgentSettingsResponse{}
	return &this
}

// GetAgentSettings returns the AgentSettings field value if set, zero value otherwise.
func (o *OrganizationsUpdateAgentSettingsResponse) GetAgentSettings() OrganizationsAgentSettings {
	if o == nil || IsNil(o.AgentSettings) {
		var ret OrganizationsAgentSettings
		return ret
	}
	return *o.AgentSettings
}

// GetAgentSettingsOk returns a tuple with the AgentSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsUpdateAgentSettingsResponse) GetAgentSettingsOk() (*OrganizationsAgentSettings, bool) {
	if o == nil || IsNil(o.AgentSettings) {
		return nil, false
	}
	return o.AgentSettings, true
}

// HasAgentSettings returns a boolean if a field has been set.
func (o *OrganizationsUpdateAgentSettingsResponse) HasAgentSettings() bool {
	if o != nil && !IsNil(o.AgentSettings) {
		return true
	}

	return false
}

// SetAgentSettings gets a reference to the given OrganizationsAgentSettings and assigns it to the AgentSettings field.
func (o *OrganizationsUpdateAgentSettingsResponse) SetAgentSettings(v OrganizationsAgentSettings) {
	o.AgentSettings = &v
}

func (o OrganizationsUpdateAgentSettingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsUpdateAgentSettingsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AgentSettings) {
		toSerialize["agentSettings"] = o.AgentSettings
	}
	return toSerialize, nil
}

type NullableOrganizationsUpdateAgentSettingsResponse struct {
	value *OrganizationsUpdateAgentSettingsResponse
	isSet bool
}

func (v NullableOrganizationsUpdateAgentSettingsResponse) Get() *OrganizationsUpdateAgentSettingsResponse {
	return v.value
}

func (v *NullableOrganizationsUpdateAgentSettingsResponse) Set(val *OrganizationsUpdateAgentSettingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsUpdateAgentSettingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsUpdateAgentSettingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsUpdateAgentSettingsResponse(val *OrganizationsUpdateAgentSettingsResponse) *NullableOrganizationsUpdateAgentSettingsResponse {
	return &NullableOrganizationsUpdateAgentSettingsResponse{value: val, isSet: true}
}

func (v NullableOrganizationsUpdateAgentSettingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsUpdateAgentSettingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
