/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the CanvasesCanvasChangeRequestDiff type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CanvasesCanvasChangeRequestDiff{}

// CanvasesCanvasChangeRequestDiff struct for CanvasesCanvasChangeRequestDiff
type CanvasesCanvasChangeRequestDiff struct {
	ChangedNodeIds []string `json:"changedNodeIds,omitempty"`
}

// NewCanvasesCanvasChangeRequestDiff instantiates a new CanvasesCanvasChangeRequestDiff object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCanvasesCanvasChangeRequestDiff() *CanvasesCanvasChangeRequestDiff {
	this := CanvasesCanvasChangeRequestDiff{}
	return &this
}

// NewCanvasesCanvasChangeRequestDiffWithDefaults instantiates a new CanvasesCanvasChangeRequestDiff object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCanvasesCanvasChangeRequestDiffWithDefaults() *CanvasesCanvasChangeRequestDiff {
	this := CanvasesCanvasChangeRequestDiff{}
	return &this
}

// GetChangedNodeIds returns the ChangedNodeIds field value if set, zero value otherwise.
func (o *CanvasesCanvasChangeRequestDiff) GetChangedNodeIds() []string {
	if o == nil || IsNil(o.ChangedNodeIds) {
		var ret []string
		return ret
	}
	return o.ChangedNodeIds
}

// GetChangedNodeIdsOk returns a tuple with the ChangedNodeIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCanvasChangeRequestDiff) GetChangedNodeIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ChangedNodeIds) {
		return nil, false
	}
	return o.ChangedNodeIds, true
}

// HasChangedNodeIds returns a boolean if a field has been set.
func (o *CanvasesCanvasChangeRequestDiff) HasChangedNodeIds() bool {
	if o != nil && !IsNil(o.ChangedNodeIds) {
		return true
	}

	return false
}

// SetChangedNodeIds gets a reference to the given []string and assigns it to the ChangedNodeIds field.
func (o *CanvasesCanvasChangeRequestDiff) SetChangedNodeIds(v []string) {
	o.ChangedNodeIds = v
}

func (o CanvasesCanvasChangeRequestDiff) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CanvasesCanvasChangeRequestDiff) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChangedNodeIds) {
		toSerialize["changedNodeIds"] = o.ChangedNodeIds
	}
	return toSerialize, nil
}

type NullableCanvasesCanvasChangeRequestDiff struct {
	value *CanvasesCanvasChangeRequestDiff
	isSet bool
}

func (v NullableCanvasesCanvasChangeRequestDiff) Get() *CanvasesCanvasChangeRequestDiff {
	return v.value
}

func (v *NullableCanvasesCanvasChangeRequestDiff) Set(val *CanvasesCanvasChangeRequestDiff) {
	v.value = val
	v.isSet = true
}

func (v NullableCanvasesCanvasChangeRequestDiff) IsSet() bool {
	return v.isSet
}

func (v *NullableCanvasesCanvasChangeRequestDiff) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCanvasesCanvasChangeRequestDiff(val *CanvasesCanvasChangeRequestDiff) *NullableCanvasesCanvasChangeRequestDiff {
	return &NullableCanvasesCanvasChangeRequestDiff{value: val, isSet: true}
}

func (v NullableCanvasesCanvasChangeRequestDiff) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCanvasesCanvasChangeRequestDiff) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
