/*
Superplane API

API for the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the SuperplaneTag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuperplaneTag{}

// SuperplaneTag struct for SuperplaneTag
type SuperplaneTag struct {
	Name *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
	State *SuperplaneTagState `json:"state,omitempty"`
}

// NewSuperplaneTag instantiates a new SuperplaneTag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuperplaneTag() *SuperplaneTag {
	this := SuperplaneTag{}
	var state SuperplaneTagState = SUPERPLANETAGSTATE_TAG_STATE_UNKNOWN
	this.State = &state
	return &this
}

// NewSuperplaneTagWithDefaults instantiates a new SuperplaneTag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuperplaneTagWithDefaults() *SuperplaneTag {
	this := SuperplaneTag{}
	var state SuperplaneTagState = SUPERPLANETAGSTATE_TAG_STATE_UNKNOWN
	this.State = &state
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SuperplaneTag) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneTag) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SuperplaneTag) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SuperplaneTag) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SuperplaneTag) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneTag) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SuperplaneTag) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *SuperplaneTag) SetValue(v string) {
	o.Value = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *SuperplaneTag) GetState() SuperplaneTagState {
	if o == nil || IsNil(o.State) {
		var ret SuperplaneTagState
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuperplaneTag) GetStateOk() (*SuperplaneTagState, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *SuperplaneTag) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given SuperplaneTagState and assigns it to the State field.
func (o *SuperplaneTag) SetState(v SuperplaneTagState) {
	o.State = &v
}

func (o SuperplaneTag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuperplaneTag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableSuperplaneTag struct {
	value *SuperplaneTag
	isSet bool
}

func (v NullableSuperplaneTag) Get() *SuperplaneTag {
	return v.value
}

func (v *NullableSuperplaneTag) Set(val *SuperplaneTag) {
	v.value = val
	v.isSet = true
}

func (v NullableSuperplaneTag) IsSet() bool {
	return v.isSet
}

func (v *NullableSuperplaneTag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuperplaneTag(val *SuperplaneTag) *NullableSuperplaneTag {
	return &NullableSuperplaneTag{value: val, isSet: true}
}

func (v NullableSuperplaneTag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuperplaneTag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


