/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the BlueprintsCreateBlueprintRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlueprintsCreateBlueprintRequest{}

// BlueprintsCreateBlueprintRequest struct for BlueprintsCreateBlueprintRequest
type BlueprintsCreateBlueprintRequest struct {
	Blueprint *BlueprintsBlueprint `json:"blueprint,omitempty"`
}

// NewBlueprintsCreateBlueprintRequest instantiates a new BlueprintsCreateBlueprintRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlueprintsCreateBlueprintRequest() *BlueprintsCreateBlueprintRequest {
	this := BlueprintsCreateBlueprintRequest{}
	return &this
}

// NewBlueprintsCreateBlueprintRequestWithDefaults instantiates a new BlueprintsCreateBlueprintRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlueprintsCreateBlueprintRequestWithDefaults() *BlueprintsCreateBlueprintRequest {
	this := BlueprintsCreateBlueprintRequest{}
	return &this
}

// GetBlueprint returns the Blueprint field value if set, zero value otherwise.
func (o *BlueprintsCreateBlueprintRequest) GetBlueprint() BlueprintsBlueprint {
	if o == nil || IsNil(o.Blueprint) {
		var ret BlueprintsBlueprint
		return ret
	}
	return *o.Blueprint
}

// GetBlueprintOk returns a tuple with the Blueprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintsCreateBlueprintRequest) GetBlueprintOk() (*BlueprintsBlueprint, bool) {
	if o == nil || IsNil(o.Blueprint) {
		return nil, false
	}
	return o.Blueprint, true
}

// HasBlueprint returns a boolean if a field has been set.
func (o *BlueprintsCreateBlueprintRequest) HasBlueprint() bool {
	if o != nil && !IsNil(o.Blueprint) {
		return true
	}

	return false
}

// SetBlueprint gets a reference to the given BlueprintsBlueprint and assigns it to the Blueprint field.
func (o *BlueprintsCreateBlueprintRequest) SetBlueprint(v BlueprintsBlueprint) {
	o.Blueprint = &v
}

func (o BlueprintsCreateBlueprintRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlueprintsCreateBlueprintRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Blueprint) {
		toSerialize["blueprint"] = o.Blueprint
	}
	return toSerialize, nil
}

type NullableBlueprintsCreateBlueprintRequest struct {
	value *BlueprintsCreateBlueprintRequest
	isSet bool
}

func (v NullableBlueprintsCreateBlueprintRequest) Get() *BlueprintsCreateBlueprintRequest {
	return v.value
}

func (v *NullableBlueprintsCreateBlueprintRequest) Set(val *BlueprintsCreateBlueprintRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprintsCreateBlueprintRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprintsCreateBlueprintRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprintsCreateBlueprintRequest(val *BlueprintsCreateBlueprintRequest) *NullableBlueprintsCreateBlueprintRequest {
	return &NullableBlueprintsCreateBlueprintRequest{value: val, isSet: true}
}

func (v NullableBlueprintsCreateBlueprintRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprintsCreateBlueprintRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
