/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the SecretsUpdateSecretNameResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretsUpdateSecretNameResponse{}

// SecretsUpdateSecretNameResponse struct for SecretsUpdateSecretNameResponse
type SecretsUpdateSecretNameResponse struct {
	Secret *SecretsSecret `json:"secret,omitempty"`
}

// NewSecretsUpdateSecretNameResponse instantiates a new SecretsUpdateSecretNameResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretsUpdateSecretNameResponse() *SecretsUpdateSecretNameResponse {
	this := SecretsUpdateSecretNameResponse{}
	return &this
}

// NewSecretsUpdateSecretNameResponseWithDefaults instantiates a new SecretsUpdateSecretNameResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretsUpdateSecretNameResponseWithDefaults() *SecretsUpdateSecretNameResponse {
	this := SecretsUpdateSecretNameResponse{}
	return &this
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *SecretsUpdateSecretNameResponse) GetSecret() SecretsSecret {
	if o == nil || IsNil(o.Secret) {
		var ret SecretsSecret
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretsUpdateSecretNameResponse) GetSecretOk() (*SecretsSecret, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *SecretsUpdateSecretNameResponse) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given SecretsSecret and assigns it to the Secret field.
func (o *SecretsUpdateSecretNameResponse) SetSecret(v SecretsSecret) {
	o.Secret = &v
}

func (o SecretsUpdateSecretNameResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretsUpdateSecretNameResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	return toSerialize, nil
}

type NullableSecretsUpdateSecretNameResponse struct {
	value *SecretsUpdateSecretNameResponse
	isSet bool
}

func (v NullableSecretsUpdateSecretNameResponse) Get() *SecretsUpdateSecretNameResponse {
	return v.value
}

func (v *NullableSecretsUpdateSecretNameResponse) Set(val *SecretsUpdateSecretNameResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretsUpdateSecretNameResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretsUpdateSecretNameResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretsUpdateSecretNameResponse(val *SecretsUpdateSecretNameResponse) *NullableSecretsUpdateSecretNameResponse {
	return &NullableSecretsUpdateSecretNameResponse{value: val, isSet: true}
}

func (v NullableSecretsUpdateSecretNameResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretsUpdateSecretNameResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


