/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the IntegrationNodeRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationNodeRef{}

// IntegrationNodeRef struct for IntegrationNodeRef
type IntegrationNodeRef struct {
	CanvasId   *string `json:"canvasId,omitempty"`
	CanvasName *string `json:"canvasName,omitempty"`
	NodeId     *string `json:"nodeId,omitempty"`
	NodeName   *string `json:"nodeName,omitempty"`
}

// NewIntegrationNodeRef instantiates a new IntegrationNodeRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationNodeRef() *IntegrationNodeRef {
	this := IntegrationNodeRef{}
	return &this
}

// NewIntegrationNodeRefWithDefaults instantiates a new IntegrationNodeRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationNodeRefWithDefaults() *IntegrationNodeRef {
	this := IntegrationNodeRef{}
	return &this
}

// GetCanvasId returns the CanvasId field value if set, zero value otherwise.
func (o *IntegrationNodeRef) GetCanvasId() string {
	if o == nil || IsNil(o.CanvasId) {
		var ret string
		return ret
	}
	return *o.CanvasId
}

// GetCanvasIdOk returns a tuple with the CanvasId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationNodeRef) GetCanvasIdOk() (*string, bool) {
	if o == nil || IsNil(o.CanvasId) {
		return nil, false
	}
	return o.CanvasId, true
}

// HasCanvasId returns a boolean if a field has been set.
func (o *IntegrationNodeRef) HasCanvasId() bool {
	if o != nil && !IsNil(o.CanvasId) {
		return true
	}

	return false
}

// SetCanvasId gets a reference to the given string and assigns it to the CanvasId field.
func (o *IntegrationNodeRef) SetCanvasId(v string) {
	o.CanvasId = &v
}

// GetCanvasName returns the CanvasName field value if set, zero value otherwise.
func (o *IntegrationNodeRef) GetCanvasName() string {
	if o == nil || IsNil(o.CanvasName) {
		var ret string
		return ret
	}
	return *o.CanvasName
}

// GetCanvasNameOk returns a tuple with the CanvasName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationNodeRef) GetCanvasNameOk() (*string, bool) {
	if o == nil || IsNil(o.CanvasName) {
		return nil, false
	}
	return o.CanvasName, true
}

// HasCanvasName returns a boolean if a field has been set.
func (o *IntegrationNodeRef) HasCanvasName() bool {
	if o != nil && !IsNil(o.CanvasName) {
		return true
	}

	return false
}

// SetCanvasName gets a reference to the given string and assigns it to the CanvasName field.
func (o *IntegrationNodeRef) SetCanvasName(v string) {
	o.CanvasName = &v
}

// GetNodeId returns the NodeId field value if set, zero value otherwise.
func (o *IntegrationNodeRef) GetNodeId() string {
	if o == nil || IsNil(o.NodeId) {
		var ret string
		return ret
	}
	return *o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationNodeRef) GetNodeIdOk() (*string, bool) {
	if o == nil || IsNil(o.NodeId) {
		return nil, false
	}
	return o.NodeId, true
}

// HasNodeId returns a boolean if a field has been set.
func (o *IntegrationNodeRef) HasNodeId() bool {
	if o != nil && !IsNil(o.NodeId) {
		return true
	}

	return false
}

// SetNodeId gets a reference to the given string and assigns it to the NodeId field.
func (o *IntegrationNodeRef) SetNodeId(v string) {
	o.NodeId = &v
}

// GetNodeName returns the NodeName field value if set, zero value otherwise.
func (o *IntegrationNodeRef) GetNodeName() string {
	if o == nil || IsNil(o.NodeName) {
		var ret string
		return ret
	}
	return *o.NodeName
}

// GetNodeNameOk returns a tuple with the NodeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationNodeRef) GetNodeNameOk() (*string, bool) {
	if o == nil || IsNil(o.NodeName) {
		return nil, false
	}
	return o.NodeName, true
}

// HasNodeName returns a boolean if a field has been set.
func (o *IntegrationNodeRef) HasNodeName() bool {
	if o != nil && !IsNil(o.NodeName) {
		return true
	}

	return false
}

// SetNodeName gets a reference to the given string and assigns it to the NodeName field.
func (o *IntegrationNodeRef) SetNodeName(v string) {
	o.NodeName = &v
}

func (o IntegrationNodeRef) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationNodeRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CanvasId) {
		toSerialize["canvasId"] = o.CanvasId
	}
	if !IsNil(o.CanvasName) {
		toSerialize["canvasName"] = o.CanvasName
	}
	if !IsNil(o.NodeId) {
		toSerialize["nodeId"] = o.NodeId
	}
	if !IsNil(o.NodeName) {
		toSerialize["nodeName"] = o.NodeName
	}
	return toSerialize, nil
}

type NullableIntegrationNodeRef struct {
	value *IntegrationNodeRef
	isSet bool
}

func (v NullableIntegrationNodeRef) Get() *IntegrationNodeRef {
	return v.value
}

func (v *NullableIntegrationNodeRef) Set(val *IntegrationNodeRef) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationNodeRef) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationNodeRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationNodeRef(val *IntegrationNodeRef) *NullableIntegrationNodeRef {
	return &NullableIntegrationNodeRef{value: val, isSet: true}
}

func (v NullableIntegrationNodeRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationNodeRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
