/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the OrganizationsListApplicationResourcesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsListApplicationResourcesResponse{}

// OrganizationsListApplicationResourcesResponse struct for OrganizationsListApplicationResourcesResponse
type OrganizationsListApplicationResourcesResponse struct {
	Resources []OrganizationsAppInstallationResourceRef `json:"resources,omitempty"`
}

// NewOrganizationsListApplicationResourcesResponse instantiates a new OrganizationsListApplicationResourcesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsListApplicationResourcesResponse() *OrganizationsListApplicationResourcesResponse {
	this := OrganizationsListApplicationResourcesResponse{}
	return &this
}

// NewOrganizationsListApplicationResourcesResponseWithDefaults instantiates a new OrganizationsListApplicationResourcesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsListApplicationResourcesResponseWithDefaults() *OrganizationsListApplicationResourcesResponse {
	this := OrganizationsListApplicationResourcesResponse{}
	return &this
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *OrganizationsListApplicationResourcesResponse) GetResources() []OrganizationsAppInstallationResourceRef {
	if o == nil || IsNil(o.Resources) {
		var ret []OrganizationsAppInstallationResourceRef
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsListApplicationResourcesResponse) GetResourcesOk() ([]OrganizationsAppInstallationResourceRef, bool) {
	if o == nil || IsNil(o.Resources) {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *OrganizationsListApplicationResourcesResponse) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given []OrganizationsAppInstallationResourceRef and assigns it to the Resources field.
func (o *OrganizationsListApplicationResourcesResponse) SetResources(v []OrganizationsAppInstallationResourceRef) {
	o.Resources = v
}

func (o OrganizationsListApplicationResourcesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsListApplicationResourcesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	return toSerialize, nil
}

type NullableOrganizationsListApplicationResourcesResponse struct {
	value *OrganizationsListApplicationResourcesResponse
	isSet bool
}

func (v NullableOrganizationsListApplicationResourcesResponse) Get() *OrganizationsListApplicationResourcesResponse {
	return v.value
}

func (v *NullableOrganizationsListApplicationResourcesResponse) Set(val *OrganizationsListApplicationResourcesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsListApplicationResourcesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsListApplicationResourcesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsListApplicationResourcesResponse(val *OrganizationsListApplicationResourcesResponse) *NullableOrganizationsListApplicationResourcesResponse {
	return &NullableOrganizationsListApplicationResourcesResponse{value: val, isSet: true}
}

func (v NullableOrganizationsListApplicationResourcesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsListApplicationResourcesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


