/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the OrganizationsUpdateIntegrationBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationsUpdateIntegrationBody{}

// OrganizationsUpdateIntegrationBody struct for OrganizationsUpdateIntegrationBody
type OrganizationsUpdateIntegrationBody struct {
	Configuration map[string]interface{} `json:"configuration,omitempty"`
	Name          *string                `json:"name,omitempty"`
}

// NewOrganizationsUpdateIntegrationBody instantiates a new OrganizationsUpdateIntegrationBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationsUpdateIntegrationBody() *OrganizationsUpdateIntegrationBody {
	this := OrganizationsUpdateIntegrationBody{}
	return &this
}

// NewOrganizationsUpdateIntegrationBodyWithDefaults instantiates a new OrganizationsUpdateIntegrationBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationsUpdateIntegrationBodyWithDefaults() *OrganizationsUpdateIntegrationBody {
	this := OrganizationsUpdateIntegrationBody{}
	return &this
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *OrganizationsUpdateIntegrationBody) GetConfiguration() map[string]interface{} {
	if o == nil || IsNil(o.Configuration) {
		var ret map[string]interface{}
		return ret
	}
	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsUpdateIntegrationBody) GetConfigurationOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Configuration) {
		return map[string]interface{}{}, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *OrganizationsUpdateIntegrationBody) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given map[string]interface{} and assigns it to the Configuration field.
func (o *OrganizationsUpdateIntegrationBody) SetConfiguration(v map[string]interface{}) {
	o.Configuration = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OrganizationsUpdateIntegrationBody) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationsUpdateIntegrationBody) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OrganizationsUpdateIntegrationBody) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OrganizationsUpdateIntegrationBody) SetName(v string) {
	o.Name = &v
}

func (o OrganizationsUpdateIntegrationBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationsUpdateIntegrationBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableOrganizationsUpdateIntegrationBody struct {
	value *OrganizationsUpdateIntegrationBody
	isSet bool
}

func (v NullableOrganizationsUpdateIntegrationBody) Get() *OrganizationsUpdateIntegrationBody {
	return v.value
}

func (v *NullableOrganizationsUpdateIntegrationBody) Set(val *OrganizationsUpdateIntegrationBody) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationsUpdateIntegrationBody) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationsUpdateIntegrationBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationsUpdateIntegrationBody(val *OrganizationsUpdateIntegrationBody) *NullableOrganizationsUpdateIntegrationBody {
	return &NullableOrganizationsUpdateIntegrationBody{value: val, isSet: true}
}

func (v NullableOrganizationsUpdateIntegrationBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationsUpdateIntegrationBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
