/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
	"time"
)

// checks if the CanvasesListNodeQueueItemsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CanvasesListNodeQueueItemsResponse{}

// CanvasesListNodeQueueItemsResponse struct for CanvasesListNodeQueueItemsResponse
type CanvasesListNodeQueueItemsResponse struct {
	Items []CanvasesCanvasNodeQueueItem `json:"items,omitempty"`
	TotalCount *int64 `json:"totalCount,omitempty"`
	HasNextPage *bool `json:"hasNextPage,omitempty"`
	LastTimestamp *time.Time `json:"lastTimestamp,omitempty"`
}

// NewCanvasesListNodeQueueItemsResponse instantiates a new CanvasesListNodeQueueItemsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCanvasesListNodeQueueItemsResponse() *CanvasesListNodeQueueItemsResponse {
	this := CanvasesListNodeQueueItemsResponse{}
	return &this
}

// NewCanvasesListNodeQueueItemsResponseWithDefaults instantiates a new CanvasesListNodeQueueItemsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCanvasesListNodeQueueItemsResponseWithDefaults() *CanvasesListNodeQueueItemsResponse {
	this := CanvasesListNodeQueueItemsResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CanvasesListNodeQueueItemsResponse) GetItems() []CanvasesCanvasNodeQueueItem {
	if o == nil || IsNil(o.Items) {
		var ret []CanvasesCanvasNodeQueueItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesListNodeQueueItemsResponse) GetItemsOk() ([]CanvasesCanvasNodeQueueItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CanvasesListNodeQueueItemsResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []CanvasesCanvasNodeQueueItem and assigns it to the Items field.
func (o *CanvasesListNodeQueueItemsResponse) SetItems(v []CanvasesCanvasNodeQueueItem) {
	o.Items = v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *CanvasesListNodeQueueItemsResponse) GetTotalCount() int64 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int64
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesListNodeQueueItemsResponse) GetTotalCountOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *CanvasesListNodeQueueItemsResponse) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int64 and assigns it to the TotalCount field.
func (o *CanvasesListNodeQueueItemsResponse) SetTotalCount(v int64) {
	o.TotalCount = &v
}

// GetHasNextPage returns the HasNextPage field value if set, zero value otherwise.
func (o *CanvasesListNodeQueueItemsResponse) GetHasNextPage() bool {
	if o == nil || IsNil(o.HasNextPage) {
		var ret bool
		return ret
	}
	return *o.HasNextPage
}

// GetHasNextPageOk returns a tuple with the HasNextPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesListNodeQueueItemsResponse) GetHasNextPageOk() (*bool, bool) {
	if o == nil || IsNil(o.HasNextPage) {
		return nil, false
	}
	return o.HasNextPage, true
}

// HasHasNextPage returns a boolean if a field has been set.
func (o *CanvasesListNodeQueueItemsResponse) HasHasNextPage() bool {
	if o != nil && !IsNil(o.HasNextPage) {
		return true
	}

	return false
}

// SetHasNextPage gets a reference to the given bool and assigns it to the HasNextPage field.
func (o *CanvasesListNodeQueueItemsResponse) SetHasNextPage(v bool) {
	o.HasNextPage = &v
}

// GetLastTimestamp returns the LastTimestamp field value if set, zero value otherwise.
func (o *CanvasesListNodeQueueItemsResponse) GetLastTimestamp() time.Time {
	if o == nil || IsNil(o.LastTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.LastTimestamp
}

// GetLastTimestampOk returns a tuple with the LastTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesListNodeQueueItemsResponse) GetLastTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastTimestamp) {
		return nil, false
	}
	return o.LastTimestamp, true
}

// HasLastTimestamp returns a boolean if a field has been set.
func (o *CanvasesListNodeQueueItemsResponse) HasLastTimestamp() bool {
	if o != nil && !IsNil(o.LastTimestamp) {
		return true
	}

	return false
}

// SetLastTimestamp gets a reference to the given time.Time and assigns it to the LastTimestamp field.
func (o *CanvasesListNodeQueueItemsResponse) SetLastTimestamp(v time.Time) {
	o.LastTimestamp = &v
}

func (o CanvasesListNodeQueueItemsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CanvasesListNodeQueueItemsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.TotalCount) {
		toSerialize["totalCount"] = o.TotalCount
	}
	if !IsNil(o.HasNextPage) {
		toSerialize["hasNextPage"] = o.HasNextPage
	}
	if !IsNil(o.LastTimestamp) {
		toSerialize["lastTimestamp"] = o.LastTimestamp
	}
	return toSerialize, nil
}

type NullableCanvasesListNodeQueueItemsResponse struct {
	value *CanvasesListNodeQueueItemsResponse
	isSet bool
}

func (v NullableCanvasesListNodeQueueItemsResponse) Get() *CanvasesListNodeQueueItemsResponse {
	return v.value
}

func (v *NullableCanvasesListNodeQueueItemsResponse) Set(val *CanvasesListNodeQueueItemsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCanvasesListNodeQueueItemsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCanvasesListNodeQueueItemsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCanvasesListNodeQueueItemsResponse(val *CanvasesListNodeQueueItemsResponse) *NullableCanvasesListNodeQueueItemsResponse {
	return &NullableCanvasesListNodeQueueItemsResponse{value: val, isSet: true}
}

func (v NullableCanvasesListNodeQueueItemsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCanvasesListNodeQueueItemsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


