/*
Superplane Organizations API

API for managing organizations in the Superplane service

API version: 1.0
Contact: support@superplane.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
)

// checks if the CanvasesCanvasChangeRequestApprovalConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CanvasesCanvasChangeRequestApprovalConfig{}

// CanvasesCanvasChangeRequestApprovalConfig struct for CanvasesCanvasChangeRequestApprovalConfig
type CanvasesCanvasChangeRequestApprovalConfig struct {
	Items []CanvasesCanvasChangeRequestApprover `json:"items,omitempty"`
}

// NewCanvasesCanvasChangeRequestApprovalConfig instantiates a new CanvasesCanvasChangeRequestApprovalConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCanvasesCanvasChangeRequestApprovalConfig() *CanvasesCanvasChangeRequestApprovalConfig {
	this := CanvasesCanvasChangeRequestApprovalConfig{}
	return &this
}

// NewCanvasesCanvasChangeRequestApprovalConfigWithDefaults instantiates a new CanvasesCanvasChangeRequestApprovalConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCanvasesCanvasChangeRequestApprovalConfigWithDefaults() *CanvasesCanvasChangeRequestApprovalConfig {
	this := CanvasesCanvasChangeRequestApprovalConfig{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CanvasesCanvasChangeRequestApprovalConfig) GetItems() []CanvasesCanvasChangeRequestApprover {
	if o == nil || IsNil(o.Items) {
		var ret []CanvasesCanvasChangeRequestApprover
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CanvasesCanvasChangeRequestApprovalConfig) GetItemsOk() ([]CanvasesCanvasChangeRequestApprover, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CanvasesCanvasChangeRequestApprovalConfig) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []CanvasesCanvasChangeRequestApprover and assigns it to the Items field.
func (o *CanvasesCanvasChangeRequestApprovalConfig) SetItems(v []CanvasesCanvasChangeRequestApprover) {
	o.Items = v
}

func (o CanvasesCanvasChangeRequestApprovalConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CanvasesCanvasChangeRequestApprovalConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableCanvasesCanvasChangeRequestApprovalConfig struct {
	value *CanvasesCanvasChangeRequestApprovalConfig
	isSet bool
}

func (v NullableCanvasesCanvasChangeRequestApprovalConfig) Get() *CanvasesCanvasChangeRequestApprovalConfig {
	return v.value
}

func (v *NullableCanvasesCanvasChangeRequestApprovalConfig) Set(val *CanvasesCanvasChangeRequestApprovalConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableCanvasesCanvasChangeRequestApprovalConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableCanvasesCanvasChangeRequestApprovalConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCanvasesCanvasChangeRequestApprovalConfig(val *CanvasesCanvasChangeRequestApprovalConfig) *NullableCanvasesCanvasChangeRequestApprovalConfig {
	return &NullableCanvasesCanvasChangeRequestApprovalConfig{value: val, isSet: true}
}

func (v NullableCanvasesCanvasChangeRequestApprovalConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCanvasesCanvasChangeRequestApprovalConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
