import { BuildingBlockCategory } from "../../BuildingBlocksSidebar";

export const mockBuildingBlockCategories: BuildingBlockCategory[] = [
  {
    name: "Primitives",
    blocks: [
      // Primitives
      {
        name: "if",
        label: "If",
        description: "Branch execution based on a condition",
        type: "component",
        outputChannels: [
          { id: "then", label: "Then" } as any,
          { id: "else", label: "Else" } as any,
        ],
        configuration: [
          {
            key: "expression",
            label: "Expression",
            type: "string",
            required: true,
          },
        ],
        icon: "braces",
        color: "gray",
      },
      {
        name: "switch",
        label: "Switch",
        description: "Multi-branch switch over a value",
        type: "component",
        outputChannels: [
          { id: "case-1", label: "Case 1" } as any,
          { id: "case-2", label: "Case 2" } as any,
          { id: "default", label: "Default" } as any,
        ],
        configuration: [
          { key: "value", label: "Value", type: "string", required: true },
          { key: "cases", label: "Cases", type: "json", required: false },
        ],
        icon: "git-branch",
        color: "gray",
      },
      {
        name: "filter",
        label: "Filter",
        description: "Filter a list using a predicate",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          {
            key: "predicate",
            label: "Predicate",
            type: "string",
            required: true,
          },
        ],
        icon: "filter",
        color: "gray",
      },
      {
        name: "approval",
        label: "Approval",
        description: "Pause until manual approval or rejection",
        type: "component",
        outputChannels: [
          { id: "approved", label: "Approved" } as any,
          { id: "rejected", label: "Rejected" } as any,
        ],
        configuration: [
          {
            key: "approvers",
            label: "Approvers",
            type: "string[]",
            required: true,
          },
          {
            key: "timeout",
            label: "Timeout (mins)",
            type: "number",
            required: false,
          },
        ],
        icon: "check-circle-2",
        color: "green",
      },
      {
        name: "wait",
        label: "Wait",
        description: "Delay for a period or until a time",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          {
            key: "duration",
            label: "Duration (s)",
            type: "number",
            required: false,
          },
          {
            key: "until",
            label: "Until (ISO8601)",
            type: "string",
            required: false,
          },
        ],
        icon: "hourglass",
        color: "yellow",
      },
      {
        name: "cron",
        label: "Cron",
        description: "Trigger on a cron schedule",
        type: "trigger",
        outputChannels: [{ id: "tick", label: "Tick" } as any],
        configuration: [
          {
            key: "expression",
            label: "Cron Expression",
            type: "string",
            required: true,
          },
          {
            key: "timezone",
            label: "Timezone",
            type: "string",
            required: false,
          },
        ],
        icon: "calendar-clock",
        color: "blue",
      },
      {
        name: "webhook",
        label: "Webhook",
        description: "Trigger on inbound HTTP webhook",
        type: "trigger",
        outputChannels: [{ id: "event", label: "Event" } as any],
        configuration: [
          { key: "path", label: "Path", type: "string", required: true },
          {
            key: "method",
            label: "Method",
            type: "enum",
            values: ["GET", "POST", "PUT", "PATCH"],
            required: true,
          },
          { key: "secret", label: "Secret", type: "string", required: false },
        ],
        icon: "webhook",
        color: "blue",
      },
      {
        name: "http-request",
        label: "HTTP Request",
        description: "Make an outbound HTTP request",
        type: "component",
        outputChannels: [
          { id: "success", label: "Success" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          { key: "url", label: "URL", type: "string", required: true },
          {
            key: "method",
            label: "Method",
            type: "enum",
            values: ["GET", "POST", "PUT", "PATCH", "DELETE"],
            required: true,
          },
          { key: "headers", label: "Headers", type: "json", required: false },
          { key: "body", label: "Body", type: "json", required: false },
        ],
        icon: "globe",
        color: "gray",
      },
      {
        name: "ai-agent",
        label: "AI Agent",
        description: "Run an AI task to analyze or generate ops data",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          { key: "model", label: "Model", type: "string", required: false },
          { key: "prompt", label: "Prompt", type: "text", required: true },
          { key: "inputs", label: "Inputs", type: "json", required: false },
        ],
        icon: "bot",
        color: "purple",
      },
    ],
  },
  {
    name: "GitHub",
    blocks: [
      // Triggers - GitHub
      {
        name: "github-push",
        label: "GitHub Push",
        description: "Trigger on pushes to a repository",
        type: "trigger",
        outputChannels: [{ id: "push", label: "Push" } as any],
        configuration: [
          { key: "repo", label: "Repository", type: "string", required: true },
          {
            key: "branches",
            label: "Branches",
            type: "string[]",
            required: false,
          },
          { key: "paths", label: "Paths", type: "string[]", required: false },
          {
            key: "secret",
            label: "Webhook Secret",
            type: "string",
            required: false,
          },
        ],
        icon: "github",
        color: "gray",
      },
      {
        name: "github-pull-request",
        label: "GitHub Pull Request",
        description: "Trigger on PR events (open, sync, close, merge)",
        type: "trigger",
        outputChannels: [
          { id: "opened", label: "Opened" } as any,
          { id: "synchronized", label: "Synchronized" } as any,
          { id: "closed", label: "Closed" } as any,
          { id: "merged", label: "Merged" } as any,
        ],
        configuration: [
          { key: "repo", label: "Repository", type: "string", required: true },
          {
            key: "targetBranches",
            label: "Target Branches",
            type: "string[]",
            required: false,
          },
          { key: "labels", label: "Labels", type: "string[]", required: false },
          {
            key: "secret",
            label: "Webhook Secret",
            type: "string",
            required: false,
          },
        ],
        icon: "github",
        color: "gray",
      },
      {
        name: "github-issue-comment",
        label: "GitHub Issue Comment",
        description: "Trigger on new comments on issues/PRs",
        type: "trigger",
        outputChannels: [{ id: "comment", label: "Comment" } as any],
        configuration: [
          { key: "repo", label: "Repository", type: "string", required: true },
          {
            key: "issueNumber",
            label: "Issue/PR Number",
            type: "number",
            required: false,
          },
          {
            key: "contains",
            label: "Comment Contains",
            type: "string",
            required: false,
          },
          {
            key: "secret",
            label: "Webhook Secret",
            type: "string",
            required: false,
          },
        ],
        icon: "github",
        color: "gray",
      },
      // Actions - GitHub
      {
        name: "github-actions",
        label: "GitHub Actions",
        description: "Dispatch or wait on GitHub Actions workflows",
        type: "component",
        outputChannels: [
          { id: "success", label: "Success" } as any,
          { id: "failure", label: "Failure" } as any,
        ],
        configuration: [
          { key: "repo", label: "Repository", type: "string", required: true },
          {
            key: "workflow",
            label: "Workflow",
            type: "string",
            required: true,
          },
          { key: "ref", label: "Ref", type: "string", required: false },
          { key: "inputs", label: "Inputs", type: "json", required: false },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "github",
        color: "gray",
      },
    ],
  },
  {
    name: "GitLab",
    blocks: [
      // Triggers - GitLab
      {
        name: "gitlab-push",
        label: "GitLab Push",
        description: "Trigger on pushes to a GitLab project",
        type: "trigger",
        outputChannels: [{ id: "push", label: "Push" } as any],
        configuration: [
          { key: "project", label: "Project", type: "string", required: true },
          {
            key: "branches",
            label: "Branches",
            type: "string[]",
            required: false,
          },
          { key: "paths", label: "Paths", type: "string[]", required: false },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "git-branch",
        color: "gray",
      },
      {
        name: "gitlab-merge-request",
        label: "GitLab Merge Request",
        description: "Trigger on MR events (open, update, close, merge)",
        type: "trigger",
        outputChannels: [
          { id: "opened", label: "Opened" } as any,
          { id: "updated", label: "Updated" } as any,
          { id: "closed", label: "Closed" } as any,
          { id: "merged", label: "Merged" } as any,
        ],
        configuration: [
          { key: "project", label: "Project", type: "string", required: true },
          {
            key: "targetBranches",
            label: "Target Branches",
            type: "string[]",
            required: false,
          },
          { key: "labels", label: "Labels", type: "string[]", required: false },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "git-branch",
        color: "gray",
      },
      {
        name: "gitlab-issue-comment",
        label: "GitLab Issue Comment",
        description: "Trigger on new comments on issues/MRs",
        type: "trigger",
        outputChannels: [{ id: "comment", label: "Comment" } as any],
        configuration: [
          { key: "project", label: "Project", type: "string", required: true },
          {
            key: "issueIid",
            label: "Issue/MR IID",
            type: "number",
            required: false,
          },
          {
            key: "contains",
            label: "Comment Contains",
            type: "string",
            required: false,
          },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "git-branch",
        color: "gray",
      },
      {
        name: "gitlab-pipeline",
        label: "GitLab Pipeline",
        description: "Trigger on pipeline status changes",
        type: "trigger",
        outputChannels: [
          { id: "success", label: "Success" } as any,
          { id: "failed", label: "Failed" } as any,
        ],
        configuration: [
          { key: "project", label: "Project", type: "string", required: true },
          { key: "ref", label: "Ref", type: "string", required: false },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "git-branch",
        color: "green",
      },
    ],
  },
  {
    name: "Semaphore",
    blocks: [
      {
        name: "semaphore-ci",
        label: "Semaphore CI",
        description: "Trigger or monitor Semaphore pipelines",
        type: "component",
        outputChannels: [
          { id: "passed", label: "Passed" } as any,
          { id: "failed", label: "Failed" } as any,
        ],
        configuration: [
          { key: "org", label: "Organization", type: "string", required: true },
          { key: "project", label: "Project", type: "string", required: true },
          {
            key: "pipeline",
            label: "Pipeline",
            type: "string",
            required: true,
          },
          {
            key: "parameters",
            label: "Parameters",
            type: "json",
            required: false,
          },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "flag-triangle-right",
        color: "green",
      },
      {
        name: "semaphore-workflow-dispatch",
        label: "Semaphore Run Workflow",
        description: "Start a workflow with parameters",
        type: "component",
        outputChannels: [
          { id: "started", label: "Started" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          { key: "org", label: "Organization", type: "string", required: true },
          { key: "project", label: "Project", type: "string", required: true },
          {
            key: "workflow",
            label: "Workflow",
            type: "string",
            required: true,
          },
          { key: "branch", label: "Branch", type: "string", required: false },
          {
            key: "parameters",
            label: "Parameters",
            type: "json",
            required: false,
          },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "flag-triangle-right",
        color: "green",
      },
      {
        name: "semaphore-pipeline-cancel",
        label: "Semaphore Cancel Pipeline",
        description: "Cancel a running pipeline",
        type: "component",
        outputChannels: [
          { id: "canceled", label: "Canceled" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          { key: "org", label: "Organization", type: "string", required: true },
          { key: "project", label: "Project", type: "string", required: true },
          {
            key: "pipelineId",
            label: "Pipeline ID",
            type: "string",
            required: true,
          },
          { key: "reason", label: "Reason", type: "string", required: false },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "flag-triangle-right",
        color: "green",
      },
      {
        name: "semaphore-pipeline-retry",
        label: "Semaphore Retry Pipeline",
        description: "Retry a failed pipeline",
        type: "component",
        outputChannels: [
          { id: "retried", label: "Retried" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          { key: "org", label: "Organization", type: "string", required: true },
          { key: "project", label: "Project", type: "string", required: true },
          {
            key: "pipelineId",
            label: "Pipeline ID",
            type: "string",
            required: true,
          },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "flag-triangle-right",
        color: "green",
      },
      {
        name: "semaphore-pipeline-promote",
        label: "Semaphore Promote Pipeline",
        description: "Promote a pipeline to the next block",
        type: "component",
        outputChannels: [
          { id: "promoted", label: "Promoted" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          { key: "org", label: "Organization", type: "string", required: true },
          { key: "project", label: "Project", type: "string", required: true },
          {
            key: "pipelineId",
            label: "Pipeline ID",
            type: "string",
            required: true,
          },
          {
            key: "promotion",
            label: "Promotion Name",
            type: "string",
            required: true,
          },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "flag-triangle-right",
        color: "green",
      },
      {
        name: "semaphore-pipeline-trigger",
        label: "Semaphore Pipeline Trigger",
        description: "Trigger on pipeline status changes",
        type: "trigger",
        outputChannels: [
          { id: "passed", label: "Passed" } as any,
          { id: "failed", label: "Failed" } as any,
          { id: "stopped", label: "Stopped" } as any,
        ],
        configuration: [
          { key: "org", label: "Organization", type: "string", required: true },
          { key: "project", label: "Project", type: "string", required: true },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "flag-triangle-right",
        color: "green",
      },
    ],
  },
  {
    name: "Argo",
    blocks: [
      {
        name: "argo-cd",
        label: "Argo CD",
        description: "Sync application in Argo CD and monitor health",
        type: "component",
        outputChannels: [
          { id: "synced", label: "Synced" } as any,
          { id: "degraded", label: "Degraded" } as any,
        ],
        configuration: [
          { key: "app", label: "Application", type: "string", required: true },
          { key: "project", label: "Project", type: "string", required: false },
          {
            key: "server",
            label: "Server URL",
            type: "string",
            required: false,
          },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "cloud-sync",
        color: "red",
      },
      {
        name: "argo-app-wait-health",
        label: "Argo App Wait Health",
        description: "Wait for an app to reach a health status",
        type: "component",
        outputChannels: [
          { id: "healthy", label: "Healthy" } as any,
          { id: "degraded", label: "Degraded" } as any,
          { id: "timeout", label: "Timeout" } as any,
        ],
        configuration: [
          { key: "app", label: "Application", type: "string", required: true },
          {
            key: "server",
            label: "Server URL",
            type: "string",
            required: false,
          },
          {
            key: "desired",
            label: "Desired Health",
            type: "enum",
            values: ["Healthy", "Degraded", "Suspended", "Missing"],
            required: true,
          },
          {
            key: "timeout",
            label: "Timeout (s)",
            type: "number",
            required: false,
          },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "cloud-sync",
        color: "red",
      },
      {
        name: "argo-app-rollback",
        label: "Argo App Rollback",
        description: "Rollback an app to a previous revision",
        type: "component",
        outputChannels: [
          { id: "rolledBack", label: "Rolled Back" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          { key: "app", label: "Application", type: "string", required: true },
          {
            key: "revision",
            label: "Revision",
            type: "string",
            required: true,
          },
          {
            key: "server",
            label: "Server URL",
            type: "string",
            required: false,
          },
          { key: "prune", label: "Prune", type: "boolean", required: false },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "cloud-sync",
        color: "red",
      },
      {
        name: "argo-app-refresh",
        label: "Argo App Refresh",
        description: "Refresh app cache and status from Git & cluster",
        type: "component",
        outputChannels: [{ id: "refreshed", label: "Refreshed" } as any],
        configuration: [
          { key: "app", label: "Application", type: "string", required: true },
          {
            key: "hard",
            label: "Hard Refresh",
            type: "boolean",
            required: false,
          },
          {
            key: "server",
            label: "Server URL",
            type: "string",
            required: false,
          },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "cloud-sync",
        color: "red",
      },
      {
        name: "argo-app-delete",
        label: "Argo App Delete",
        description: "Delete an application (optionally cascade resources)",
        type: "component",
        outputChannels: [
          { id: "deleted", label: "Deleted" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          { key: "app", label: "Application", type: "string", required: true },
          {
            key: "cascade",
            label: "Cascade",
            type: "boolean",
            required: false,
          },
          {
            key: "server",
            label: "Server URL",
            type: "string",
            required: false,
          },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "cloud-sync",
        color: "red",
      },
      {
        name: "argo-app-status-trigger",
        label: "Argo App Status Trigger",
        description: "Trigger on app status changes",
        type: "trigger",
        outputChannels: [
          { id: "healthy", label: "Healthy" } as any,
          { id: "degraded", label: "Degraded" } as any,
          { id: "progressing", label: "Progressing" } as any,
          { id: "synced", label: "Synced" } as any,
          { id: "outOfSync", label: "OutOfSync" } as any,
          { id: "unknown", label: "Unknown" } as any,
        ],
        configuration: [
          { key: "app", label: "Application", type: "string", required: false },
          { key: "project", label: "Project", type: "string", required: false },
          {
            key: "server",
            label: "Server URL",
            type: "string",
            required: false,
          },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "cloud-sync",
        color: "red",
      },
      // Argo Workflows
      {
        name: "argo-workflow-submit",
        label: "Argo Workflow Submit",
        description: "Submit a workflow from template with parameters",
        type: "component",
        outputChannels: [
          { id: "submitted", label: "Submitted" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          {
            key: "namespace",
            label: "Namespace",
            type: "string",
            required: true,
          },
          {
            key: "template",
            label: "Template",
            type: "string",
            required: true,
          },
          {
            key: "parameters",
            label: "Parameters",
            type: "json",
            required: false,
          },
          {
            key: "server",
            label: "Server URL",
            type: "string",
            required: false,
          },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "cloud-sync",
        color: "red",
      },
      {
        name: "argo-workflow-terminate",
        label: "Argo Workflow Terminate",
        description: "Terminate a running workflow",
        type: "component",
        outputChannels: [
          { id: "terminated", label: "Terminated" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          {
            key: "namespace",
            label: "Namespace",
            type: "string",
            required: true,
          },
          {
            key: "name",
            label: "Workflow Name",
            type: "string",
            required: true,
          },
          { key: "message", label: "Message", type: "string", required: false },
          {
            key: "server",
            label: "Server URL",
            type: "string",
            required: false,
          },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "cloud-sync",
        color: "red",
      },
      {
        name: "argo-workflow-status-trigger",
        label: "Argo Workflow Status Trigger",
        description: "Trigger on workflow status changes",
        type: "trigger",
        outputChannels: [
          { id: "succeeded", label: "Succeeded" } as any,
          { id: "failed", label: "Failed" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          {
            key: "namespace",
            label: "Namespace",
            type: "string",
            required: true,
          },
          {
            key: "name",
            label: "Workflow Name",
            type: "string",
            required: false,
          },
          {
            key: "server",
            label: "Server URL",
            type: "string",
            required: false,
          },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "cloud-sync",
        color: "red",
      },
    ],
  },
  {
    name: "PagerDuty",
    blocks: [
      // Triggers
      {
        name: "pagerduty-incident-trigger",
        label: "Incident Events",
        description: "Trigger on incident events",
        type: "trigger",
        outputChannels: [
          { id: "triggered", label: "Triggered" } as any,
          { id: "acknowledged", label: "Acknowledged" } as any,
          { id: "resolved", label: "Resolved" } as any,
          { id: "escalated", label: "Escalated" } as any,
          { id: "assigned", label: "Assigned" } as any,
        ],
        configuration: [
          {
            key: "services",
            label: "Service IDs",
            type: "string[]",
            required: false,
          },
          {
            key: "severities",
            label: "Severities",
            type: "string[]",
            required: false,
          },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "siren",
        color: "red",
      },
      {
        name: "pagerduty-oncall-trigger",
        label: "On-call Changes",
        description: "Trigger on on-call handoffs/changes",
        type: "trigger",
        outputChannels: [
          { id: "handoff", label: "Handoff" } as any,
          { id: "start", label: "Start" } as any,
          { id: "end", label: "End" } as any,
        ],
        configuration: [
          {
            key: "scheduleIds",
            label: "Schedule IDs",
            type: "string[]",
            required: false,
          },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "siren",
        color: "red",
      },
      {
        name: "pagerduty-maintenance-trigger",
        label: "Maintenance Windows",
        description: "Trigger on maintenance window start/end",
        type: "trigger",
        outputChannels: [
          { id: "start", label: "Start" } as any,
          { id: "end", label: "End" } as any,
        ],
        configuration: [
          {
            key: "serviceIds",
            label: "Service IDs",
            type: "string[]",
            required: false,
          },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "siren",
        color: "red",
      },

      // Actions - Incidents
      {
        name: "pagerduty-incident-create",
        label: "Create Incident",
        description: "Create/trigger a new incident",
        type: "component",
        outputChannels: [{ id: "created", label: "Created" } as any],
        configuration: [
          {
            key: "routingKey",
            label: "Routing Key (secret)",
            type: "string",
            required: true,
          },
          { key: "summary", label: "Summary", type: "string", required: true },
          {
            key: "severity",
            label: "Severity",
            type: "enum",
            values: ["info", "warning", "error", "critical"],
            required: true,
          },
          { key: "source", label: "Source", type: "string", required: false },
          {
            key: "customDetails",
            label: "Custom Details",
            type: "json",
            required: false,
          },
          {
            key: "dedupKey",
            label: "Dedup Key",
            type: "string",
            required: false,
          },
        ],
        icon: "siren",
        color: "red",
      },
      {
        name: "pagerduty-incident-resolve",
        label: "Resolve Incident",
        description: "Resolve an existing incident",
        type: "component",
        outputChannels: [{ id: "resolved", label: "Resolved" } as any],
        configuration: [
          {
            key: "routingKey",
            label: "Routing Key (secret)",
            type: "string",
            required: true,
          },
          {
            key: "dedupKey",
            label: "Dedup/Incident Key",
            type: "string",
            required: true,
          },
          { key: "summary", label: "Summary", type: "string", required: false },
        ],
        icon: "siren",
        color: "red",
      },
      {
        name: "pagerduty-incident-ack",
        label: "Acknowledge Incident",
        description: "Acknowledge an incident",
        type: "component",
        outputChannels: [{ id: "acknowledged", label: "Acknowledged" } as any],
        configuration: [
          {
            key: "routingKey",
            label: "Routing Key (secret)",
            type: "string",
            required: true,
          },
          {
            key: "dedupKey",
            label: "Dedup/Incident Key",
            type: "string",
            required: true,
          },
          { key: "summary", label: "Summary", type: "string", required: false },
        ],
        icon: "siren",
        color: "red",
      },
      {
        name: "pagerduty-incident-note",
        label: "Add Incident Note",
        description: "Add a note to an incident",
        type: "component",
        outputChannels: [{ id: "noted", label: "Noted" } as any],
        configuration: [
          {
            key: "apiToken",
            label: "API Token (secret)",
            type: "string",
            required: true,
          },
          {
            key: "incidentId",
            label: "Incident ID",
            type: "string",
            required: true,
          },
          { key: "note", label: "Note", type: "text", required: true },
        ],
        icon: "siren",
        color: "red",
      },
      {
        name: "pagerduty-incident-escalate",
        label: "Escalate Incident",
        description: "Escalate an incident",
        type: "component",
        outputChannels: [{ id: "escalated", label: "Escalated" } as any],
        configuration: [
          {
            key: "apiToken",
            label: "API Token (secret)",
            type: "string",
            required: true,
          },
          {
            key: "incidentId",
            label: "Incident ID",
            type: "string",
            required: true,
          },
          {
            key: "escalationLevel",
            label: "Escalation Level",
            type: "number",
            required: false,
          },
        ],
        icon: "siren",
        color: "red",
      },
      {
        name: "pagerduty-incident-reassign",
        label: "Reassign Incident",
        description: "Reassign an incident to a user/team",
        type: "component",
        outputChannels: [{ id: "reassigned", label: "Reassigned" } as any],
        configuration: [
          {
            key: "apiToken",
            label: "API Token (secret)",
            type: "string",
            required: true,
          },
          {
            key: "incidentId",
            label: "Incident ID",
            type: "string",
            required: true,
          },
          {
            key: "assignees",
            label: "Assignee IDs",
            type: "string[]",
            required: true,
          },
        ],
        icon: "siren",
        color: "red",
      },

      // Actions - Change events & maintenance
      {
        name: "pagerduty-change-event",
        label: "Create Change Event",
        description: "Post a change event to services",
        type: "component",
        outputChannels: [{ id: "posted", label: "Posted" } as any],
        configuration: [
          {
            key: "routingKey",
            label: "Routing Key (secret)",
            type: "string",
            required: true,
          },
          { key: "summary", label: "Summary", type: "string", required: true },
          { key: "source", label: "Source", type: "string", required: false },
          {
            key: "customDetails",
            label: "Custom Details",
            type: "json",
            required: false,
          },
        ],
        icon: "siren",
        color: "red",
      },
      {
        name: "pagerduty-maintenance-create",
        label: "Create Maintenance Window",
        description: "Create a maintenance window for services",
        type: "component",
        outputChannels: [{ id: "created", label: "Created" } as any],
        configuration: [
          {
            key: "apiToken",
            label: "API Token (secret)",
            type: "string",
            required: true,
          },
          {
            key: "serviceIds",
            label: "Service IDs",
            type: "string[]",
            required: true,
          },
          {
            key: "start",
            label: "Start (ISO8601)",
            type: "string",
            required: true,
          },
          {
            key: "end",
            label: "End (ISO8601)",
            type: "string",
            required: true,
          },
          {
            key: "description",
            label: "Description",
            type: "string",
            required: false,
          },
        ],
        icon: "siren",
        color: "red",
      },
    ],
  },
  {
    name: "Datadog",
    blocks: [
      {
        name: "datadog-metric-query",
        label: "Metric Query",
        description: "Query time series metrics",
        type: "component",
        outputChannels: [{ id: "data", label: "Data" } as any],
        configuration: [
          { key: "query", label: "Query", type: "string", required: true },
          {
            key: "from",
            label: "From (s ago)",
            type: "number",
            required: true,
          },
          { key: "to", label: "To (s ago)", type: "number", required: false },
          {
            key: "interval",
            label: "Interval (s)",
            type: "number",
            required: false,
          },
          {
            key: "apiKey",
            label: "API Key (secret)",
            type: "string",
            required: false,
          },
          {
            key: "appKey",
            label: "App Key (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "dog",
        color: "purple",
      },
      {
        name: "datadog-monitors-query",
        label: "Monitors Query",
        description: "List monitors matching filters",
        type: "component",
        outputChannels: [{ id: "monitors", label: "Monitors" } as any],
        configuration: [
          { key: "query", label: "Query", type: "string", required: false },
          { key: "tags", label: "Tags", type: "string[]", required: false },
          {
            key: "status",
            label: "Status",
            type: "enum",
            values: ["OK", "Alert", "Warn", "No Data", "Ignored"],
            required: false,
          },
          {
            key: "apiKey",
            label: "API Key (secret)",
            type: "string",
            required: false,
          },
          {
            key: "appKey",
            label: "App Key (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "dog",
        color: "purple",
      },
      {
        name: "datadog-event-create",
        label: "Create Event",
        description: "Create a Datadog event",
        type: "component",
        outputChannels: [{ id: "created", label: "Created" } as any],
        configuration: [
          { key: "title", label: "Title", type: "string", required: true },
          { key: "text", label: "Text", type: "text", required: true },
          { key: "tags", label: "Tags", type: "string[]", required: false },
          {
            key: "priority",
            label: "Priority",
            type: "enum",
            values: ["normal", "low"],
            required: false,
          },
          {
            key: "alertType",
            label: "Alert Type",
            type: "enum",
            values: ["info", "success", "warning", "error"],
            required: false,
          },
          {
            key: "apiKey",
            label: "API Key (secret)",
            type: "string",
            required: false,
          },
          {
            key: "appKey",
            label: "App Key (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "dog",
        color: "purple",
      },
      {
        name: "datadog-monitor-trigger",
        label: "Monitor Trigger",
        description: "Trigger on monitor status changes",
        type: "trigger",
        outputChannels: [
          { id: "ok", label: "OK" } as any,
          { id: "alert", label: "Alert" } as any,
          { id: "warn", label: "Warn" } as any,
          { id: "noData", label: "No Data" } as any,
        ],
        configuration: [
          {
            key: "monitorIds",
            label: "Monitor IDs",
            type: "string[]",
            required: false,
          },
          { key: "tags", label: "Tags", type: "string[]", required: false },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "dog",
        color: "purple",
      },
      {
        name: "datadog-event-stream-trigger",
        label: "Event Stream Trigger",
        description: "Trigger on Datadog events matching filters",
        type: "trigger",
        outputChannels: [{ id: "event", label: "Event" } as any],
        configuration: [
          { key: "query", label: "Query", type: "string", required: false },
          { key: "tags", label: "Tags", type: "string[]", required: false },
          {
            key: "priorities",
            label: "Priorities",
            type: "string[]",
            required: false,
          },
          {
            key: "sources",
            label: "Sources",
            type: "string[]",
            required: false,
          },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "dog",
        color: "purple",
      },
      {
        name: "datadog-logs-trigger",
        label: "Logs Trigger",
        description: "Trigger on logs matching a query",
        type: "trigger",
        outputChannels: [{ id: "match", label: "Match" } as any],
        configuration: [
          { key: "query", label: "Query", type: "string", required: true },
          {
            key: "indexes",
            label: "Indexes",
            type: "string[]",
            required: false,
          },
          { key: "service", label: "Service", type: "string", required: false },
          { key: "tags", label: "Tags", type: "string[]", required: false },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "dog",
        color: "purple",
      },
      {
        name: "datadog-slo-burn-trigger",
        label: "SLO Burn Trigger",
        description: "Trigger when SLO burn rate crosses a threshold",
        type: "trigger",
        outputChannels: [
          { id: "breached", label: "Breached" } as any,
          { id: "recovered", label: "Recovered" } as any,
        ],
        configuration: [
          { key: "sloId", label: "SLO ID", type: "string", required: true },
          {
            key: "window",
            label: "Window (min)",
            type: "number",
            required: false,
          },
          {
            key: "burnRate",
            label: "Burn Rate",
            type: "number",
            required: true,
          },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "dog",
        color: "purple",
      },
      {
        name: "datadog-metric-anomaly-trigger",
        label: "Metric Anomaly Trigger",
        description: "Trigger on metric anomalies (heuristic)",
        type: "trigger",
        outputChannels: [{ id: "anomaly", label: "Anomaly" } as any],
        configuration: [
          { key: "query", label: "Query", type: "string", required: true },
          {
            key: "sensitivity",
            label: "Sensitivity",
            type: "enum",
            values: ["low", "medium", "high"],
            required: false,
          },
          {
            key: "window",
            label: "Window (min)",
            type: "number",
            required: false,
          },
          {
            key: "token",
            label: "Webhook Token",
            type: "string",
            required: false,
          },
        ],
        icon: "dog",
        color: "purple",
      },
    ],
  },
  {
    name: "Snyk",
    blocks: [
      // Actions
      {
        name: "snyk-project-test",
        label: "Project Test",
        description: "Test a project for vulnerabilities",
        type: "component",
        outputChannels: [{ id: "clean", label: "Clean" } as any, { id: "vulns", label: "Vulnerabilities" } as any],
        configuration: [
          { key: "org", label: "Org", type: "string", required: false },
          { key: "project", label: "Project", type: "string", required: true },
          { key: "severity", label: "Min Severity", type: "enum", values: ["low","medium","high","critical"], required: false },
          { key: "failOn", label: "Fail On", type: "enum", values: ["all","upgradable","patchable","none"], required: false },
          { key: "token", label: "Token (secret)", type: "string", required: false },
        ],
        icon: "shield-check",
        color: "purple",
      },
      {
        name: "snyk-monitor-project",
        label: "Monitor Project",
        description: "Create a monitored snapshot for continuous alerts",
        type: "component",
        outputChannels: [{ id: "monitored", label: "Monitored" } as any],
        configuration: [
          { key: "org", label: "Org", type: "string", required: false },
          { key: "project", label: "Project", type: "string", required: true },
          { key: "targetRef", label: "Target Ref", type: "string", required: false },
          { key: "token", label: "Token (secret)", type: "string", required: false },
        ],
        icon: "shield-check",
        color: "purple",
      },
      {
        name: "snyk-issue-ignore",
        label: "Ignore Issue",
        description: "Ignore a specific issue with reason and expiry",
        type: "component",
        outputChannels: [{ id: "ignored", label: "Ignored" } as any, { id: "error", label: "Error" } as any],
        configuration: [
          { key: "apiToken", label: "API Token (secret)", type: "string", required: true },
          { key: "org", label: "Org", type: "string", required: true },
          { key: "issueId", label: "Issue ID", type: "string", required: true },
          { key: "reason", label: "Reason", type: "string", required: false },
          { key: "expiresAt", label: "Expires At (ISO8601)", type: "string", required: false },
        ],
        icon: "shield-check",
        color: "purple",
      },
      {
        name: "snyk-report-export",
        label: "Export Report",
        description: "Export vulnerability report for a project",
        type: "component",
        outputChannels: [{ id: "report", label: "Report" } as any],
        configuration: [
          { key: "apiToken", label: "API Token (secret)", type: "string", required: true },
          { key: "org", label: "Org", type: "string", required: true },
          { key: "project", label: "Project", type: "string", required: true },
          { key: "format", label: "Format", type: "enum", values: ["json","csv"], required: false },
          { key: "severity", label: "Min Severity", type: "enum", values: ["low","medium","high","critical"], required: false },
        ],
        icon: "shield-check",
        color: "purple",
      },

      // Events / Triggers
      {
        name: "snyk-pr-check-trigger",
        label: "PR Check Status",
        description: "Trigger on Snyk PR check pass/fail",
        type: "trigger",
        outputChannels: [{ id: "passed", label: "Passed" } as any, { id: "failed", label: "Failed" } as any],
        configuration: [
          { key: "repos", label: "Repositories", type: "string[]", required: false },
          { key: "branches", label: "Branches", type: "string[]", required: false },
          { key: "token", label: "Webhook Token", type: "string", required: false },
        ],
        icon: "shield-check",
        color: "purple",
      },
      {
        name: "snyk-issue-created-trigger",
        label: "Issue Created",
        description: "Trigger on new vulnerability/license issues",
        type: "trigger",
        outputChannels: [{ id: "issue", label: "Issue" } as any],
        configuration: [
          { key: "orgs", label: "Orgs", type: "string[]", required: false },
          { key: "types", label: "Types", type: "string[]", required: false },
          { key: "severities", label: "Severities", type: "string[]", required: false },
          { key: "token", label: "Webhook Token", type: "string", required: false },
        ],
        icon: "shield-check",
        color: "purple",
      },
      {
        name: "snyk-issue-updated-trigger",
        label: "Issue Updated",
        description: "Trigger on issue fix/ignore/reopen",
        type: "trigger",
        outputChannels: [{ id: "updated", label: "Updated" } as any],
        configuration: [
          { key: "orgs", label: "Orgs", type: "string[]", required: false },
          { key: "actions", label: "Actions", type: "string[]", required: false },
          { key: "token", label: "Webhook Token", type: "string", required: false },
        ],
        icon: "shield-check",
        color: "purple",
      },
      {
        name: "snyk-project-imported-trigger",
        label: "Project Imported",
        description: "Trigger when a project is imported",
        type: "trigger",
        outputChannels: [{ id: "imported", label: "Imported" } as any],
        configuration: [
          { key: "orgs", label: "Orgs", type: "string[]", required: false },
          { key: "token", label: "Webhook Token", type: "string", required: false },
        ],
        icon: "shield-check",
        color: "purple",
      },
    ],
  },
  {
    name: "Kubernetes",
    blocks: [
      // Kubernetes specific actions
      {
        name: "k8s-apply-manifest",
        label: "K8s Apply Manifest",
        description: "Apply a Kubernetes manifest to a cluster",
        type: "component",
        outputChannels: [
          { id: "applied", label: "Applied" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          { key: "cluster", label: "Cluster", type: "string", required: false },
          {
            key: "namespace",
            label: "Namespace",
            type: "string",
            required: false,
          },
          {
            key: "manifest",
            label: "Manifest (YAML)",
            type: "text",
            required: true,
          },
        ],
        icon: "cuboid",
        color: "blue",
      },
      {
        name: "k8s-rollout-restart",
        label: "K8s Rollout Restart",
        description: "Restart a deployment and wait for readiness",
        type: "component",
        outputChannels: [
          { id: "success", label: "Success" } as any,
          { id: "failed", label: "Failed" } as any,
        ],
        configuration: [
          { key: "cluster", label: "Cluster", type: "string", required: false },
          {
            key: "namespace",
            label: "Namespace",
            type: "string",
            required: true,
          },
          {
            key: "deployment",
            label: "Deployment",
            type: "string",
            required: true,
          },
          {
            key: "timeout",
            label: "Timeout (s)",
            type: "number",
            required: false,
          },
        ],
        icon: "cuboid",
        color: "blue",
      },
      {
        name: "k8s-get-resource",
        label: "K8s Get Resource",
        description: "Get a resource by kind/name and optional selector",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          { key: "cluster", label: "Cluster", type: "string", required: false },
          {
            key: "namespace",
            label: "Namespace",
            type: "string",
            required: false,
          },
          {
            key: "kind",
            label: "Kind",
            type: "enum",
            values: ["pod", "deployment", "service", "ingress", "job"],
            required: true,
          },
          { key: "name", label: "Name", type: "string", required: false },
          {
            key: "selector",
            label: "Selector",
            type: "string",
            required: false,
          },
        ],
        icon: "cuboid",
        color: "blue",
      },
    ],
  },
  {
    name: "AWS",
    blocks: [
      {
        name: "aws-lambda-invoke",
        label: "AWS Lambda Invoke",
        description: "Invoke a Lambda function with payload",
        type: "component",
        outputChannels: [
          { id: "success", label: "Success" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          {
            key: "functionName",
            label: "Function Name",
            type: "string",
            required: true,
          },
          { key: "region", label: "Region", type: "string", required: false },
          { key: "payload", label: "Payload", type: "json", required: false },
        ],
        icon: "cloud",
        color: "orange",
      },
      {
        name: "aws-s3-upload",
        label: "AWS S3 Upload",
        description: "Upload an object to an S3 bucket",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          { key: "bucket", label: "Bucket", type: "string", required: true },
          { key: "key", label: "Key", type: "string", required: true },
          { key: "body", label: "Body", type: "text", required: true },
          { key: "region", label: "Region", type: "string", required: false },
          {
            key: "contentType",
            label: "Content-Type",
            type: "string",
            required: false,
          },
        ],
        icon: "cloud",
        color: "orange",
      },
      {
        name: "aws-ecs-deploy",
        label: "AWS ECS Deploy",
        description: "Update ECS service to new task definition",
        type: "component",
        outputChannels: [
          { id: "deployed", label: "Deployed" } as any,
          { id: "failed", label: "Failed" } as any,
        ],
        configuration: [
          { key: "cluster", label: "Cluster", type: "string", required: true },
          { key: "service", label: "Service", type: "string", required: true },
          {
            key: "taskDefinition",
            label: "Task Definition",
            type: "string",
            required: true,
          },
          { key: "region", label: "Region", type: "string", required: false },
          {
            key: "wait",
            label: "Wait for stability",
            type: "boolean",
            required: false,
          },
        ],
        icon: "cloud",
        color: "orange",
      },
    ],
  },
  {
    name: "GCP",
    blocks: [
      {
        name: "gcp-cloud-run-deploy",
        label: "GCP Cloud Run Deploy",
        description: "Deploy a revision to Cloud Run",
        type: "component",
        outputChannels: [
          { id: "deployed", label: "Deployed" } as any,
          { id: "failed", label: "Failed" } as any,
        ],
        configuration: [
          { key: "service", label: "Service", type: "string", required: true },
          { key: "image", label: "Image", type: "string", required: true },
          { key: "region", label: "Region", type: "string", required: false },
          { key: "env", label: "Env Vars", type: "json", required: false },
        ],
        icon: "cloud",
        color: "blue",
      },
      {
        name: "gcp-pubsub-publish",
        label: "GCP Pub/Sub Publish",
        description: "Publish a message to a Pub/Sub topic",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          { key: "topic", label: "Topic", type: "string", required: true },
          { key: "message", label: "Message", type: "text", required: true },
          {
            key: "attributes",
            label: "Attributes",
            type: "json",
            required: false,
          },
        ],
        icon: "cloud",
        color: "blue",
      },
      {
        name: "gcp-gke-rollout",
        label: "GCP GKE Rollout",
        description: "Roll out a deployment on GKE",
        type: "component",
        outputChannels: [
          { id: "success", label: "Success" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          { key: "cluster", label: "Cluster", type: "string", required: true },
          {
            key: "namespace",
            label: "Namespace",
            type: "string",
            required: true,
          },
          {
            key: "deployment",
            label: "Deployment",
            type: "string",
            required: true,
          },
          { key: "image", label: "Image", type: "string", required: false },
        ],
        icon: "cloud",
        color: "blue",
      },
    ],
  },
  {
    name: "Cloudflare",
    blocks: [
      {
        name: "cloudflare-cache-purge",
        label: "Cloudflare Cache Purge",
        description: "Purge cache by URL or everything",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          { key: "zone", label: "Zone ID", type: "string", required: true },
          {
            key: "purgeEverything",
            label: "Purge Everything",
            type: "boolean",
            required: false,
          },
          { key: "urls", label: "URLs", type: "string[]", required: false },
        ],
        icon: "cloud",
        color: "yellow",
      },
      {
        name: "cloudflare-dns-update",
        label: "Cloudflare DNS Update",
        description: "Create or update a DNS record",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          { key: "zone", label: "Zone ID", type: "string", required: true },
          {
            key: "type",
            label: "Type",
            type: "enum",
            values: ["A", "AAAA", "CNAME", "TXT"],
            required: true,
          },
          { key: "name", label: "Name", type: "string", required: true },
          { key: "content", label: "Content", type: "string", required: true },
          { key: "ttl", label: "TTL", type: "number", required: false },
          {
            key: "proxied",
            label: "Proxied",
            type: "boolean",
            required: false,
          },
        ],
        icon: "cloud",
        color: "yellow",
      },
      {
        name: "cloudflare-workers-deploy",
        label: "Cloudflare Workers Deploy",
        description: "Deploy a Worker script to a route",
        type: "component",
        outputChannels: [
          { id: "deployed", label: "Deployed" } as any,
          { id: "failed", label: "Failed" } as any,
        ],
        configuration: [
          {
            key: "scriptName",
            label: "Script Name",
            type: "string",
            required: true,
          },
          { key: "route", label: "Route", type: "string", required: false },
          {
            key: "accountId",
            label: "Account ID",
            type: "string",
            required: false,
          },
        ],
        icon: "cloud",
        color: "yellow",
      },
    ],
  },
  {
    name: "Custom Components",
    blocks: [
      // Complex user-built components
      {
        name: "deployment",
        label: "Deployment",
        description: "Standardized deploy flow across environments",
        type: "blueprint",
        outputChannels: [
          { id: "success", label: "Success" } as any,
          { id: "failed", label: "Failed" } as any,
        ],
        configuration: [
          {
            key: "environment",
            label: "Environment",
            type: "enum",
            values: ["dev", "staging", "prod"],
            required: true,
          },
          {
            key: "strategy",
            label: "Strategy",
            type: "enum",
            values: ["rolling", "blue-green", "canary"],
            required: false,
          },
          { key: "version", label: "Version", type: "string", required: true },
        ],
        icon: "truck",
        color: "blue",
        id: "bp-deployment",
      },
      {
        name: "incident-monitor",
        label: "Incident Monitor",
        description: "Detect, triage, and route incidents",
        type: "blueprint",
        outputChannels: [
          { id: "resolved", label: "Resolved" } as any,
          { id: "escalated", label: "Escalated" } as any,
        ],
        configuration: [
          {
            key: "sources",
            label: "Sources",
            type: "string[]",
            required: false,
          },
          {
            key: "sevThreshold",
            label: "Severity Threshold",
            type: "enum",
            values: ["low", "medium", "high", "critical"],
            required: false,
          },
          {
            key: "onCallSchedule",
            label: "On-call Schedule",
            type: "string",
            required: false,
          },
        ],
        icon: "alert-triangle",
        color: "orange",
        id: "bp-incident-monitor",
      },
    ],
  },
];
