import { BuildingBlockCategory } from "../../BuildingBlocksSidebar";

export const mockBuildingBlockCategories: BuildingBlockCategory[] = [
  {
    name: "Primitives",
    blocks: [
      // Primitives
      {
        name: "if",
        label: "If",
        description: "Branch execution based on a condition",
        type: "component",
        outputChannels: [
          { id: "then", label: "Then" } as any,
          { id: "else", label: "Else" } as any,
        ],
        configuration: [
          {
            key: "expression",
            label: "Expression",
            type: "string",
            required: true,
          },
        ],
        icon: "braces",
        color: "gray",
      },
      {
        name: "switch",
        label: "Switch",
        description: "Multi-branch switch over a value",
        type: "component",
        outputChannels: [
          { id: "case-1", label: "Case 1" } as any,
          { id: "case-2", label: "Case 2" } as any,
          { id: "default", label: "Default" } as any,
        ],
        configuration: [
          { key: "value", label: "Value", type: "string", required: true },
          { key: "cases", label: "Cases", type: "json", required: false },
        ],
        icon: "git-branch",
        color: "gray",
      },
      {
        name: "filter",
        label: "Filter",
        description: "Filter a list using a predicate",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          {
            key: "predicate",
            label: "Predicate",
            type: "string",
            required: true,
          },
        ],
        icon: "filter",
        color: "gray",
      },
      {
        name: "approval",
        label: "Approval",
        description: "Pause until manual approval or rejection",
        type: "component",
        outputChannels: [
          { id: "approved", label: "Approved" } as any,
          { id: "rejected", label: "Rejected" } as any,
        ],
        configuration: [
          {
            key: "approvers",
            label: "Approvers",
            type: "string[]",
            required: true,
          },
          {
            key: "timeout",
            label: "Timeout (mins)",
            type: "number",
            required: false,
          },
        ],
        icon: "check-circle-2",
        color: "green",
      },
      {
        name: "wait",
        label: "Wait",
        description: "Delay for a period or until a time",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          {
            key: "duration",
            label: "Duration (s)",
            type: "number",
            required: false,
          },
          {
            key: "until",
            label: "Until (ISO8601)",
            type: "string",
            required: false,
          },
        ],
        icon: "hourglass",
        color: "yellow",
      },
      {
        name: "cron",
        label: "Cron",
        description: "Trigger on a cron schedule",
        type: "trigger",
        outputChannels: [{ id: "tick", label: "Tick" } as any],
        configuration: [
          {
            key: "expression",
            label: "Cron Expression",
            type: "string",
            required: true,
          },
          {
            key: "timezone",
            label: "Timezone",
            type: "string",
            required: false,
          },
        ],
        icon: "calendar-clock",
        color: "blue",
      },
      {
        name: "webhook",
        label: "Webhook",
        description: "Trigger on inbound HTTP webhook",
        type: "trigger",
        outputChannels: [{ id: "event", label: "Event" } as any],
        configuration: [
          { key: "path", label: "Path", type: "string", required: true },
          {
            key: "method",
            label: "Method",
            type: "enum",
            values: ["GET", "POST", "PUT", "PATCH"],
            required: true,
          },
          { key: "secret", label: "Secret", type: "string", required: false },
        ],
        icon: "webhook",
        color: "blue",
      },
      {
        name: "http-request",
        label: "HTTP Request",
        description: "Make an outbound HTTP request",
        type: "component",
        outputChannels: [
          { id: "success", label: "Success" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          { key: "url", label: "URL", type: "string", required: true },
          {
            key: "method",
            label: "Method",
            type: "enum",
            values: ["GET", "POST", "PUT", "PATCH", "DELETE"],
            required: true,
          },
          { key: "headers", label: "Headers", type: "json", required: false },
          { key: "body", label: "Body", type: "json", required: false },
        ],
        icon: "globe",
        color: "gray",
      },
      {
        name: "ai-agent",
        label: "AI Agent",
        description: "Run an AI task to analyze or generate ops data",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          { key: "model", label: "Model", type: "string", required: false },
          { key: "prompt", label: "Prompt", type: "text", required: true },
          { key: "inputs", label: "Inputs", type: "json", required: false },
        ],
        icon: "bot",
        color: "purple",
      },
    ],
  },
  {
    name: "CI/CD",
    blocks: [
      // Platform integrations
      {
        name: "github-actions",
        label: "GitHub Actions",
        description: "Dispatch or wait on GitHub Actions workflows",
        type: "component",
        outputChannels: [
          { id: "success", label: "Success" } as any,
          { id: "failure", label: "Failure" } as any,
        ],
        configuration: [
          { key: "repo", label: "Repository", type: "string", required: true },
          {
            key: "workflow",
            label: "Workflow",
            type: "string",
            required: true,
          },
          { key: "ref", label: "Ref", type: "string", required: false },
          { key: "inputs", label: "Inputs", type: "json", required: false },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "github",
        color: "gray",
      },
      {
        name: "semaphore-ci",
        label: "Semaphore CI",
        description: "Trigger or monitor Semaphore pipelines",
        type: "component",
        outputChannels: [
          { id: "passed", label: "Passed" } as any,
          { id: "failed", label: "Failed" } as any,
        ],
        configuration: [
          { key: "org", label: "Organization", type: "string", required: true },
          { key: "project", label: "Project", type: "string", required: true },
          {
            key: "pipeline",
            label: "Pipeline",
            type: "string",
            required: true,
          },
          {
            key: "parameters",
            label: "Parameters",
            type: "json",
            required: false,
          },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "flag-triangle-right",
        color: "green",
      },
      {
        name: "argo-cd",
        label: "Argo CD",
        description: "Sync application in Argo CD and monitor health",
        type: "component",
        outputChannels: [
          { id: "synced", label: "Synced" } as any,
          { id: "degraded", label: "Degraded" } as any,
        ],
        configuration: [
          { key: "app", label: "Application", type: "string", required: true },
          { key: "project", label: "Project", type: "string", required: false },
          {
            key: "server",
            label: "Server URL",
            type: "string",
            required: false,
          },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "cloud-sync",
        color: "red",
      },
    ],
  },
  {
    name: "Observability & Incidents",
    blocks: [
      {
        name: "datadog",
        label: "Datadog",
        description: "Query monitors, metrics, or create events",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          {
            key: "action",
            label: "Action",
            type: "enum",
            values: ["query-metric", "query-monitors", "create-event"],
            required: true,
          },
          { key: "params", label: "Params", type: "json", required: false },
          {
            key: "apiKey",
            label: "API Key (secret)",
            type: "string",
            required: false,
          },
          {
            key: "appKey",
            label: "App Key (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "dog",
        color: "purple",
      },
      {
        name: "pagerduty",
        label: "PagerDuty",
        description: "Create or resolve incidents, or post notes",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          {
            key: "action",
            label: "Action",
            type: "enum",
            values: ["trigger", "resolve", "note"],
            required: true,
          },
          {
            key: "routingKey",
            label: "Routing Key (secret)",
            type: "string",
            required: false,
          },
          {
            key: "incidentKey",
            label: "Incident Key",
            type: "string",
            required: false,
          },
          { key: "payload", label: "Payload", type: "json", required: false },
        ],
        icon: "siren",
        color: "red",
      },
      {
        name: "snyk",
        label: "Snyk",
        description: "Scan projects and report vulnerabilities",
        type: "component",
        outputChannels: [
          { id: "clean", label: "Clean" } as any,
          { id: "vulns", label: "Vulnerabilities" } as any,
        ],
        configuration: [
          { key: "org", label: "Org", type: "string", required: false },
          { key: "project", label: "Project", type: "string", required: true },
          {
            key: "severity",
            label: "Min Severity",
            type: "enum",
            values: ["low", "medium", "high", "critical"],
            required: false,
          },
          {
            key: "token",
            label: "Token (secret)",
            type: "string",
            required: false,
          },
        ],
        icon: "shield-check",
        color: "purple",
      },
    ],
  },
  {
    name: "Kubernetes",
    blocks: [
      // Kubernetes specific actions
      {
        name: "k8s-apply-manifest",
        label: "K8s Apply Manifest",
        description: "Apply a Kubernetes manifest to a cluster",
        type: "component",
        outputChannels: [
          { id: "applied", label: "Applied" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          { key: "cluster", label: "Cluster", type: "string", required: false },
          {
            key: "namespace",
            label: "Namespace",
            type: "string",
            required: false,
          },
          {
            key: "manifest",
            label: "Manifest (YAML)",
            type: "text",
            required: true,
          },
        ],
        icon: "cuboid",
        color: "blue",
      },
      {
        name: "k8s-rollout-restart",
        label: "K8s Rollout Restart",
        description: "Restart a deployment and wait for readiness",
        type: "component",
        outputChannels: [
          { id: "success", label: "Success" } as any,
          { id: "failed", label: "Failed" } as any,
        ],
        configuration: [
          { key: "cluster", label: "Cluster", type: "string", required: false },
          {
            key: "namespace",
            label: "Namespace",
            type: "string",
            required: true,
          },
          {
            key: "deployment",
            label: "Deployment",
            type: "string",
            required: true,
          },
          {
            key: "timeout",
            label: "Timeout (s)",
            type: "number",
            required: false,
          },
        ],
        icon: "cuboid",
        color: "blue",
      },
      {
        name: "k8s-get-resource",
        label: "K8s Get Resource",
        description: "Get a resource by kind/name and optional selector",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          { key: "cluster", label: "Cluster", type: "string", required: false },
          {
            key: "namespace",
            label: "Namespace",
            type: "string",
            required: false,
          },
          {
            key: "kind",
            label: "Kind",
            type: "enum",
            values: ["pod", "deployment", "service", "ingress", "job"],
            required: true,
          },
          { key: "name", label: "Name", type: "string", required: false },
          {
            key: "selector",
            label: "Selector",
            type: "string",
            required: false,
          },
        ],
        icon: "cuboid",
        color: "blue",
      },
    ],
  },
  {
    name: "Cloud Providers",
    blocks: [
      // Cloud providers split into specific actions
      {
        name: "aws-lambda-invoke",
        label: "AWS Lambda Invoke",
        description: "Invoke a Lambda function with payload",
        type: "component",
        outputChannels: [
          { id: "success", label: "Success" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          {
            key: "functionName",
            label: "Function Name",
            type: "string",
            required: true,
          },
          { key: "region", label: "Region", type: "string", required: false },
          { key: "payload", label: "Payload", type: "json", required: false },
        ],
        icon: "cloud",
        color: "orange",
      },
      {
        name: "aws-s3-upload",
        label: "AWS S3 Upload",
        description: "Upload an object to an S3 bucket",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          { key: "bucket", label: "Bucket", type: "string", required: true },
          { key: "key", label: "Key", type: "string", required: true },
          { key: "body", label: "Body", type: "text", required: true },
          { key: "region", label: "Region", type: "string", required: false },
          {
            key: "contentType",
            label: "Content-Type",
            type: "string",
            required: false,
          },
        ],
        icon: "cloud",
        color: "orange",
      },
      {
        name: "aws-ecs-deploy",
        label: "AWS ECS Deploy",
        description: "Update ECS service to new task definition",
        type: "component",
        outputChannels: [
          { id: "deployed", label: "Deployed" } as any,
          { id: "failed", label: "Failed" } as any,
        ],
        configuration: [
          { key: "cluster", label: "Cluster", type: "string", required: true },
          { key: "service", label: "Service", type: "string", required: true },
          {
            key: "taskDefinition",
            label: "Task Definition",
            type: "string",
            required: true,
          },
          { key: "region", label: "Region", type: "string", required: false },
          {
            key: "wait",
            label: "Wait for stability",
            type: "boolean",
            required: false,
          },
        ],
        icon: "cloud",
        color: "orange",
      },
      {
        name: "gcp-cloud-run-deploy",
        label: "GCP Cloud Run Deploy",
        description: "Deploy a revision to Cloud Run",
        type: "component",
        outputChannels: [
          { id: "deployed", label: "Deployed" } as any,
          { id: "failed", label: "Failed" } as any,
        ],
        configuration: [
          { key: "service", label: "Service", type: "string", required: true },
          { key: "image", label: "Image", type: "string", required: true },
          { key: "region", label: "Region", type: "string", required: false },
          { key: "env", label: "Env Vars", type: "json", required: false },
        ],
        icon: "cloud",
        color: "blue",
      },
      {
        name: "gcp-pubsub-publish",
        label: "GCP Pub/Sub Publish",
        description: "Publish a message to a Pub/Sub topic",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          { key: "topic", label: "Topic", type: "string", required: true },
          { key: "message", label: "Message", type: "text", required: true },
          {
            key: "attributes",
            label: "Attributes",
            type: "json",
            required: false,
          },
        ],
        icon: "cloud",
        color: "blue",
      },
      {
        name: "gcp-gke-rollout",
        label: "GCP GKE Rollout",
        description: "Roll out a deployment on GKE",
        type: "component",
        outputChannels: [
          { id: "success", label: "Success" } as any,
          { id: "error", label: "Error" } as any,
        ],
        configuration: [
          { key: "cluster", label: "Cluster", type: "string", required: true },
          {
            key: "namespace",
            label: "Namespace",
            type: "string",
            required: true,
          },
          {
            key: "deployment",
            label: "Deployment",
            type: "string",
            required: true,
          },
          { key: "image", label: "Image", type: "string", required: false },
        ],
        icon: "cloud",
        color: "blue",
      },
      {
        name: "cloudflare-cache-purge",
        label: "Cloudflare Cache Purge",
        description: "Purge cache by URL or everything",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          { key: "zone", label: "Zone ID", type: "string", required: true },
          {
            key: "purgeEverything",
            label: "Purge Everything",
            type: "boolean",
            required: false,
          },
          { key: "urls", label: "URLs", type: "string[]", required: false },
        ],
        icon: "cloud",
        color: "yellow",
      },
      {
        name: "cloudflare-dns-update",
        label: "Cloudflare DNS Update",
        description: "Create or update a DNS record",
        type: "component",
        outputChannels: [{ id: "next", label: "Next" } as any],
        configuration: [
          { key: "zone", label: "Zone ID", type: "string", required: true },
          {
            key: "type",
            label: "Type",
            type: "enum",
            values: ["A", "AAAA", "CNAME", "TXT"],
            required: true,
          },
          { key: "name", label: "Name", type: "string", required: true },
          { key: "content", label: "Content", type: "string", required: true },
          { key: "ttl", label: "TTL", type: "number", required: false },
          {
            key: "proxied",
            label: "Proxied",
            type: "boolean",
            required: false,
          },
        ],
        icon: "cloud",
        color: "yellow",
      },
      {
        name: "cloudflare-workers-deploy",
        label: "Cloudflare Workers Deploy",
        description: "Deploy a Worker script to a route",
        type: "component",
        outputChannels: [
          { id: "deployed", label: "Deployed" } as any,
          { id: "failed", label: "Failed" } as any,
        ],
        configuration: [
          {
            key: "scriptName",
            label: "Script Name",
            type: "string",
            required: true,
          },
          { key: "route", label: "Route", type: "string", required: false },
          {
            key: "accountId",
            label: "Account ID",
            type: "string",
            required: false,
          },
        ],
        icon: "cloud",
        color: "yellow",
      },
    ],
  },
  {
    name: "Blueprints",
    blocks: [
      // Complex user-built components
      {
        name: "deployment",
        label: "Deployment",
        description: "Standardized deploy flow across environments",
        type: "blueprint",
        outputChannels: [
          { id: "success", label: "Success" } as any,
          { id: "failed", label: "Failed" } as any,
        ],
        configuration: [
          {
            key: "environment",
            label: "Environment",
            type: "enum",
            values: ["dev", "staging", "prod"],
            required: true,
          },
          {
            key: "strategy",
            label: "Strategy",
            type: "enum",
            values: ["rolling", "blue-green", "canary"],
            required: false,
          },
          { key: "version", label: "Version", type: "string", required: true },
        ],
        icon: "truck",
        color: "blue",
        id: "bp-deployment",
      },
      {
        name: "incident-monitor",
        label: "Incident Monitor",
        description: "Detect, triage, and route incidents",
        type: "blueprint",
        outputChannels: [
          { id: "resolved", label: "Resolved" } as any,
          { id: "escalated", label: "Escalated" } as any,
        ],
        configuration: [
          {
            key: "sources",
            label: "Sources",
            type: "string[]",
            required: false,
          },
          {
            key: "sevThreshold",
            label: "Severity Threshold",
            type: "enum",
            values: ["low", "medium", "high", "critical"],
            required: false,
          },
          {
            key: "onCallSchedule",
            label: "On-call Schedule",
            type: "string",
            required: false,
          },
        ],
        icon: "alert-triangle",
        color: "orange",
        id: "bp-incident-monitor",
      },
    ],
  },
];
