// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.15.8
// source: manifests.proto

package manifests

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManifestService_GetManifests_FullMethodName = "/Superplane.ManifestService/GetManifests"
)

// ManifestServiceClient is the client API for ManifestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManifestServiceClient interface {
	GetManifests(ctx context.Context, in *GetManifestsRequest, opts ...grpc.CallOption) (*GetManifestsResponse, error)
}

type manifestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManifestServiceClient(cc grpc.ClientConnInterface) ManifestServiceClient {
	return &manifestServiceClient{cc}
}

func (c *manifestServiceClient) GetManifests(ctx context.Context, in *GetManifestsRequest, opts ...grpc.CallOption) (*GetManifestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManifestsResponse)
	err := c.cc.Invoke(ctx, ManifestService_GetManifests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManifestServiceServer is the server API for ManifestService service.
// All implementations should embed UnimplementedManifestServiceServer
// for forward compatibility.
type ManifestServiceServer interface {
	GetManifests(context.Context, *GetManifestsRequest) (*GetManifestsResponse, error)
}

// UnimplementedManifestServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManifestServiceServer struct{}

func (UnimplementedManifestServiceServer) GetManifests(context.Context, *GetManifestsRequest) (*GetManifestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManifests not implemented")
}
func (UnimplementedManifestServiceServer) testEmbeddedByValue() {}

// UnsafeManifestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManifestServiceServer will
// result in compilation errors.
type UnsafeManifestServiceServer interface {
	mustEmbedUnimplementedManifestServiceServer()
}

func RegisterManifestServiceServer(s grpc.ServiceRegistrar, srv ManifestServiceServer) {
	// If the following call pancis, it indicates UnimplementedManifestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManifestService_ServiceDesc, srv)
}

func _ManifestService_GetManifests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManifestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestServiceServer).GetManifests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManifestService_GetManifests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestServiceServer).GetManifests(ctx, req.(*GetManifestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManifestService_ServiceDesc is the grpc.ServiceDesc for ManifestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManifestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Superplane.ManifestService",
	HandlerType: (*ManifestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManifests",
			Handler:    _ManifestService_GetManifests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manifests.proto",
}
