import { canvasAppIds } from "@/pages/app/__fixtures__/handlers";

import type { WorkspacePageData } from "../types";

export const projectXWorkspaceData = {
  project: {
    name: "Project X Factory",
    description: "Plans, implements, verifies, and delivers well-specified product work across Project X.",
    status: "operational",
    repositories: [
      { id: "project-x", name: "superplane/project-x", defaultBranch: "main" },
      { id: "project-x-api", name: "superplane/project-x-api", defaultBranch: "main" },
      { id: "project-x-web", name: "superplane/project-x-web", defaultBranch: "main" },
    ],
  },
  repositoryVelocity: {
    period: "Last 14 days",
    defaultRepositoryId: "project-x",
    cohorts: [
      {
        id: "team",
        label: "Team total",
        description: "All merged work",
      },
      {
        id: "human",
        label: "Human-authored",
        description: "Git account authors",
      },
      {
        id: "factory",
        label: "Factory-authored",
        description: "Factory work orders",
      },
    ],
    metrics: [
      {
        id: "throughput",
        label: "Merged pull requests",
        description: "Pull requests merged into the default branch",
        values: {
          team: { value: "42", detail: "21.0 per week", trend: "Up 12% vs prior period" },
          human: { value: "41", detail: "20.5 per week", trend: "Up 9% vs prior period" },
          factory: { value: "1", detail: "0.5 per week", trend: "First Factory merge" },
        },
      },
      {
        id: "cycle-time",
        label: "Median cycle time",
        description: "First commit to merge",
        values: {
          team: { value: "13h 54m", detail: "All merged PRs", trend: "2h 18m faster" },
          human: { value: "14h 12m", detail: "Human-authored PRs", trend: "2h 02m faster" },
          factory: { value: "42m", detail: "Factory-authored PRs", trend: "1 completed sample" },
        },
      },
      {
        id: "success-rate",
        label: "Success rate",
        description: "Completed changes without rollback or unsuccessful outcome",
        values: {
          team: { value: "95.5%", detail: "42 completed changes" },
          human: { value: "95.1%", detail: "41 completed changes" },
          factory: { value: "100%", detail: "1 completed work order" },
        },
      },
      {
        id: "execution-cost",
        label: "Tracked execution cost",
        description: "Model tokens and execution compute",
        values: {
          team: { value: "$184", detail: "Factory cost included" },
          human: { value: "Not attributed", detail: "Human labor is outside scope", unavailable: true },
          factory: { value: "$184", detail: "$184 per merged PR" },
        },
      },
    ],
    trend: [
      { label: "Jul 16", team: 2, human: 2, factory: 0 },
      { label: "Jul 17", team: 4, human: 4, factory: 0 },
      { label: "Jul 18", team: 3, human: 3, factory: 0 },
      { label: "Jul 19", team: 1, human: 1, factory: 0 },
      { label: "Jul 20", team: 2, human: 2, factory: 0 },
      { label: "Jul 21", team: 5, human: 5, factory: 0 },
      { label: "Jul 22", team: 3, human: 3, factory: 0 },
      { label: "Jul 23", team: 4, human: 4, factory: 0 },
      { label: "Jul 24", team: 2, human: 2, factory: 0 },
      { label: "Jul 25", team: 5, human: 5, factory: 0 },
      { label: "Jul 26", team: 1, human: 1, factory: 0 },
      { label: "Jul 27", team: 3, human: 3, factory: 0 },
      { label: "Jul 28", team: 3, human: 3, factory: 0 },
      { label: "Jul 29", team: 4, human: 3, factory: 1 },
    ],
    costBreakdown: {
      tokens: "$126",
      compute: "$58",
      total: "$184",
      note: "Includes model tokens and execution compute. Third-party service charges are excluded.",
    },
  },
  metrics: [
    { id: "throughput", label: "Work orders completed", value: "12", detail: "Last 14 days", tone: "neutral" },
    { id: "success", label: "Factory success rate", value: "92.3%", detail: "Up 3.1 points", tone: "positive" },
    { id: "active", label: "Active work", value: "5", detail: "3 running, 2 need input", tone: "neutral" },
    { id: "cost", label: "Tracked execution cost", value: "$184", detail: "Tokens and compute", tone: "neutral" },
  ],
  automations: [
    {
      id: "issue-intake",
      canvasId: canvasAppIds.canvasId,
      name: "Issue intake",
      description: "Creates draft work orders from eligible GitHub issues.",
      trigger: "Issue assigned to Factory",
      status: "active",
      activeWorkItems: 0,
      successRate: "98.7%",
      lastRun: "8m ago",
    },
    {
      id: "plan-and-build",
      canvasId: canvasAppIds.canvasId,
      name: "Plan and build",
      description: "Plans approved work and implements the change on a branch.",
      trigger: "Work order becomes ready",
      status: "active",
      activeWorkItems: 3,
      successRate: "94.1%",
      lastRun: "Now",
    },
    {
      id: "verify-and-deliver",
      canvasId: canvasAppIds.canvasId,
      name: "Verify and deliver",
      description: "Runs checks, prepares the pull request, and records the outcome.",
      trigger: "Implementation completed",
      status: "active",
      activeWorkItems: 2,
      successRate: "91.8%",
      lastRun: "2m ago",
    },
    {
      id: "dependency-maintenance",
      canvasId: canvasAppIds.canvasId,
      name: "Dependency maintenance",
      description: "Handles low-risk dependency and backend maintenance work.",
      trigger: "Weekly schedule",
      status: "paused",
      activeWorkItems: 0,
      successRate: "96.2%",
      lastRun: "6d ago",
    },
  ],
  stages: [
    { id: "intake", label: "Intake", detail: "Issue accepted", state: "complete" },
    { id: "plan", label: "Plan", detail: "Scope prepared", state: "complete" },
    { id: "build", label: "Build", detail: "3 agents active", state: "active" },
    { id: "verify", label: "Verify", detail: "Tests and review", state: "active" },
    { id: "deliver", label: "Deliver", detail: "Merge to main", state: "queued" },
  ],
  workItems: [
    {
      id: "PX-131",
      title: "Choose session recovery fallback",
      stage: "Plan",
      branch: "feat/session-recovery",
      agentCount: 1,
      elapsed: "6m",
      status: "attention",
      detail: "Agent needs a decision: refresh the token or force sign-in.",
      updatedAt: "4m ago",
    },
    {
      id: "PX-130",
      title: "Approve production migration window",
      stage: "Approval",
      branch: "chore/billing-migration",
      agentCount: 1,
      elapsed: "18m",
      status: "attention",
      detail: "Release is paused until a production window is approved.",
      updatedAt: "11m ago",
    },
    {
      id: "PX-128",
      title: "Add SSO session recovery",
      stage: "Verify",
      branch: "feat/sso-recovery",
      agentCount: 3,
      elapsed: "12m",
      status: "running",
      detail: "Test suite is running across four environments.",
      updatedAt: "Now",
    },
    {
      id: "PX-127",
      title: "Improve retry diagnostics",
      stage: "Build",
      branch: "feat/retry-diagnostics",
      agentCount: 2,
      elapsed: "28m",
      status: "running",
      detail: "Implementing structured retry traces.",
      updatedAt: "2m ago",
    },
    {
      id: "PX-126",
      title: "Fix stale deployment status",
      stage: "Review",
      branch: "fix/deployment-status",
      agentCount: 3,
      elapsed: "46m",
      status: "running",
      detail: "Automated reviewer is checking the final patch.",
      updatedAt: "3m ago",
    },
    {
      id: "PX-125",
      title: "Add rate limit metrics",
      stage: "Delivered",
      branch: "feat/rate-limit-metrics",
      agentCount: 2,
      elapsed: "38m",
      status: "done",
      detail: "PR #342 merged to main.",
      updatedAt: "18m ago",
    },
    {
      id: "PX-124",
      title: "Add webhook replay controls",
      stage: "Delivered",
      branch: "feat/webhook-replay",
      agentCount: 3,
      elapsed: "1h 12m",
      status: "done",
      detail: "PR #339 merged to main.",
      updatedAt: "2h ago",
    },
    {
      id: "PX-123",
      title: "Enforce audit log retention",
      stage: "Delivered",
      branch: "feat/audit-retention",
      agentCount: 2,
      elapsed: "58m",
      status: "done",
      detail: "PR #335 merged to main.",
      updatedAt: "Yesterday",
    },
    {
      id: "PX-122",
      title: "Upgrade billing schema",
      stage: "Verify",
      branch: "chore/billing-schema",
      agentCount: 1,
      elapsed: "23m",
      status: "failed",
      detail: "Integration tests failed in the billing sandbox.",
      updatedAt: "3h ago",
    },
  ],
  throughput: [
    { label: "Mon", value: 0 },
    { label: "Tue", value: 0 },
    { label: "Wed", value: 0 },
    { label: "Thu", value: 0 },
    { label: "Fri", value: 0 },
    { label: "Sat", value: 0 },
    { label: "Sun", value: 0 },
  ],
} satisfies WorkspacePageData;
