export const OWNER_SETUP_COPY = {
  smtp: {
    headline: "Send email from this installation",
    body: "SMTP sends invites and magic codes. The owner password login works without it.",
    save: "Save and continue",
    saving: "Saving…",
    skip: "Skip for now",
    host: "SMTP host",
    port: "SMTP port",
    username: "SMTP username",
    password: "SMTP password",
    fromName: "From name",
    fromEmail: "From email",
    useTls: "Use TLS (STARTTLS)",
    useTlsHelp: "Encrypt the connection to the SMTP server.",
    required: "Enter the SMTP host, port, and from email.",
    error: "SuperPlane could not save SMTP settings. Check the values and try again.",
  },
  fleet: {
    headline: "Configure Fleet Manager",
    body: "SuperPlane does not call Fleet Manager. Copy this YAML into the Fleet Manager configuration, then apply it.",
    helper: "Replace the placeholder values with the values from your Terraform ConfigMap.",
    copy: "Copy YAML",
    copied: "Copied",
    continue: "Continue",
    skip: "Skip for now",
    loading: "Preparing Fleet Manager configuration…",
    error: "SuperPlane could not prepare Fleet Manager. Try again, or skip this step.",
    retry: "Try again",
  },
  pane: {
    owner: "Awaiting owner",
    license: "Awaiting edition",
    smtp: "Awaiting email",
    fleet: "Awaiting runners",
  },
} as const;
