package actions

func defaultRunTitleExpression(triggerName string) string {
	return defaultRunTitleExpressions[triggerName]
}

var defaultRunTitleExpressions = map[string]string{
	"start":    "Event emitted by trigger",
	"schedule": "Schedule",
	"webhook":  "Webhook event",

	"aws.cloudwatch.onAlarm":            "{{ root().data.alarmName }}",
	"aws.codeArtifact.onPackageVersion": "{{ root().data.detail.packageName }} {{ root().data.detail.packageVersion }}",
	"aws.codepipeline.onPipeline":       "{{ root().data.detail.pipeline }}",
	"aws.ec2.onAlarm":                   "{{ root().data.alarmName }}",
	"aws.ec2.onImage":                   "{{ root().data.detail[\"image-id\"] }}",
	"aws.ecr.onImagePush":               "{{ root().data.detail[\"repository-name\"] }}:{{ root().data.detail[\"image-tag\"] }}",
	"aws.ecr.onImageScan":               "{{ root().data.detail[\"repository-name\"] }}:{{ root().data.detail[\"image-tag\"] }}",
	"aws.sns.onTopicMessage":            "{{ root().data.Subject }}",

	"azure.onBlobCreated":           "{{ root().data.subject }}",
	"azure.onBlobDeleted":           "{{ root().data.subject }}",
	"azure.onContainerImageDeleted": "{{ root().data.subject }}",
	"azure.onContainerImagePushed":  "{{ root().data.subject }}",
	"azure.onVMDeallocated":         "{{ root().data.subject }}",
	"azure.onVMDeleted":             "{{ root().data.subject }}",
	"azure.onVMRestarted":           "{{ root().data.subject }}",
	"azure.onVMStarted":             "{{ root().data.subject }}",
	"azure.onVMStopped":             "{{ root().data.subject }}",
	"bitbucket.onPush":              "{{ root().data.push.changes[0].new.name }}",
	"circleci.onWorkflowCompleted":  "{{ root().data.workflow.name }}",

	"cloudflare.onLoadBalancingHealthAlert": "{{ root().data.alert_type }}",
	"cloudflare.onTunnelHealth":             "{{ root().data.tunnel_name }}",
	"dash0.onAlertNotification":             "{{ root().data.alert.title }}",
	"dash0.onSyntheticCheckNotification":    "{{ root().data.check.name }}",
	"dockerhub.onImagePush":                 "{{ root().data.repository.repo_name }}:{{ root().data.push_data.tag }}",
	"elastic.onAlertFires":                  "{{ root().data.rule.name }}",
	"elastic.onCaseStatusChange":            "{{ root().data.case.title }}",
	"elastic.onDocumentIndexed":             "{{ root().data._index }}",
	"firehydrant.onIncident":                "{{ root().data.name }}",

	"gcp.artifactregistry.onArtifactAnalysis": "{{ root().data.package }}",
	"gcp.artifactregistry.onArtifactPush":     "{{ root().data.package }}",
	"gcp.cloudbuild.onBuildComplete":          "{{ root().data.substitutions.BRANCH_NAME }}",
	"gcp.compute.onVMInstance":                "{{ root().data.resource.labels.instance_id }}",
	"gcp.pubsub.onMessage":                    "{{ root().data.message.messageId }}",

	"github.onBranchCreated":   "{{ root().data.ref }}",
	"github.onCheckRun":        "{{ root().data.check_run.name }} {{ root().data.check_run.conclusion }} - {{ root().data.check_run.head_sha }}",
	"github.onCommitStatus":    "{{ root().data.context }} {{ root().data.state }} - {{ root().data.sha }}",
	"github.onIssue":           "#{{ root().data.issue.number }} - {{ root().data.issue.title }}",
	"github.onIssueComment":    "#{{ root().data.issue.number }} - {{ root().data.issue.title }}",
	"github.onPRComment":       "#{{ root().data.issue.number }} - {{ root().data.issue.title }}",
	"github.onPRReviewComment": "#{{ root().data.pull_request.number }} - {{ root().data.pull_request.title }}",
	"github.onPullRequest":     "#{{ root().data.number }} - {{ root().data.pull_request.title }}",
	"github.onPush":            "{{ root().data.head_commit.message }}",
	"github.onRelease":         "{{ root().data.release.name }}",
	"github.onTagCreated":      "{{ root().data.ref }}",
	"github.onWorkflowRun":     "{{ root().data.workflow_run.display_title }}",

	"gitlab.onIssue":         "#{{ root().data.object_attributes.iid }} - {{ root().data.object_attributes.title }}",
	"gitlab.onMergeRequest":  "!{{ root().data.object_attributes.iid }} - {{ root().data.object_attributes.title }}",
	"gitlab.onMilestone":     "{{ root().data.object_attributes.title }}",
	"gitlab.onPipeline":      "{{ root().data.object_attributes.ref }}",
	"gitlab.onRelease":       "{{ root().data.name }}",
	"gitlab.onTag":           "{{ root().data.ref }}",
	"gitlab.onVulnerability": "{{ root().data.vulnerability.name }}",

	"grafana.onAlertFiring":               "{{ root().data.title }}",
	"harness.onPipelineCompleted":         "{{ root().data.data.pipeline.name }}",
	"honeycomb.onAlertFired":              "{{ root().data.alert.name }}",
	"incident.onIncident":                 "{{ root().data.incident.name }}",
	"jfrogArtifactory.onArtifactUploaded": "{{ root().data.domain }}",
	"launchdarkly.onFeatureFlagChange":    "{{ root().data.flag.name }}",
	"logfire.onAlertReceived":             "{{ root().data.alert_name }}",
	"newrelic.onIssue":                    "{{ root().data.issueTitle }}",
	"oci.onComputeInstanceCreated":        "{{ root().data.data.resourceName }}",
	"oci.onInstanceStateChange":           "{{ root().data.data.resourceName }}",
	"octopus.onDeploymentEvent":           "{{ root().data.Event.Message }}",
	"pagerduty.onIncident":                "{{ root().data.event.data.title }}",
	"pagerduty.onIncidentAnnotated":       "{{ root().data.event.data.title }}",
	"pagerduty.onIncidentStatusUpdate":    "{{ root().data.event.data.message }}",
	"prometheus.onAlert":                  "{{ root().data.commonLabels.alertname }}",
	"render.onBuild":                      "{{ root().data.service.name }}",
	"render.onDeploy":                     "{{ root().data.service.name }}",
	"rootly.onIncident":                   "{{ root().data.data.attributes.title }}",
	"rootly.onIncidentTimelineEvent":      "{{ root().data.data.attributes.summary }}",
	"semaphore.onPipelineDone":            "{{ root().data.pipeline.name }}",
	"sendgrid.onEmailEvent":               "{{ root().data.email }}",
	"sentry.onIssue":                      "{{ root().data.data.issue.title }}",
	"slack.onAppMention":                  "{{ root().data.event.text }}",
	"teams.onMention":                     "{{ root().data.text }}",
	"teams.onMessage":                     "{{ root().data.text }}",
	"telegram.onMention":                  "{{ root().data.message.text }}",
}
