package actions

func defaultRunTitleExpression(triggerName string) string {
	return defaultRunTitleExpressions[triggerName]
}

var defaultRunTitleExpressions = map[string]string{
	"start":       "Manual run {{ date(root().timestamp).Format(\"2006-01-02 15:04:05\") }}",
	"schedule":    "Schedule {{ root().data.calendar.month }} {{ root().data.calendar.day }} {{ root().data.calendar.hour }}:{{ root().data.calendar.minute }}",
	"webhook":     "Webhook {{ date(root().timestamp).Format(\"2006-01-02 15:04:05\") }}",
	"onError":     "{{ root().data.node.name }} errored",
	"onBroadcast": "{{ root().data.app.name }}",
	"onRun":       "App run {{ date(root().timestamp).Format(\"2006-01-02 15:04:05\") }}",

	"aws.cloudwatch.onAlarm":            "{{ root().data.detail.alarmName }} - {{ root().data.detail.previousState.value }} -> {{ root().data.detail.state.value }}",
	"aws.codeArtifact.onPackageVersion": "{{ root().data.detail.packageName }} {{ root().data.detail.packageVersion }}",
	"aws.codepipeline.onPipeline":       "{{ root().data.detail.pipeline }}",
	"aws.ec2.onAlarm":                   "{{ root().data.detail.alarmName }} - {{ root().data.detail.previousState.value }} -> {{ root().data.detail.state.value }}",
	"aws.ec2.onImage":                   "{{ root().data.detail.ImageId }} {{ root().data.detail.State }}",
	"aws.ecr.onImagePush":               "{{ root().data.detail[\"repository-name\"] }}:{{ root().data.detail[\"image-tag\"] }}",
	"aws.ecr.onImageScan":               "{{ root().data.detail[\"repository-name\"] }} scan {{ root().data.detail[\"scan-status\"] }} - {{ root().data.detail[\"image-digest\"][:19] }}",
	"aws.sns.onTopicMessage":            "{{ root().data.subject }}",

	"azure.onBlobCreated":               "{{ root().data.subject }}",
	"azure.onBlobDeleted":               "{{ root().data.subject }}",
	"azure.onContainerImageDeleted":     "{{ root().data.subject }}",
	"azure.onContainerImagePushed":      "{{ root().data.subject }}",
	"azure.onVirtualMachineDeallocated": "{{ root().data.subject }}",
	"azure.onVirtualMachineDeleted":     "{{ root().data.subject }}",
	"azure.onVirtualMachineRestarted":   "{{ root().data.subject }}",
	"azure.onVirtualMachineStarted":     "{{ root().data.subject }}",
	"azure.onVirtualMachineStopped":     "{{ root().data.subject }}",
	"bitbucket.onPush":                  "{{ root().data.push.changes[0].new.name }}",
	"circleci.onWorkflowCompleted":      "{{ root().data.workflow.name }}",

	"cloudflare.onLoadBalancingHealthAlert": "{{ root().data.alert_type }}",
	"cloudflare.onTunnelHealth":             "{{ root().data.tunnel_name }}",
	"cloudsmith.onPackageCreated":           "{{ root().data.name }} {{ root().data.version }} ({{ root().data.format }})",
	"cloudsmith.onSecurityScanCompleted":    "{{ root().data.name }} {{ root().data.version }} - {{ root().data.security_scan_status }}",
	"dash0.onAlertNotification":             "{{ root().data.issue.summary }}",
	"dash0.onSyntheticCheckNotification":    "{{ root().data.issue.summary }}",
	"dockerhub.onImagePush":                 "{{ root().data.repository.repo_name }}:{{ root().data.push_data.tag }}",
	"elastic.onAlertFires":                  "{{ root().data.ruleName }}",
	"elastic.onCaseStatusChange":            "{{ root().data.title }}",
	"elastic.onDocumentIndexed":             "{{ root().data.index }}",
	"firehydrant.onIncident":                "#{{ root().data.incident.number }} - {{ root().data.incident.name }}",

	"gcp.artifactregistry.onArtifactAnalysis": "{{ root().data.resourceUri }}",
	"gcp.artifactregistry.onArtifactPush":     "{{ root().data.tag }}",
	"gcp.cloudbuild.onBuildComplete":          "{{ root().data.status }} - {{ root().data.id }}",
	"gcp.compute.onVMInstance":                "{{ root().data.resourceName }}",
	"gcp.monitoring.onAlert":                  "{{ root().data.conditionName }} {{ root().data.state }} - {{ root().data.resourceName }}",
	"gcp.pubsub.onMessage":                    "{{ root().data.messageId }}",

	"github.onBranchCreated":   "{{ root().data.ref }}",
	"github.onCheckRun":        "{{ root().data.check_run.name }} {{ root().data.check_run.conclusion }} - {{ root().data.check_run.head_sha[:7] }}",
	"github.onCommitStatus":    "{{ root().data.context }} {{ root().data.state }} - {{ root().data.sha[:7] }}",
	"github.onIssue":           "#{{ root().data.issue.number }} - {{ root().data.issue.title }}",
	"github.onIssueComment":    "#{{ root().data.issue.number }} - {{ root().data.issue.title }}",
	"github.onPRComment":       "#{{ root().data.issue.number }} - {{ root().data.issue.title }}",
	"github.onPRReviewComment": "#{{ root().data.pull_request.number }} - {{ root().data.pull_request.title }}",
	"github.onPullRequest":     "#{{ root().data.number }} - {{ root().data.pull_request.title }}",
	"github.onPush":            "{{ root().data.head_commit.message }} - {{ root().data.head_commit.id[:7] }}",
	"github.onRelease":         "{{ root().data.release.name }}",
	"github.onTagCreated":      "{{ root().data.ref }}",
	"github.onWorkflowRun":     "{{ root().data.workflow_run.name }} {{ root().data.workflow_run.conclusion }} #{{ root().data.workflow_run.run_number }}",

	"gitlab.onBranchCreated": "{{ root().data.ref }}",
	"gitlab.onIssue":         "#{{ root().data.object_attributes.iid }} - {{ root().data.object_attributes.title }}",
	"gitlab.onIssueComment":  "#{{ root().data.issue.iid }} - {{ root().data.issue.title }}",
	"gitlab.onMergeComment":  "!{{ root().data.merge_request.iid }} - {{ root().data.merge_request.title }}",
	"gitlab.onMergeRequest":  "!{{ root().data.object_attributes.iid }} - {{ root().data.object_attributes.title }}",
	"gitlab.onMRDiffNote":    "!{{ root().data.merge_request.iid }} - {{ root().data.merge_request.title }}",
	"gitlab.onMilestone":     "{{ root().data.object_attributes.title }}",
	"gitlab.onPipeline":      "{{ root().data.object_attributes.ref }}",
	"gitlab.onPush":          "{{ root().data.commits != nil && len(root().data.commits) > 0 ? root().data.commits[-1].message + \" - \" + root().data.commits[-1].id[:7] : root().data.ref }}",
	"gitlab.onRelease":       "{{ root().data.name }}",
	"gitlab.onTag":           "{{ root().data.ref }}",
	"gitlab.onVulnerability": "{{ root().data.object_attributes.title }}",

	"grafana.onAlertFiring":               "{{ root().data.title }}",
	"harness.onPipelineCompleted":         "{{ root().data.pipelineIdentifier }} {{ root().data.status }}",
	"honeycomb.onAlertFired":              "{{ root().data.name }}",
	"incident.onIncident":                 "{{ root().data.incident.name }}",
	"jfrogArtifactory.onArtifactUploaded": "{{ root().data.name }} in {{ root().data.repo }}",
	"jira.onIssue":                        "{{ root().data.issue.key }} - {{ root().data.issue.fields.summary }}",
	"launchdarkly.onFeatureFlagChange":    "{{ root().data.name }}",
	"linear.onIssue":                      "{{ root().data.data.identifier }} - {{ root().data.data.title }}",
	"logfire.onAlertReceived":             "{{ root().data.alertName }}",
	"newrelic.onIssue":                    "{{ root().data.title }} {{ root().data.state }}",
	"oci.onComputeInstanceCreated":        "{{ root().data.data.resourceName }}",
	"oci.onInstanceStateChange":           "{{ root().data.data.resourceName }}",
	"octopus.onDeploymentEvent":           "{{ root().data.message }}",
	"pagerduty.onIncident":                "{{ root().data.incident.title }}",
	"pagerduty.onIncidentAnnotated":       "{{ root().data.incident.title }}",
	"pagerduty.onIncidentStatusUpdate":    "{{ root().data.status_update.message }}",
	"prometheus.onAlert":                  "{{ root().data.commonLabels.alertname }}",
	"render.onBuild":                      "{{ root().data.serviceName }} {{ root().data.status }}",
	"render.onDeploy":                     "{{ root().data.serviceName }} {{ root().data.status }}",
	"rootly.onIncident":                   "{{ root().data.incident.title }}",
	"rootly.onIncidentTimelineEvent":      "{{ root().data.event }}",
	"semaphore.onPipelineDone":            "{{ root().data.pipeline.name }}",
	"sendgrid.onEmailEvent":               "{{ root().data.email }}",
	"sentry.onIssue":                      "{{ root().data.data.issue.title }}",
	"slack.onAppMention":                  "{{ root().data.event.text }}",
	"teams.onMention":                     "{{ root().data.text }}",
	"teams.onMessage":                     "{{ root().data.text }}",
	"telegram.onMention":                  "{{ root().data.text }}",
}
