export const CREATE_WITH_AGENT_COPY = {
  menu: "Create with an Agent",
  title: "New task with an agent",
  endSession: "End session",
  endSessionAsk: "End this session?",
  endSessionBody: "The machine will stop. Tasks you already created stay in the backlog.",
  endSessionConfirm: "End session",
  keepSession: "Keep session",
  send: "Send",
  composerPlaceholder: "Tell the agent what you want to do",
  machineStarting: "The machine is starting",
  machineRunning: "Machine is running",
  machineWaiting: "Waiting for you",
  emptyHeadline: "Waiting for your first work order.",
  emptyBody: "The agent will draft a task here.",
  draftLabel: "Draft task",
  create: "Create",
  skip: "Skip",
  openTask: "Open task",
  greeting: "The repository is ready. What do you want to do?",
  afterCreate: "Created the draft task. Work on a new one, or tell me what is next.",
  afterSkip: "Skipped that draft. What should we do next?",
  failedStart: "Failed to start the session.",
  failedSend: "Failed to send the message.",
  failedDraft: "Failed to save the draft.",
  failedCreate: "Failed to create the task.",
  failedSkip: "Failed to skip the draft.",
} as const;
