export const PLANNING_SETTINGS_COPY = {
  tabsLabel: "Planning settings",
  title: "Planning",
  generalTab: "General",
  agentTab: "Agent",
  automationTab: "Automation",
  planningLabel: "Planning",
  planningHelper: "When Planning is on, SuperPlane opens a chat and writes a plan for each new draft task.",
  clarityLabel: "Clarity score",
  clarityHelper: "Show how well the task is defined.",
  confidenceLabel: "Confidence score",
  confidenceHelper: "Show how likely an agent completes the task in one run.",
  healthReady: "Ready",
  healthDisabled: "Off",
  healthReadyHelper: "This automation writes a plan for each new draft task.",
  healthDisabledHelper: "New draft tasks stay in Backlog without a Planning chat.",
  save: "Save",
  saving: "Saving",
  saveError: "Could not save Planning settings.",
  loading: "Loading Planning settings.",
  loadError: "Could not load Planning settings.",
  retry: "Retry",
  automationEmpty: "This automation has no steps yet.",
  automationLoading: "Loading the steps.",
  automationError: "Could not load the steps.",
  wizardPageTitle: "How should new backlog tasks be refined?",
  wizardBannerDescription: "SuperPlane can open a chat and write a plan for each new draft task.",
  wizardBadgeLabel: "Configure backlog refinement",
  wizardStepRefine: "How should new backlog tasks be refined?",
  wizardRefineOption: "Refine with a plan",
  wizardRefineHelper: "SuperPlane opens a chat and writes a plan for each new draft.",
  wizardSourceOption: "Keep the source description",
  wizardSourceHelper: "New drafts stay in Backlog with the source text only.",
  wizardStepScores: "Which scores should SuperPlane show?",
  wizardScoresIntro: "These scores help you decide when a draft is ready to start.",
  wizardClarityOnOption: "Show Clarity",
  wizardClarityOnHelper: "Show how well the task is defined.",
  wizardClarityOffOption: "Hide Clarity",
  wizardClarityOffHelper: "Do not show a Clarity score on drafts.",
  wizardConfidenceOnOption: "Show Confidence",
  wizardConfidenceOnHelper: "Show how likely an agent completes the task in one run.",
  wizardConfidenceOffOption: "Hide Confidence",
  wizardConfidenceOffHelper: "Do not show a Confidence score on drafts.",
  wizardContinue: "Continue",
  wizardFinish: "Finish",
  wizardFinishing: "Finishing...",
  wizardBackToBoard: "Back to board",
  wizardBack: "Back",
  wizardPreviewLabel: "Example draft task",
  wizardPreviewRefineCaption: "A chat writes a plan for the draft.",
  wizardPreviewSourceCaption: "The draft shows the source description.",
  wizardPreviewScoresBoth: "Clarity and Confidence appear on the draft.",
  wizardPreviewClarityOnly: "Clarity appears on the draft.",
  wizardPreviewConfidenceOnly: "Confidence appears on the draft.",
  wizardPreviewNoScores: "No scores appear on the draft.",
  wizardFinishError: "Could not save Planning settings.",
} as const;
