import type { Edge, Node } from "@xyflow/react";
import type { StepNodeData } from "./workOrderCanvasTypes";

const MAIN_X = 120;
const SIDE_X = 520;
const EDGE_TYPE = "default";

function step(id: string, position: { x: number; y: number }, data: Omit<StepNodeData, "kind">): Node<StepNodeData> {
  return {
    id,
    type: "step",
    position,
    data: { ...data, kind: "step" },
    draggable: false,
  };
}

function action(
  id: string,
  position: { x: number; y: number },
  data: Omit<StepNodeData, "kind" | "showLogs" | "meta">,
): Node<StepNodeData> {
  return {
    id,
    type: "action",
    position,
    data: { ...data, kind: "action" },
    draggable: false,
  };
}

const nodes: Node<StepNodeData>[] = [
  step(
    "create-branch",
    { x: MAIN_X, y: 0 },
    {
      title: "Create Branch",
      componentName: "Create Branch",
      provider: "github",
      status: "passed",
      detail: "feat/invite-poc · a3f91c2",
      showLogs: true,
      details: {
        startedAt: "14:02:11",
        finishedAt: "14:02:18",
        duration: "7s",
        agent: "git-worker",
        attempt: "1 / 1",
        output: "Branch feat/invite-poc created from main.",
        logs: ["Cloned repository", "Checked out main", "Created feat/invite-poc", "Pushed origin"],
        inputs: ["base: main", "prefix: feat/invite-poc"],
      },
    },
  ),
  step(
    "open-draft-pr",
    { x: MAIN_X, y: 200 },
    {
      title: "Open Draft PR",
      componentName: "Create Pull Request",
      provider: "github",
      status: "created",
      detail: "PR #148 · Draft",
      details: {
        startedAt: "14:02:19",
        finishedAt: "14:02:24",
        duration: "5s",
        agent: "github-worker",
        attempt: "1 / 1",
        output: "Opened draft PR #148 against main.",
        logs: ["Authenticated GitHub app", "Created draft pull request", "Linked task"],
        inputs: ["head: feat/invite-poc", "base: main", "draft: true"],
      },
    },
  ),
  step(
    "write-plan",
    { x: MAIN_X, y: 400 },
    {
      title: "Write Plan",
      componentName: "Agent",
      provider: "superplane",
      status: "passed",
      detail: "Write Plan · plan.md · 12 steps",
      showLogs: true,
      details: {
        startedAt: "14:02:25",
        finishedAt: "14:03:41",
        duration: "1m 16s",
        agent: "planner",
        attempt: "1 / 1",
        output: "Wrote plan.md with 12 implementation steps.",
        logs: ["Read repo context", "Drafted plan", "Committed plan.md", "Posted plan comment"],
        inputs: ["goal: Bind Console widget to latest run", "repo: superplanehq/superplane"],
      },
    },
  ),
  action(
    "action-comment",
    { x: SIDE_X, y: 280 },
    {
      title: "Post plan comment",
      componentName: "Create Issue Comment",
      provider: "github",
      status: "failed",
      detail: "comment · #8841",
      details: {
        startedAt: "14:03:42",
        finishedAt: "14:03:43",
        duration: "1s",
        agent: "github-worker",
        attempt: "1 / 1",
        output: "GitHub API returned 403: Resource not accessible by integration.",
        logs: ["Rendered markdown comment", "Posted via Issues API", "Received 403 Forbidden"],
        inputs: ["issue: #8841"],
      },
    },
  ),
  action(
    "action-notify-start",
    { x: SIDE_X, y: 440 },
    {
      title: "Notify work started",
      componentName: "Send Text Message",
      provider: "slack",
      status: "passed",
      detail: "#factory · work started",
      details: {
        startedAt: "14:03:43",
        finishedAt: "14:03:44",
        duration: "1s",
        agent: "notifier",
        attempt: "1 / 1",
        output: "Sent start notification to #factory.",
        logs: ["Resolved channel", "Posted message"],
        inputs: ["channel: #factory"],
      },
    },
  ),
  action(
    "action-label",
    { x: SIDE_X, y: 600 },
    {
      title: "Add in-progress label",
      componentName: "Add Issue Label",
      provider: "github",
      status: "passed",
      detail: "label · in-progress",
      details: {
        startedAt: "14:03:44",
        finishedAt: "14:03:45",
        duration: "1s",
        agent: "github-worker",
        attempt: "1 / 1",
        output: "Added in-progress label.",
        logs: ["Applied label in-progress"],
        inputs: ["issue: #8841", "label: in-progress"],
      },
    },
  ),
  action(
    "action-correlate",
    { x: SIDE_X, y: 760 },
    {
      title: "Correlate PR Memory",
      componentName: "Add Memory",
      provider: "superplane",
      status: "passed",
      detail: "memory · pr-148",
      details: {
        startedAt: "14:03:45",
        finishedAt: "14:03:46",
        duration: "1s",
        agent: "memory",
        attempt: "1 / 1",
        output: "Linked PR #148 to work-order memory.",
        logs: ["Wrote correlation record"],
        inputs: ["pr: 148", "workOrder: poc-4"],
      },
    },
  ),
  step(
    "implementation",
    { x: MAIN_X, y: 900 },
    {
      title: "Implementation",
      componentName: "Agent",
      provider: "superplane",
      status: "running",
      detail: "Implementation · commits · 4 files",
      showLogs: true,
      details: {
        startedAt: "14:03:47",
        duration: "9m so far",
        agent: "implementor",
        attempt: "1 / 3",
        output: "Editing auth mock routes and tests…",
        logs: [
          "Checked out feat/invite-poc",
          "Updated src/auth/mock.ts",
          "Updated src/auth/session.ts",
          "Running unit tests…",
        ],
        inputs: ["plan.md", "acceptance: mock auth path"],
      },
    },
  ),
  action(
    "action-mark-plan",
    { x: SIDE_X, y: 920 },
    {
      title: "Mark Plan Done",
      componentName: "Update Work Order Status",
      provider: "superplane",
      status: "pending",
      detail: "waits on implementation",
      details: {
        agent: "orchestrator",
        attempt: "—",
        output: "Queued until Implementation passes.",
        inputs: ["dependsOn: Implementation"],
      },
    },
  ),
  step(
    "babysit",
    { x: MAIN_X, y: 1200 },
    {
      title: "Babysit",
      componentName: "Babysit",
      provider: "superplane",
      status: "pending",
      detail: "Software Factory · Timeout: 1h",
      meta: ["Software Factory", "Start Babysitting", "Timeout: 1h"],
      details: {
        agent: "software-factory",
        attempt: "—",
        duration: "Timeout: 1h",
        output: "Will start after Implementation finishes.",
        inputs: ["mode: Start Babysitting", "timeout: 1h"],
      },
    },
  ),
  action(
    "action-mark-impl",
    { x: SIDE_X, y: 1180 },
    {
      title: "Mark Implementation Done",
      componentName: "Update Work Order Status",
      provider: "superplane",
      status: "pending",
      detail: "on babysit passed",
      details: {
        agent: "orchestrator",
        attempt: "—",
        output: "Runs when Babysit reports passed.",
        inputs: ["dependsOn: Babysit / passed"],
      },
    },
  ),
  action(
    "action-notify-fail",
    { x: SIDE_X, y: 1340 },
    {
      title: "Notify work failed",
      componentName: "Send Text Message",
      provider: "slack",
      status: "pending",
      detail: "#factory · on babysit failed",
      details: {
        agent: "notifier",
        attempt: "—",
        output: "Runs when Babysit reports failed.",
        inputs: ["dependsOn: Babysit / failed", "channel: #factory"],
      },
    },
  ),
  action(
    "action-mark-fail-memory",
    { x: SIDE_X, y: 1500 },
    {
      title: "Mark Implementation Failed Memory",
      componentName: "Add Memory",
      provider: "superplane",
      status: "pending",
      detail: "on babysit failed",
      details: {
        agent: "memory",
        attempt: "—",
        output: "Writes failure memory when Babysit fails.",
        inputs: ["dependsOn: Babysit / failed"],
      },
    },
  ),
];

const edges: Edge[] = [
  {
    id: "e-create-pr",
    source: "create-branch",
    sourceHandle: "out",
    target: "open-draft-pr",
    type: EDGE_TYPE,
    data: { tone: "default" },
  },
  {
    id: "e-pr-plan",
    source: "open-draft-pr",
    sourceHandle: "out",
    target: "write-plan",
    type: EDGE_TYPE,
    data: { tone: "default" },
  },
  {
    id: "e-plan-comment",
    source: "write-plan",
    sourceHandle: "side",
    target: "action-comment",
    type: EDGE_TYPE,
    data: { tone: "default" },
  },
  {
    id: "e-plan-notify",
    source: "write-plan",
    sourceHandle: "side",
    target: "action-notify-start",
    type: EDGE_TYPE,
    data: { tone: "default" },
  },
  {
    id: "e-plan-label",
    source: "write-plan",
    sourceHandle: "side",
    target: "action-label",
    type: EDGE_TYPE,
    data: { tone: "default" },
  },
  {
    id: "e-plan-correlate",
    source: "write-plan",
    sourceHandle: "side",
    target: "action-correlate",
    type: EDGE_TYPE,
    data: { tone: "default" },
  },
  {
    id: "e-plan-impl",
    source: "write-plan",
    sourceHandle: "out",
    target: "implementation",
    type: EDGE_TYPE,
    data: { tone: "default" },
  },
  {
    id: "e-impl-mark-plan",
    source: "implementation",
    sourceHandle: "side",
    target: "action-mark-plan",
    type: EDGE_TYPE,
    data: { tone: "default" },
  },
  {
    id: "e-impl-babysit",
    source: "implementation",
    sourceHandle: "out",
    target: "babysit",
    type: EDGE_TYPE,
    animated: true,
    data: { tone: "running" },
  },
  {
    id: "e-babysit-mark",
    source: "babysit",
    sourceHandle: "side",
    target: "action-mark-impl",
    type: EDGE_TYPE,
    data: { tone: "default" },
  },
  {
    id: "e-babysit-notify-fail",
    source: "babysit",
    sourceHandle: "side",
    target: "action-notify-fail",
    type: EDGE_TYPE,
    data: { tone: "failed" },
  },
  {
    id: "e-babysit-fail-memory",
    source: "babysit",
    sourceHandle: "side",
    target: "action-mark-fail-memory",
    type: EDGE_TYPE,
    data: { tone: "failed" },
  },
];

export const WORKFLOW_GRAPH_SEED: { nodes: Node<StepNodeData>[]; edges: Edge[] } = {
  nodes,
  edges,
};
